/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type AccessCheckResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description Whether the user has premium content access
   * @type boolean
   */
  has_premium: boolean;
  /**
   * @description Whether the user has admin access
   * @type boolean
   */
  is_admin: boolean;
};
