/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserRoleResponse } from "./UserRoleResponse.ts";

export type AssignRoleResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description Assigned role
   * @type object
   */
  role: UserRoleResponse;
  /**
   * @description ID of the user
   * @type string
   */
  user_id: string;
};
