/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AssignRoleRequest = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description ID of the role to assign
     * @type string
    */
    role_id: string;
};