/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreatePremiumPostParams = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type string | undefined
   */
  college_id?: string;
  /**
   * @type string
   */
  content: string;
  /**
   * @type string | undefined
   */
  media_id?: string;
  /**
   * @type string | undefined
   */
  sport_id?: string;
  /**
   * @type array,null
   */
  tag: string[] | null;
  /**
   * @type string
   */
  title: string;
};
