/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateTagBody = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description The name of the tag to create
     * @type string
    */
    name: string;
};