/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreatePostLikeResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description ID of the like
     * @type string
    */
    id: string;
    /**
     * @description Whether the requested user has liked the post
     * @type boolean
    */
    liked: boolean;
    /**
     * @description Total number of likes on the post
     * @type integer, int64
    */
    total: number;
};