/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateSportRequest = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type integer,null, int32
    */
    popularity: number | null;
};