/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateCollegeFollowResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description ID of the College
   * @type string
   */
  college_id: string;
  /**
   * @description ID of the college follow created
   * @type string
   */
  id: string;
  /**
   * @description ID of the user
   * @type string
   */
  user_id: string;
};
