/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateStripeCheckoutSessionRequest = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type string
   */
  user_id: string;
  /**
   * @type string
   */
  cancel_url: string;
  /**
   * @type string
   */
  price_id: string;
  /**
   * @type integer, int64
   */
  quantity: number;
  /**
   * @type string
   */
  success_url: string;
};
