/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateTagPostsResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description ID of the tagpost item created
     * @type string
    */
    id: string;
    /**
     * @description ID of the post
     * @type string
    */
    post_id: string;
    /**
     * @description ID of the tag
     * @type string
    */
    tag_id: string;
};