/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateCommentLikeResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description ID of the like
   * @type string
   */
  id: string;
  /**
   * @description Whether the requested user has liked the comment
   * @type boolean
   */
  liked: boolean;
  /**
   * @description Total number of likes on the comment
   * @type integer, int64
   */
  total: number;
};
