/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateTagPostBody = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description ID of the post or premium post
   * @type string
   */
  postable_id: string;
  /**
   * @description Type: post or premium_post
   * @type string
   */
  postable_type: string;
  /**
   * @description ID of the tag
   * @type string
   */
  tag_id: string;
};
