/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateCommentResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description Content of the comment
     * @maxLength 1500
     * @type string
    */
    description: string;
    /**
     * @description ID of comment
     * @type string
    */
    id: string;
    /**
     * @description True if posted as anonymous; frontend can show \'Anonymous\' when user_id is omitted
     * @type boolean
    */
    is_anonymous: boolean;
    /**
     * @description CommentID the comment belongs to
     * @type string
    */
    parent_comment_id: string;
    /**
     * @description PostID the comment belongs to
     * @type string
    */
    post_id: string;
    /**
     * @description The user who commented; omitted for anonymous comments
     * @type string | undefined
    */
    user?: string;
};