/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserRoleResponse } from "./UserRoleResponse.ts";

export type CreateUserResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description ID of the user
   * @type string
   */
  id: string;
  /**
   * @description Name of the user
   * @type string
   */
  name: string;
  /**
   * @description Default role assigned to the user
   * @type object | undefined
   */
  role?: UserRoleResponse;
};
