/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { RoleResponse } from "./RoleResponse.ts";

export type DeleteApiV1RoleByIdPathParams = {
    /**
     * @description ID of the role
     * @maxLength 36
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type DeleteApiV1RoleById200 = RoleResponse;

/**
 * @description Error
*/
export type DeleteApiV1RoleByIdError = ErrorModel;

export type DeleteApiV1RoleByIdMutationResponse = DeleteApiV1RoleById200;

export type DeleteApiV1RoleByIdMutation = {
    Response: DeleteApiV1RoleById200;
    PathParams: DeleteApiV1RoleByIdPathParams;
    Errors: any;
};