/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteTagResponse } from "./DeleteTagResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type DeleteApiV1TagByIdPathParams = {
    /**
     * @description ID to identify tag
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type DeleteApiV1TagById200 = DeleteTagResponse;

/**
 * @description Error
*/
export type DeleteApiV1TagByIdError = ErrorModel;

export type DeleteApiV1TagByIdMutationResponse = DeleteApiV1TagById200;

export type DeleteApiV1TagByIdMutation = {
    Response: DeleteApiV1TagById200;
    PathParams: DeleteApiV1TagByIdPathParams;
    Errors: any;
};