/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DeleteTagFollowResponse } from "./DeleteTagFollowResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type DeleteApiV1UserTagTagByTagIdPathParams = {
  /**
   * @description ID of the tag follow\'s tag to be deleted for current user
   * @type string
   */
  tag_id: string;
};

/**
 * @description OK
 */
export type DeleteApiV1UserTagTagByTagId200 = DeleteTagFollowResponse;

/**
 * @description Error
 */
export type DeleteApiV1UserTagTagByTagIdError = ErrorModel;

export type DeleteApiV1UserTagTagByTagIdMutationResponse =
  DeleteApiV1UserTagTagByTagId200;

export type DeleteApiV1UserTagTagByTagIdMutation = {
  Response: DeleteApiV1UserTagTagByTagId200;
  PathParams: DeleteApiV1UserTagTagByTagIdPathParams;
  Errors: any;
};
