/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AssignRoleRequest } from "./AssignRoleRequest.ts";
import type { AssignRoleResponse } from "./AssignRoleResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type DeleteApiV1UserByIdRolesPathParams = {
  /**
   * @description ID of the user
   * @maxLength 36
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type DeleteApiV1UserByIdRoles200 = AssignRoleResponse;

/**
 * @description Error
 */
export type DeleteApiV1UserByIdRolesError = ErrorModel;

export type DeleteApiV1UserByIdRolesMutationRequest = Omit<
  NonNullable<AssignRoleRequest>,
  "$schema"
>;

export type DeleteApiV1UserByIdRolesMutationResponse =
  DeleteApiV1UserByIdRoles200;

export type DeleteApiV1UserByIdRolesMutation = {
  Response: DeleteApiV1UserByIdRoles200;
  Request: DeleteApiV1UserByIdRolesMutationRequest;
  PathParams: DeleteApiV1UserByIdRolesPathParams;
  Errors: any;
};
