/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { StripePriceResponse } from "./StripePriceResponse.ts";

export type DeleteApiV1StripePriceByIdPathParams = {
  /**
   * @description ID of the product
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type DeleteApiV1StripePriceById200 = StripePriceResponse;

/**
 * @description Error
 */
export type DeleteApiV1StripePriceByIdError = ErrorModel;

export type DeleteApiV1StripePriceByIdMutationResponse =
  DeleteApiV1StripePriceById200;

export type DeleteApiV1StripePriceByIdMutation = {
  Response: DeleteApiV1StripePriceById200;
  PathParams: DeleteApiV1StripePriceByIdPathParams;
  Errors: any;
};
