/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { PermissionResponse } from "./PermissionResponse.ts";

export type DeleteApiV1PermissionByIdPathParams = {
  /**
   * @description ID of the permission
   * @maxLength 36
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type DeleteApiV1PermissionById200 = PermissionResponse;

/**
 * @description Error
 */
export type DeleteApiV1PermissionByIdError = ErrorModel;

export type DeleteApiV1PermissionByIdMutationResponse =
  DeleteApiV1PermissionById200;

export type DeleteApiV1PermissionByIdMutation = {
  Response: DeleteApiV1PermissionById200;
  PathParams: DeleteApiV1PermissionByIdPathParams;
  Errors: any;
};
