/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DeleteContentResponse } from "./DeleteContentResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type DeleteApiV1ContentQueryParams = {
  /**
   * @description S3 object key to delete
   * @type string
   */
  key: string;
};

/**
 * @description OK
 */
export type DeleteApiV1Content200 = DeleteContentResponse;

/**
 * @description Error
 */
export type DeleteApiV1ContentError = ErrorModel;

export type DeleteApiV1ContentMutationResponse = DeleteApiV1Content200;

export type DeleteApiV1ContentMutation = {
  Response: DeleteApiV1Content200;
  QueryParams: DeleteApiV1ContentQueryParams;
  Errors: any;
};
