/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { StripeCheckoutSessionResponse } from "./StripeCheckoutSessionResponse.ts";

export type DeleteApiV1CheckoutSessionsByIdPathParams = {
    /**
     * @description ID of the checkout session
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type DeleteApiV1CheckoutSessionsById200 = StripeCheckoutSessionResponse;

/**
 * @description Error
*/
export type DeleteApiV1CheckoutSessionsByIdError = ErrorModel;

export type DeleteApiV1CheckoutSessionsByIdMutationResponse = DeleteApiV1CheckoutSessionsById200;

export type DeleteApiV1CheckoutSessionsByIdMutation = {
    Response: DeleteApiV1CheckoutSessionsById200;
    PathParams: DeleteApiV1CheckoutSessionsByIdPathParams;
    Errors: any;
};