/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteTagPostResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description ID of the deleted tagpost
     * @type string
    */
    id: string;
};