/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DeleteStripeCustomerResponse } from "./DeleteStripeCustomerResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type DeleteApiV1StripeCustomersByIdPathParams = {
  /**
   * @description ID of the user on stripe
   * @maxLength 36
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type DeleteApiV1StripeCustomersById200 = DeleteStripeCustomerResponse;

/**
 * @description Error
 */
export type DeleteApiV1StripeCustomersByIdError = ErrorModel;

export type DeleteApiV1StripeCustomersByIdMutationResponse =
  DeleteApiV1StripeCustomersById200;

export type DeleteApiV1StripeCustomersByIdMutation = {
  Response: DeleteApiV1StripeCustomersById200;
  PathParams: DeleteApiV1StripeCustomersByIdPathParams;
  Errors: any;
};
