/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetTagResponse } from "./GetTagResponse.ts";

export type GetApiV1TagNameByNamePathParams = {
  /**
   * @description Name to identify tag
   * @type string
   */
  name: string;
};

/**
 * @description OK
 */
export type GetApiV1TagNameByName200 = GetTagResponse;

/**
 * @description Error
 */
export type GetApiV1TagNameByNameError = ErrorModel;

export type GetApiV1TagNameByNameQueryResponse = GetApiV1TagNameByName200;

export type GetApiV1TagNameByNameQuery = {
  Response: GetApiV1TagNameByName200;
  PathParams: GetApiV1TagNameByNamePathParams;
  Errors: any;
};
