/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetSearchPremiumPostResponse } from "./GetSearchPremiumPostResponse.ts";

export type GetApiV1PostsPremiumSearchQueryParams = {
  /**
   * @description String to fuzzy search premium posts on
   * @type string | undefined
   */
  search_str?: string;
  /**
   * @description Cap on the number of posts to return
   * @default 20
   * @type integer | undefined, int64
   */
  limit?: number;
  /**
   * @description Number of entries to skip for pagination
   * @default 0
   * @type integer | undefined, int64
   */
  offset?: number;
};

/**
 * @description OK
 */
export type GetApiV1PostsPremiumSearch200 = GetSearchPremiumPostResponse;

/**
 * @description Error
 */
export type GetApiV1PostsPremiumSearchError = ErrorModel;

export type GetApiV1PostsPremiumSearchQueryResponse =
  GetApiV1PostsPremiumSearch200;

export type GetApiV1PostsPremiumSearchQuery = {
  Response: GetApiV1PostsPremiumSearch200;
  QueryParams: GetApiV1PostsPremiumSearchQueryParams;
  Errors: any;
};
