/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetCurrentUserIDResponse } from "./GetCurrentUserIDResponse.ts";

/**
 * @description OK
*/
export type GetApiV1UserCurrent200 = GetCurrentUserIDResponse;

/**
 * @description Error
*/
export type GetApiV1UserCurrentError = ErrorModel;

export type GetApiV1UserCurrentQueryResponse = GetApiV1UserCurrent200;

export type GetApiV1UserCurrentQuery = {
    Response: GetApiV1UserCurrent200;
    Errors: any;
};