/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetUserResponse } from "./GetUserResponse.ts";

export type GetApiV1UserUsernameByUsernamePathParams = {
  /**
   * @description Username of the user
   * @type string
   */
  username: string;
};

/**
 * @description OK
 */
export type GetApiV1UserUsernameByUsername200 = GetUserResponse;

/**
 * @description Error
 */
export type GetApiV1UserUsernameByUsernameError = ErrorModel;

export type GetApiV1UserUsernameByUsernameQueryResponse =
  GetApiV1UserUsernameByUsername200;

export type GetApiV1UserUsernameByUsernameQuery = {
  Response: GetApiV1UserUsernameByUsername200;
  PathParams: GetApiV1UserUsernameByUsernamePathParams;
  Errors: any;
};
