/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PremiumPostResponse } from "./PremiumPostResponse.ts";

export type GetAllPremiumPostsResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description List of premium posts
   * @type array,null
   */
  posts: PremiumPostResponse[] | null;
  /**
   * @description Total number of premium posts
   * @type integer, int64
   */
  total: number;
};
