/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetPostLikeResponse } from "./GetPostLikeResponse.ts";

export type GetApiV1PostLikeByIdPathParams = {
    /**
     * @description ID of the like
     * @maxLength 36
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type GetApiV1PostLikeById200 = GetPostLikeResponse;

/**
 * @description Error
*/
export type GetApiV1PostLikeByIdError = ErrorModel;

export type GetApiV1PostLikeByIdQueryResponse = GetApiV1PostLikeById200;

export type GetApiV1PostLikeByIdQuery = {
    Response: GetApiV1PostLikeById200;
    PathParams: GetApiV1PostLikeByIdPathParams;
    Errors: any;
};