/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PermissionResponse } from "./PermissionResponse.ts";

export type GetAllPermissionsResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description List of permissions
   * @type array,null
   */
  permissions: PermissionResponse[] | null;
  /**
   * @description Total number of permissions
   * @type integer, int64
   */
  total: number;
};
