/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetCommentLikeInfoResponse } from "./GetCommentLikeInfoResponse.ts";

export type GetApiV1CommentLikeByCommentIdLikesPathParams = {
    /**
     * @description Comment to get like info for
     * @type string
    */
    comment_id: string;
};

/**
 * @description OK
*/
export type GetApiV1CommentLikeByCommentIdLikes200 = GetCommentLikeInfoResponse;

/**
 * @description Error
*/
export type GetApiV1CommentLikeByCommentIdLikesError = ErrorModel;

export type GetApiV1CommentLikeByCommentIdLikesQueryResponse = GetApiV1CommentLikeByCommentIdLikes200;

export type GetApiV1CommentLikeByCommentIdLikesQuery = {
    Response: GetApiV1CommentLikeByCommentIdLikes200;
    PathParams: GetApiV1CommentLikeByCommentIdLikesPathParams;
    Errors: any;
};