/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetAllRolesResponse } from "./GetAllRolesResponse.ts";

/**
 * @description OK
 */
export type GetApiV1RoleRoles200 = GetAllRolesResponse;

/**
 * @description Error
 */
export type GetApiV1RoleRolesError = ErrorModel;

export type GetApiV1RoleRolesQueryResponse = GetApiV1RoleRoles200;

export type GetApiV1RoleRolesQuery = {
  Response: GetApiV1RoleRoles200;
  Errors: any;
};
