/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetPopularPostsResponse } from "./GetPopularPostsResponse.ts";

export type GetApiV1PostsPopularQueryParams = {
  /**
   * @description Number of posts to return
   * @default 20
   * @type integer | undefined, int64
   */
  limit?: number;
  /**
   * @description Number of posts to skip
   * @default 0
   * @type integer | undefined, int64
   */
  offset?: number;
  /**
   * @description Rolling window used for rapid-engagement scoring
   * @default 72
   * @type integer | undefined, int64
   */
  window_hours?: number;
};

/**
 * @description OK
 */
export type GetApiV1PostsPopular200 = GetPopularPostsResponse;

/**
 * @description Error
 */
export type GetApiV1PostsPopularError = ErrorModel;

export type GetApiV1PostsPopularQueryResponse = GetApiV1PostsPopular200;

export type GetApiV1PostsPopularQuery = {
  Response: GetApiV1PostsPopular200;
  QueryParams: GetApiV1PostsPopularQueryParams;
  Errors: any;
};
