/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetDownloadURLResponse } from "./GetDownloadURLResponse.ts";

export type GetApiV1ContentDownloadUrlQueryParams = {
  /**
   * @description S3 object key
   * @type string
   */
  key: string;
};

/**
 * @description OK
 */
export type GetApiV1ContentDownloadUrl200 = GetDownloadURLResponse;

/**
 * @description Error
 */
export type GetApiV1ContentDownloadUrlError = ErrorModel;

export type GetApiV1ContentDownloadUrlQueryResponse =
  GetApiV1ContentDownloadUrl200;

export type GetApiV1ContentDownloadUrlQuery = {
  Response: GetApiV1ContentDownloadUrl200;
  QueryParams: GetApiV1ContentDownloadUrlQueryParams;
  Errors: any;
};
