/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetSportFollowsByUserResponse } from "./GetSportFollowsByUserResponse.ts";

export type GetApiV1UserSportByUserIdFollowsPathParams = {
  /**
   * @description ID of the user
   * @type string
   */
  user_id: string;
};

/**
 * @description OK
 */
export type GetApiV1UserSportByUserIdFollows200 = GetSportFollowsByUserResponse;

/**
 * @description Error
 */
export type GetApiV1UserSportByUserIdFollowsError = ErrorModel;

export type GetApiV1UserSportByUserIdFollowsQueryResponse =
  GetApiV1UserSportByUserIdFollows200;

export type GetApiV1UserSportByUserIdFollowsQuery = {
  Response: GetApiV1UserSportByUserIdFollows200;
  PathParams: GetApiV1UserSportByUserIdFollowsPathParams;
  Errors: any;
};
