/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetStripeCustomerByEmailResponse } from "./GetStripeCustomerByEmailResponse.ts";

export type GetApiV1StripeCustomersEmailByEmailPathParams = {
    /**
     * @description email to identify the stripe user
     * @maxLength 36
     * @type string
    */
    email: string;
};

/**
 * @description OK
*/
export type GetApiV1StripeCustomersEmailByEmail200 = GetStripeCustomerByEmailResponse;

/**
 * @description Error
*/
export type GetApiV1StripeCustomersEmailByEmailError = ErrorModel;

export type GetApiV1StripeCustomersEmailByEmailQueryResponse = GetApiV1StripeCustomersEmailByEmail200;

export type GetApiV1StripeCustomersEmailByEmailQuery = {
    Response: GetApiV1StripeCustomersEmailByEmail200;
    PathParams: GetApiV1StripeCustomersEmailByEmailPathParams;
    Errors: any;
};