/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AccessCheckResponse } from "./AccessCheckResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

/**
 * @description OK
 */
export type GetApiV1UtilityAccessCheck200 = AccessCheckResponse;

/**
 * @description Error
 */
export type GetApiV1UtilityAccessCheckError = ErrorModel;

export type GetApiV1UtilityAccessCheckQueryResponse =
  GetApiV1UtilityAccessCheck200;

export type GetApiV1UtilityAccessCheckQuery = {
  Response: GetApiV1UtilityAccessCheck200;
  Errors: any;
};
