/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetPremiumPostsByAuthorIDResponse } from "./GetPremiumPostsByAuthorIDResponse.ts";

export type GetApiV1PostsPremiumByAuthorByAuthorIdPathParams = {
  /**
   * @description Author ID to filter posts
   * @type string
   */
  author_id: string;
};

export type GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams = {
  /**
   * @description Number of posts to return
   * @default 50
   * @type integer | undefined, int64
   */
  limit?: number;
  /**
   * @description Number of posts to skip
   * @default 0
   * @type integer | undefined, int64
   */
  offset?: number;
};

/**
 * @description OK
 */
export type GetApiV1PostsPremiumByAuthorByAuthorId200 =
  GetPremiumPostsByAuthorIDResponse;

/**
 * @description Error
 */
export type GetApiV1PostsPremiumByAuthorByAuthorIdError = ErrorModel;

export type GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse =
  GetApiV1PostsPremiumByAuthorByAuthorId200;

export type GetApiV1PostsPremiumByAuthorByAuthorIdQuery = {
  Response: GetApiV1PostsPremiumByAuthorByAuthorId200;
  PathParams: GetApiV1PostsPremiumByAuthorByAuthorIdPathParams;
  QueryParams: GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams;
  Errors: any;
};
