/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetTagFollowsByUserResponse } from "./GetTagFollowsByUserResponse.ts";

export type GetApiV1UserTagByUserIdFollowsPathParams = {
  /**
   * @description ID of the user
   * @type string
   */
  user_id: string;
};

/**
 * @description OK
 */
export type GetApiV1UserTagByUserIdFollows200 = GetTagFollowsByUserResponse;

/**
 * @description Error
 */
export type GetApiV1UserTagByUserIdFollowsError = ErrorModel;

export type GetApiV1UserTagByUserIdFollowsQueryResponse =
  GetApiV1UserTagByUserIdFollows200;

export type GetApiV1UserTagByUserIdFollowsQuery = {
  Response: GetApiV1UserTagByUserIdFollows200;
  PathParams: GetApiV1UserTagByUserIdFollowsPathParams;
  Errors: any;
};
