/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AverageRatingsResponse } from "./AverageRatingsResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type GetApiV1SurveyAveragesQueryParams = {
  /**
   * @description Filter by sport ID
   * @type string | undefined
   */
  sport_id?: string;
  /**
   * @description Filter by college ID
   * @type string | undefined
   */
  college_id?: string;
};

/**
 * @description OK
 */
export type GetApiV1SurveyAverages200 = AverageRatingsResponse;

/**
 * @description Error
 */
export type GetApiV1SurveyAveragesError = ErrorModel;

export type GetApiV1SurveyAveragesQueryResponse = GetApiV1SurveyAverages200;

export type GetApiV1SurveyAveragesQuery = {
  Response: GetApiV1SurveyAverages200;
  QueryParams: GetApiV1SurveyAveragesQueryParams;
  Errors: any;
};
