/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { PermissionResponse } from "./PermissionResponse.ts";

export type GetApiV1PermissionByIdPathParams = {
  /**
   * @description ID of the permission
   * @maxLength 36
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type GetApiV1PermissionById200 = PermissionResponse;

/**
 * @description Error
 */
export type GetApiV1PermissionByIdError = ErrorModel;

export type GetApiV1PermissionByIdQueryResponse = GetApiV1PermissionById200;

export type GetApiV1PermissionByIdQuery = {
  Response: GetApiV1PermissionById200;
  PathParams: GetApiV1PermissionByIdPathParams;
  Errors: any;
};
