/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetCollegeFollowsByUserResponse } from "./GetCollegeFollowsByUserResponse.ts";

/**
 * @description OK
 */
export type GetApiV1UserCollegeFollows200 = GetCollegeFollowsByUserResponse;

/**
 * @description Error
 */
export type GetApiV1UserCollegeFollowsError = ErrorModel;

export type GetApiV1UserCollegeFollowsQueryResponse =
  GetApiV1UserCollegeFollows200;

export type GetApiV1UserCollegeFollowsQuery = {
  Response: GetApiV1UserCollegeFollows200;
  Errors: any;
};
