/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetCollegeFollowsByUserResponse } from "./GetCollegeFollowsByUserResponse.ts";

export type GetApiV1UserCollegeByUserIdFollowsPathParams = {
  /**
   * @description ID of the user
   * @type string
   */
  user_id: string;
};

/**
 * @description OK
 */
export type GetApiV1UserCollegeByUserIdFollows200 =
  GetCollegeFollowsByUserResponse;

/**
 * @description Error
 */
export type GetApiV1UserCollegeByUserIdFollowsError = ErrorModel;

export type GetApiV1UserCollegeByUserIdFollowsQueryResponse =
  GetApiV1UserCollegeByUserIdFollows200;

export type GetApiV1UserCollegeByUserIdFollowsQuery = {
  Response: GetApiV1UserCollegeByUserIdFollows200;
  PathParams: GetApiV1UserCollegeByUserIdFollowsPathParams;
  Errors: any;
};
