/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { StripePriceResponse } from "./StripePriceResponse.ts";

export type GetApiV1StripePriceByIdPathParams = {
    /**
     * @description ID of the product
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type GetApiV1StripePriceById200 = StripePriceResponse;

/**
 * @description Error
*/
export type GetApiV1StripePriceByIdError = ErrorModel;

export type GetApiV1StripePriceByIdQueryResponse = GetApiV1StripePriceById200;

export type GetApiV1StripePriceByIdQuery = {
    Response: GetApiV1StripePriceById200;
    PathParams: GetApiV1StripePriceByIdPathParams;
    Errors: any;
};