/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetAllPremiumPostsResponse } from "./GetAllPremiumPostsResponse.ts";

export type GetApiV1PostsPremiumQueryParams = {
  /**
   * @description Number of posts to return
   * @default 50
   * @type integer | undefined, int64
   */
  limit?: number;
  /**
   * @description Number of posts to skip
   * @default 0
   * @type integer | undefined, int64
   */
  offset?: number;
};

/**
 * @description OK
 */
export type GetApiV1PostsPremium200 = GetAllPremiumPostsResponse;

/**
 * @description Error
 */
export type GetApiV1PostsPremiumError = ErrorModel;

export type GetApiV1PostsPremiumQueryResponse = GetApiV1PostsPremium200;

export type GetApiV1PostsPremiumQuery = {
  Response: GetApiV1PostsPremium200;
  QueryParams: GetApiV1PostsPremiumQueryParams;
  Errors: any;
};
