/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetSportFollowsByUserResponse } from "./GetSportFollowsByUserResponse.ts";

/**
 * @description OK
 */
export type GetApiV1UserSportFollows200 = GetSportFollowsByUserResponse;

/**
 * @description Error
 */
export type GetApiV1UserSportFollowsError = ErrorModel;

export type GetApiV1UserSportFollowsQueryResponse = GetApiV1UserSportFollows200;

export type GetApiV1UserSportFollowsQuery = {
  Response: GetApiV1UserSportFollows200;
  Errors: any;
};
