/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { ListCollegesResponse } from "./ListCollegesResponse.ts";

export type GetApiV1CollegeQueryParams = {
  /**
   * @description Maximum number of colleges to return
   * @default 200
   * @type integer | undefined, int64
   */
  limit?: number;
  /**
   * @description Number of colleges to skip
   * @default 0
   * @type integer | undefined, int64
   */
  offset?: number;
};

/**
 * @description OK
 */
export type GetApiV1College200 = ListCollegesResponse;

/**
 * @description Error
 */
export type GetApiV1CollegeError = ErrorModel;

export type GetApiV1CollegeQueryResponse = GetApiV1College200;

export type GetApiV1CollegeQuery = {
  Response: GetApiV1College200;
  QueryParams: GetApiV1CollegeQueryParams;
  Errors: any;
};
