/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { GetTagPostByIDResponse } from "./GetTagPostByIDResponse.ts";

export type GetApiV1PostTagByIdPathParams = {
    /**
     * @description ID of the TagsPosts item
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type GetApiV1PostTagById200 = GetTagPostByIDResponse;

/**
 * @description Error
*/
export type GetApiV1PostTagByIdError = ErrorModel;

export type GetApiV1PostTagByIdQueryResponse = GetApiV1PostTagById200;

export type GetApiV1PostTagByIdQuery = {
    Response: GetApiV1PostTagById200;
    PathParams: GetApiV1PostTagByIdPathParams;
    Errors: any;
};