/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetCollegeResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description Academic rank of the college
     * @type integer,null, int32
    */
    academic_rank: number | null;
    /**
     * @description City of the college
     * @type string
    */
    city: string;
    /**
     * @description NCAA division (1, 2, or 3)
     * @minLength 1
     * @maxLength 3
     * @type integer, int32
    */
    division_rank: number;
    /**
     * @description ID of the college
     * @type string
    */
    id: string;
    /**
     * @description Logo of the college
     * @type string,null
    */
    logo: string | null;
    /**
     * @description Name of the college
     * @type string
    */
    name: string;
    /**
     * @description State of the college
     * @type string
    */
    state: string;
    /**
     * @description Website of the college
     * @type string
    */
    website: string;
};