/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetDownloadURLResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type string
   */
  download_url: string;
  /**
   * @type integer, int64
   */
  expires_in: number;
};
