/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetFollowingUsersByCollegeResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description ID of the College
   * @type string
   */
  college_id: string;
  /**
   * @description All users that follow this college
   * @type array,null
   */
  user_ids: string[] | null;
};
