/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostResponse } from "./PostResponse.ts";

export type GetPopularPostsResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description List of popular posts
   * @type array,null
   */
  posts: PostResponse[] | null;
  /**
   * @description Total number of posts considered
   * @type integer, int64
   */
  total: number;
};
