/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PremiumPostResponse } from "./PremiumPostResponse.ts";

export type GetSearchPremiumPostResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description Count of search results found for given search
   * @type integer, int64
   */
  count: number;
  /**
   * @description List of premium post responses found for given search
   * @type array,null
   */
  posts: PremiumPostResponse[] | null;
};
