/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SurveyResponse } from "./SurveyResponse.ts";

export type GetSurveysByUserResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description List of survey responses
   * @type array,null
   */
  surveys: SurveyResponse[] | null;
  /**
   * @description Total number of surveys submitted by this user
   * @type integer, int64
   */
  total: number;
};
