/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetStripeCustomerByEmailResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description Customer email
     * @type string
    */
    email: string;
    /**
     * @description Stripe customer ID
     * @type string
    */
    id: string;
};