/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { College } from "./College.ts";
import type { RoleResponse } from "./RoleResponse.ts";
import type { Sport } from "./Sport.ts";

export type GetUserResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description If the user has access to premium features
   * @type boolean
   */
  account_type: boolean;
  /**
   * @description The bio of a user
   * @type string | undefined
   */
  bio?: string;
  /**
   * @description The college of a user
   * @type object | undefined
   */
  college?: College;
  /**
   * @description The division of their college
   * @minLength 0
   * @type integer | undefined, int64
   */
  division?: number;
  /**
   * @description The email of a user
   * @type string
   */
  email: string;
  /**
   * @description The user\'s grad year
   * @minLength 0
   * @type integer | undefined, int64
   */
  expected_grad_year?: number;
  /**
   * @description The first name of a user
   * @type string
   */
  first_name: string;
  /**
   * @description ID of the user
   * @type string
   */
  id: string;
  /**
   * @description The last name of a user
   * @type string
   */
  last_name: string;
  /**
   * @description Roles assigned to the user
   * @type array | undefined
   */
  roles?: RoleResponse[];
  /**
   * @description The sport(s) the user is interested in
   * @type object | undefined
   */
  sport?: Sport;
  /**
   * @description The username of a user
   * @type string
   */
  username: string;
  /**
   * @description Verification status for the athlete
   * @type string
   */
  verified_athlete_status: string;
};
