/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetUploadURLResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type string
   */
  document_id: string;
  /**
   * @type integer, int64
   */
  expires_in: number;
  /**
   * @type string
   */
  key: string;
  /**
   * @type string
   */
  upload_url: string;
};
