/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type HealthResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description Message to display
     * @type string
    */
    message: string;
};