export type { CreateCollegeRequest } from "./CreateCollegeRequest.ts";
export type { CreateCollegeResponse } from "./CreateCollegeResponse.ts";
export type { CreateSportRequest } from "./CreateSportRequest.ts";
export type { CreateUserBody } from "./CreateUserBody.ts";
export type { CreateUserResponse } from "./CreateUserResponse.ts";
export type { DeleteApiV1CollegeByIdPathParams, DeleteApiV1CollegeById200, DeleteApiV1CollegeByIdError, DeleteApiV1CollegeByIdMutationResponse, DeleteApiV1CollegeByIdMutation } from "./DeleteApiV1CollegeById.ts";
export type { DeleteApiV1SportByIdPathParams, DeleteApiV1SportById200, DeleteApiV1SportByIdError, DeleteApiV1SportByIdMutationResponse, DeleteApiV1SportByIdMutation } from "./DeleteApiV1SportById.ts";
export type { DeleteApiV1UserByIdPathParams, DeleteApiV1UserById200, DeleteApiV1UserByIdError, DeleteApiV1UserByIdMutationResponse, DeleteApiV1UserByIdMutation } from "./DeleteApiV1UserById.ts";
export type { DeleteCollegeResponse } from "./DeleteCollegeResponse.ts";
export type { DeleteUserResponse } from "./DeleteUserResponse.ts";
export type { ErrorDetail } from "./ErrorDetail.ts";
export type { ErrorModel } from "./ErrorModel.ts";
export type { GetAllSportsResponse } from "./GetAllSportsResponse.ts";
export type { GetApiV1CollegeByIdPathParams, GetApiV1CollegeById200, GetApiV1CollegeByIdError, GetApiV1CollegeByIdQueryResponse, GetApiV1CollegeByIdQuery } from "./GetApiV1CollegeById.ts";
export type { GetApiV1Health200, GetApiV1HealthError, GetApiV1HealthQueryResponse, GetApiV1HealthQuery } from "./GetApiV1Health.ts";
export type { GetApiV1HealthHealthcheck200, GetApiV1HealthHealthcheckError, GetApiV1HealthHealthcheckQueryResponse, GetApiV1HealthHealthcheckQuery } from "./GetApiV1HealthHealthcheck.ts";
export type { GetApiV1SportByIdPathParams, GetApiV1SportById200, GetApiV1SportByIdError, GetApiV1SportByIdQueryResponse, GetApiV1SportByIdQuery } from "./GetApiV1SportById.ts";
export type { GetApiV1SportByNameByNamePathParams, GetApiV1SportByNameByName200, GetApiV1SportByNameByNameError, GetApiV1SportByNameByNameQueryResponse, GetApiV1SportByNameByNameQuery } from "./GetApiV1SportByNameByName.ts";
export type { GetApiV1SportsQueryParams, GetApiV1Sports200, GetApiV1SportsError, GetApiV1SportsQueryResponse, GetApiV1SportsQuery } from "./GetApiV1Sports.ts";
export type { GetApiV1UserByIdPathParams, GetApiV1UserById200, GetApiV1UserByIdError, GetApiV1UserByIdQueryResponse, GetApiV1UserByIdQuery } from "./GetApiV1UserById.ts";
export type { GetApiV1UserCurrent200, GetApiV1UserCurrentError, GetApiV1UserCurrentQueryResponse, GetApiV1UserCurrentQuery } from "./GetApiV1UserCurrent.ts";
export type { GetCollegeResponse } from "./GetCollegeResponse.ts";
export type { GetCurrentUserIDResponse } from "./GetCurrentUserIDResponse.ts";
export type { GetUserResponse } from "./GetUserResponse.ts";
export type { HealthResponse } from "./HealthResponse.ts";
export type { PatchApiV1SportByIdPathParams, PatchApiV1SportById200, PatchApiV1SportByIdError, PatchApiV1SportByIdMutationRequest, PatchApiV1SportByIdMutationResponse, PatchApiV1SportByIdMutation } from "./PatchApiV1SportById.ts";
export type { PatchApiV1UserByIdPathParams, PatchApiV1UserById200, PatchApiV1UserByIdError, PatchApiV1UserByIdMutationRequest, PatchApiV1UserByIdMutationResponse, PatchApiV1UserByIdMutation } from "./PatchApiV1UserById.ts";
export type { PostApiV1College200, PostApiV1CollegeError, PostApiV1CollegeMutationRequest, PostApiV1CollegeMutationResponse, PostApiV1CollegeMutation } from "./PostApiV1College.ts";
export type { PostApiV1Sport200, PostApiV1SportError, PostApiV1SportMutationRequest, PostApiV1SportMutationResponse, PostApiV1SportMutation } from "./PostApiV1Sport.ts";
export type { PostApiV1User200, PostApiV1UserError, PostApiV1UserMutationRequest, PostApiV1UserMutationResponse, PostApiV1UserMutation } from "./PostApiV1User.ts";
export type { PutApiV1CollegeByIdPathParams, PutApiV1CollegeById200, PutApiV1CollegeByIdError, PutApiV1CollegeByIdMutationRequest, PutApiV1CollegeByIdMutationResponse, PutApiV1CollegeByIdMutation } from "./PutApiV1CollegeById.ts";
export type { SportResponse } from "./SportResponse.ts";
export type { UpdateCollegeRequest } from "./UpdateCollegeRequest.ts";
export type { UpdateCollegeResponse } from "./UpdateCollegeResponse.ts";
export type { UpdateSportRequest } from "./UpdateSportRequest.ts";
export type { UpdateUserBody } from "./UpdateUserBody.ts";
export type { UpdateUserResponse } from "./UpdateUserResponse.ts";