/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CommentResponse } from "./CommentResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

export type ListApiV1PostByPostIdCommentsPathParams = {
    /**
     * @description ID of the post
     * @type string
    */
    post_id: string;
};

/**
 * @description OK
*/
export type ListApiV1PostByPostIdComments200 = CommentResponse[] | null;

/**
 * @description Error
*/
export type ListApiV1PostByPostIdCommentsError = ErrorModel;

export type ListApiV1PostByPostIdCommentsQueryResponse = ListApiV1PostByPostIdComments200;

export type ListApiV1PostByPostIdCommentsQuery = {
    Response: ListApiV1PostByPostIdComments200;
    PathParams: ListApiV1PostByPostIdCommentsPathParams;
    Errors: any;
};