/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MediaResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type string | undefined
   */
  id?: string;
  /**
   * @type string
   */
  media_type: string;
  /**
   * @type string
   */
  s3key: string;
  /**
   * @type string
   */
  title: string;
};
