/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorModel } from "./ErrorModel.ts";
import type { PostResponse } from "./PostResponse.ts";
import type { UpdatePostRequest } from "./UpdatePostRequest.ts";

export type PatchApiV1PostByIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description OK
 */
export type PatchApiV1PostById200 = PostResponse;

/**
 * @description Error
 */
export type PatchApiV1PostByIdError = ErrorModel;

export type PatchApiV1PostByIdMutationRequest = Omit<
  NonNullable<UpdatePostRequest>,
  "$schema"
>;

export type PatchApiV1PostByIdMutationResponse = PatchApiV1PostById200;

export type PatchApiV1PostByIdMutation = {
  Response: PatchApiV1PostById200;
  Request: PatchApiV1PostByIdMutationRequest;
  PathParams: PatchApiV1PostByIdPathParams;
  Errors: any;
};
