/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorModel } from "./ErrorModel.ts";
import type { UpdateTagBody } from "./UpdateTagBody.ts";
import type { UpdateTagResponse } from "./UpdateTagResponse.ts";

export type PatchApiV1TagByIdPathParams = {
    /**
     * @description ID of the tag to update
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type PatchApiV1TagById200 = UpdateTagResponse;

/**
 * @description Error
*/
export type PatchApiV1TagByIdError = ErrorModel;

export type PatchApiV1TagByIdMutationRequest = Omit<NonNullable<UpdateTagBody>, "$schema">;

export type PatchApiV1TagByIdMutationResponse = PatchApiV1TagById200;

export type PatchApiV1TagByIdMutation = {
    Response: PatchApiV1TagById200;
    Request: PatchApiV1TagByIdMutationRequest;
    PathParams: PatchApiV1TagByIdPathParams;
    Errors: any;
};