/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateSurveyRequest } from "./CreateSurveyRequest.ts";
import type { ErrorModel } from "./ErrorModel.ts";
import type { SurveyResponse } from "./SurveyResponse.ts";

/**
 * @description OK
 */
export type PostApiV1Survey200 = SurveyResponse;

/**
 * @description Error
 */
export type PostApiV1SurveyError = ErrorModel;

export type PostApiV1SurveyMutationRequest = Omit<
  NonNullable<CreateSurveyRequest>,
  "$schema"
>;

export type PostApiV1SurveyMutationResponse = PostApiV1Survey200;

export type PostApiV1SurveyMutation = {
  Response: PostApiV1Survey200;
  Request: PostApiV1SurveyMutationRequest;
  Errors: any;
};
