/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatePermissionRequest } from "./CreatePermissionRequest.ts";
import type { ErrorModel } from "./ErrorModel.ts";
import type { PermissionResponse } from "./PermissionResponse.ts";

/**
 * @description OK
 */
export type PostApiV1Permission200 = PermissionResponse;

/**
 * @description Error
 */
export type PostApiV1PermissionError = ErrorModel;

export type PostApiV1PermissionMutationRequest = Omit<
  NonNullable<CreatePermissionRequest>,
  "$schema"
>;

export type PostApiV1PermissionMutationResponse = PostApiV1Permission200;

export type PostApiV1PermissionMutation = {
  Response: PostApiV1Permission200;
  Request: PostApiV1PermissionMutationRequest;
  Errors: any;
};
