/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateRoleRequest } from "./CreateRoleRequest.ts";
import type { ErrorModel } from "./ErrorModel.ts";
import type { RoleResponse } from "./RoleResponse.ts";

/**
 * @description OK
*/
export type PostApiV1RoleBasic200 = RoleResponse;

/**
 * @description Error
*/
export type PostApiV1RoleBasicError = ErrorModel;

export type PostApiV1RoleBasicMutationRequest = Omit<NonNullable<CreateRoleRequest>, "$schema">;

export type PostApiV1RoleBasicMutationResponse = PostApiV1RoleBasic200;

export type PostApiV1RoleBasicMutation = {
    Response: PostApiV1RoleBasic200;
    Request: PostApiV1RoleBasicMutationRequest;
    Errors: any;
};