/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatePremiumPostParams } from "./CreatePremiumPostParams.ts";
import type { CreatePremiumPostResponse } from "./CreatePremiumPostResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

/**
 * @description OK
 */
export type PostApiV1PostPremium200 = CreatePremiumPostResponse;

/**
 * @description Error
 */
export type PostApiV1PostPremiumError = ErrorModel;

export type PostApiV1PostPremiumMutationRequest = Omit<
  NonNullable<CreatePremiumPostParams>,
  "$schema"
>;

export type PostApiV1PostPremiumMutationResponse = PostApiV1PostPremium200;

export type PostApiV1PostPremiumMutation = {
  Response: PostApiV1PostPremium200;
  Request: PostApiV1PostPremiumMutationRequest;
  Errors: any;
};
