/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCommentBody } from "./CreateCommentBody.ts";
import type { CreateCommentResponse } from "./CreateCommentResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

/**
 * @description OK
 */
export type PostApiV1Comment200 = CreateCommentResponse;

/**
 * @description Error
 */
export type PostApiV1CommentError = ErrorModel;

export type PostApiV1CommentMutationRequest = Omit<
  NonNullable<CreateCommentBody>,
  "$schema"
>;

export type PostApiV1CommentMutationResponse = PostApiV1Comment200;

export type PostApiV1CommentMutation = {
  Response: PostApiV1Comment200;
  Request: PostApiV1CommentMutationRequest;
  Errors: any;
};
