/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateSportFollowBody } from "./CreateSportFollowBody.ts";
import type { CreateSportFollowResponse } from "./CreateSportFollowResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

/**
 * @description OK
 */
export type PostApiV1UserSport200 = CreateSportFollowResponse;

/**
 * @description Error
 */
export type PostApiV1UserSportError = ErrorModel;

export type PostApiV1UserSportMutationRequest = Omit<
  NonNullable<CreateSportFollowBody>,
  "$schema"
>;

export type PostApiV1UserSportMutationResponse = PostApiV1UserSport200;

export type PostApiV1UserSportMutation = {
  Response: PostApiV1UserSport200;
  Request: PostApiV1UserSportMutationRequest;
  Errors: any;
};
