/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCommentLikeBody } from "./CreateCommentLikeBody.ts";
import type { CreateCommentLikeResponse } from "./CreateCommentLikeResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

/**
 * @description OK
 */
export type PostApiV1CommentLike200 = CreateCommentLikeResponse;

/**
 * @description Error
 */
export type PostApiV1CommentLikeError = ErrorModel;

export type PostApiV1CommentLikeMutationRequest = Omit<
  NonNullable<CreateCommentLikeBody>,
  "$schema"
>;

export type PostApiV1CommentLikeMutationResponse = PostApiV1CommentLike200;

export type PostApiV1CommentLikeMutation = {
  Response: PostApiV1CommentLike200;
  Request: PostApiV1CommentLikeMutationRequest;
  Errors: any;
};
