/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateStripePriceRequest } from "./CreateStripePriceRequest.ts";
import type { ErrorModel } from "./ErrorModel.ts";
import type { StripePriceResponse } from "./StripePriceResponse.ts";

/**
 * @description OK
*/
export type PostApiV1StripePrice200 = StripePriceResponse;

/**
 * @description Error
*/
export type PostApiV1StripePriceError = ErrorModel;

export type PostApiV1StripePriceMutationRequest = Omit<NonNullable<CreateStripePriceRequest>, "$schema">;

export type PostApiV1StripePriceMutationResponse = PostApiV1StripePrice200;

export type PostApiV1StripePriceMutation = {
    Response: PostApiV1StripePrice200;
    Request: PostApiV1StripePriceMutationRequest;
    Errors: any;
};