/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateTagBody } from "./CreateTagBody.ts";
import type { CreateTagResponse } from "./CreateTagResponse.ts";
import type { ErrorModel } from "./ErrorModel.ts";

/**
 * @description OK
 */
export type PostApiV1Tag200 = CreateTagResponse;

/**
 * @description Error
 */
export type PostApiV1TagError = ErrorModel;

export type PostApiV1TagMutationRequest = Omit<
  NonNullable<CreateTagBody>,
  "$schema"
>;

export type PostApiV1TagMutationResponse = PostApiV1Tag200;

export type PostApiV1TagMutation = {
  Response: PostApiV1Tag200;
  Request: PostApiV1TagMutationRequest;
  Errors: any;
};
