/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateRoleRequest } from "./CreateRoleRequest.ts";
import type { ErrorModel } from "./ErrorModel.ts";
import type { RoleResponse } from "./RoleResponse.ts";

/**
 * @description OK
 */
export type PostApiV1Role200 = RoleResponse;

/**
 * @description Error
 */
export type PostApiV1RoleError = ErrorModel;

export type PostApiV1RoleMutationRequest = Omit<
  NonNullable<CreateRoleRequest>,
  "$schema"
>;

export type PostApiV1RoleMutationResponse = PostApiV1Role200;

export type PostApiV1RoleMutation = {
  Response: PostApiV1Role200;
  Request: PostApiV1RoleMutationRequest;
  Errors: any;
};
