/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RegisterStripeCustomerBody = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description A description of the user
   * @type string,null
   */
  description: string | null;
  /**
   * @description The email of the user
   * @type string,null
   */
  email: string | null;
  /**
   * @description The name of the user
   * @type string,null
   */
  name: string | null;
  /**
   * @description The phone number of the user
   * @type string,null
   */
  phone: string | null;
};
