/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetCollegeResponse } from "./GetCollegeResponse.ts";

export type SearchResultsGetCollegeResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type array,null
   */
  results: GetCollegeResponse[] | null;
};
