/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetTagResponse } from "./GetTagResponse.ts";

export type SearchResultsGetTagResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type array,null
   */
  results: GetTagResponse[] | null;
};
