/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeletedAt } from "./DeletedAt.ts";

export type Sport = {
    /**
     * @type string, date-time
    */
    created_at: string;
    /**
     * @type object | undefined
    */
    deleted_at?: DeletedAt;
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type integer | undefined, int32
    */
    popularity?: number;
    /**
     * @type string, date-time
    */
    updated_at: string;
};