/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type StripePriceResponse = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @type boolean
   */
  active: boolean;
  /**
   * @type integer, int64
   */
  created: number;
  /**
   * @type string
   */
  currency: string;
  /**
   * @type string
   */
  id: string;
  /**
   * @type string
   */
  interval: string;
  /**
   * @type integer, int64
   */
  interval_count: number;
  /**
   * @type string
   */
  product_id: string;
  /**
   * @type integer, int64
   */
  unit_amount: number;
};
