/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type StripeCheckoutSessionResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @type integer, int64
    */
    created: number;
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    mode: string;
    /**
     * @type string
    */
    status: string;
    /**
     * @type string | undefined
    */
    subscription_id?: string;
    /**
     * @type string
    */
    url: string;
};