/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateCollegeRequestDivisionRankEnum = {
  "1": 1,
  "2": 2,
  "3": 3,
} as const;

export type UpdateCollegeRequestDivisionRankEnumKey =
  (typeof updateCollegeRequestDivisionRankEnum)[keyof typeof updateCollegeRequestDivisionRankEnum];

export type UpdateCollegeRequest = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description Academic rank of the college
   * @type integer,null, int32
   */
  academic_rank: number | null;
  /**
   * @description City of the college
   * @maxLength 100
   * @type string,null
   */
  city: string | null;
  /**
   * @description NCAA division (1, 2, or 3)
   * @type integer,null, int64
   */
  division_rank: UpdateCollegeRequestDivisionRankEnumKey | null;
  /**
   * @description Logo of the college
   * @maxLength 500
   * @type string,null
   */
  logo: string | null;
  /**
   * @description Name of the college
   * @maxLength 200
   * @type string,null
   */
  name: string | null;
  /**
   * @description State of the college
   * @maxLength 100
   * @type string,null
   */
  state: string | null;
  /**
   * @description Website of the college
   * @maxLength 500
   * @type string,null
   */
  website: string | null;
};
