/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateTagPostBody = {
  /**
   * @description A URL to the JSON Schema for this object.
   * @type string | undefined, uri
   */
  readonly $schema?: string;
  /**
   * @description the postable id to update to
   * @type string
   */
  postable_id: string;
  /**
   * @description Type: post or premium_post
   * @type string
   */
  postable_type: string;
  /**
   * @description the tag id to update to
   * @type string
   */
  tag_id: string;
};
