/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateTagPostResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description ID of the tagpost updated
     * @type string
    */
    id: string;
    /**
     * @description the updated post id
     * @type string
    */
    post_id: string;
    /**
     * @description the updated tag id
     * @type string
    */
    tag_id: string;
};