/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateUserBody = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description If the user has access to premium features
     * @type boolean | undefined
    */
    account_type?: boolean;
    /**
     * @description The bio of a user
     * @type string | undefined
    */
    bio?: string;
    /**
     * @description The college of a user
     * @type string | undefined
    */
    college?: string;
    /**
     * @description The division of their college
     * @minLength 0
     * @type integer | undefined, int64
    */
    division?: number;
    /**
     * @description The email of a user
     * @type string | undefined
    */
    email?: string;
    /**
     * @description The user\'s grad year
     * @minLength 0
     * @type integer | undefined, int64
    */
    expected_grad_year?: number;
    /**
     * @description The first name of a user
     * @type string | undefined
    */
    first_name?: string;
    /**
     * @description The last name of a user
     * @type string | undefined
    */
    last_name?: string;
    /**
     * @description The sport(s) the user is interested in
     * @type array | undefined
    */
    sport?: string[];
    /**
     * @description The username of a user
     * @type string | undefined
    */
    username?: string;
    /**
     * @description Verification status for the athlete
     * @type string | undefined
    */
    verified_athlete_status?: string;
};