/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateTagResponse = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description ID of the tag updated
     * @type string
    */
    id: string;
    /**
     * @description The updated name of the tag
     * @type string
    */
    name: string;
};