/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateSportRequest = {
    /**
     * @description A URL to the JSON Schema for this object.
     * @type string | undefined, uri
    */
    readonly $schema?: string;
    /**
     * @description Name of the sport
     * @type string,null
    */
    name: string | null;
    /**
     * @description Number of players
     * @type integer,null, int32
    */
    popularity: number | null;
};