/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type User = {
  /**
   * @description If the user has access to premium features
   * @type boolean
   */
  account_type: boolean;
  /**
   * @description The name of a user
   * @type string,null
   */
  bio: string | null;
  /**
   * @description The college of a user
   * @type string
   */
  college: string;
  /**
   * @type string, date-time
   */
  created_at: string;
  /**
   * @type string,null, date-time
   */
  deleted_at: string | null;
  /**
   * @description The divison of their college
   * @minLength 0
   * @type integer,null, int64
   */
  division: number | null;
  /**
   * @description The email of a user
   * @type string
   */
  email: string;
  /**
   * @description The user\'s grad year
   * @minLength 0
   * @type integer, int64
   */
  expected_grad_year: number;
  /**
   * @description The first name of a user
   * @type string
   */
  first_name: string;
  /**
   * @type string
   */
  id: string;
  /**
   * @description The last name of a user
   * @type string
   */
  last_name: string;
  /**
   * @description The sport the user plays
   * @type string
   */
  sport: string;
  /**
   * @type string, date-time
   */
  updated_at: string;
  /**
   * @description The username of a user
   * @type string
   */
  username: string;
  /**
   * @type string
   */
  verified_athelete_status: string;
};
