export type { DeleteApiV1CheckoutSessionsByIdMutationKey } from "./useDeleteApiV1CheckoutSessionsById.ts";
export type { DeleteApiV1CollegeByIdMutationKey } from "./useDeleteApiV1CollegeById.ts";
export type { DeleteApiV1CommentByIdMutationKey } from "./useDeleteApiV1CommentById.ts";
export type { DeleteApiV1CommentLikeByIdMutationKey } from "./useDeleteApiV1CommentLikeById.ts";
export type { DeleteApiV1ContentMutationKey } from "./useDeleteApiV1Content.ts";
export type { DeleteApiV1PermissionByIdMutationKey } from "./useDeleteApiV1PermissionById.ts";
export type { DeleteApiV1PostByIdMutationKey } from "./useDeleteApiV1PostById.ts";
export type { DeleteApiV1PostLikeByIdMutationKey } from "./useDeleteApiV1PostLikeById.ts";
export type { DeleteApiV1PostTagByIdMutationKey } from "./useDeleteApiV1PostTagById.ts";
export type { DeleteApiV1RoleByIdMutationKey } from "./useDeleteApiV1RoleById.ts";
export type { DeleteApiV1SportByIdMutationKey } from "./useDeleteApiV1SportById.ts";
export type { DeleteApiV1StripeCustomersByIdMutationKey } from "./useDeleteApiV1StripeCustomersById.ts";
export type { DeleteApiV1StripePriceByIdMutationKey } from "./useDeleteApiV1StripePriceById.ts";
export type { DeleteApiV1StripeProductByIdMutationKey } from "./useDeleteApiV1StripeProductById.ts";
export type { DeleteApiV1TagByIdMutationKey } from "./useDeleteApiV1TagById.ts";
export type { DeleteApiV1UserByIdMutationKey } from "./useDeleteApiV1UserById.ts";
export type { GetApiV1CheckoutSessionsByIdQueryKey } from "./useGetApiV1CheckoutSessionsById.ts";
export type { GetApiV1CheckoutSessionsByIdSuspenseQueryKey } from "./useGetApiV1CheckoutSessionsByIdSuspense.ts";
export type { GetApiV1CollegeByIdQueryKey } from "./useGetApiV1CollegeById.ts";
export type { GetApiV1CollegeByIdSuspenseQueryKey } from "./useGetApiV1CollegeByIdSuspense.ts";
export type { GetApiV1CollegesQueryKey } from "./useGetApiV1Colleges.ts";
export type { GetApiV1CollegesSuspenseQueryKey } from "./useGetApiV1CollegesSuspense.ts";
export type { GetApiV1CommentByIdQueryKey } from "./useGetApiV1CommentById.ts";
export type { GetApiV1CommentByIdSuspenseQueryKey } from "./useGetApiV1CommentByIdSuspense.ts";
export type { GetApiV1CommentLikeByCommentIdLikesQueryKey } from "./useGetApiV1CommentLikeByCommentIdLikes.ts";
export type { GetApiV1CommentLikeByCommentIdLikesSuspenseQueryKey } from "./useGetApiV1CommentLikeByCommentIdLikesSuspense.ts";
export type { GetApiV1CommentLikeByIdQueryKey } from "./useGetApiV1CommentLikeById.ts";
export type { GetApiV1CommentLikeByIdSuspenseQueryKey } from "./useGetApiV1CommentLikeByIdSuspense.ts";
export type { GetApiV1ContentDownloadUrlQueryKey } from "./useGetApiV1ContentDownloadUrl.ts";
export type { GetApiV1ContentDownloadUrlSuspenseQueryKey } from "./useGetApiV1ContentDownloadUrlSuspense.ts";
export type { GetApiV1HealthQueryKey } from "./useGetApiV1Health.ts";
export type { GetApiV1HealthHealthcheckQueryKey } from "./useGetApiV1HealthHealthcheck.ts";
export type { GetApiV1HealthHealthcheckSuspenseQueryKey } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export type { GetApiV1HealthSuspenseQueryKey } from "./useGetApiV1HealthSuspense.ts";
export type { GetApiV1PermissionByIdQueryKey } from "./useGetApiV1PermissionById.ts";
export type { GetApiV1PermissionByIdSuspenseQueryKey } from "./useGetApiV1PermissionByIdSuspense.ts";
export type { GetApiV1PermissionsQueryKey } from "./useGetApiV1Permissions.ts";
export type { GetApiV1PermissionsSuspenseQueryKey } from "./useGetApiV1PermissionsSuspense.ts";
export type { GetApiV1PostByIdQueryKey } from "./useGetApiV1PostById.ts";
export type { GetApiV1PostByIdSuspenseQueryKey } from "./useGetApiV1PostByIdSuspense.ts";
export type { GetApiV1PostLikeByIdQueryKey } from "./useGetApiV1PostLikeById.ts";
export type { GetApiV1PostLikeByIdSuspenseQueryKey } from "./useGetApiV1PostLikeByIdSuspense.ts";
export type { GetApiV1PostLikeByPostIdLikesQueryKey } from "./useGetApiV1PostLikeByPostIdLikes.ts";
export type { GetApiV1PostLikeByPostIdLikesSuspenseQueryKey } from "./useGetApiV1PostLikeByPostIdLikesSuspense.ts";
export type { GetApiV1PostsQueryKey } from "./useGetApiV1Posts.ts";
export type { GetApiV1PostsByAuthorByAuthorIdQueryKey } from "./useGetApiV1PostsByAuthorByAuthorId.ts";
export type { GetApiV1PostsByAuthorByAuthorIdSuspenseQueryKey } from "./useGetApiV1PostsByAuthorByAuthorIdSuspense.ts";
export type { GetApiV1PostsBySportBySportIdQueryKey } from "./useGetApiV1PostsBySportBySportId.ts";
export type { GetApiV1PostsBySportBySportIdSuspenseQueryKey } from "./useGetApiV1PostsBySportBySportIdSuspense.ts";
export type { GetApiV1PostsSuspenseQueryKey } from "./useGetApiV1PostsSuspense.ts";
export type { GetApiV1PostTagByIdQueryKey } from "./useGetApiV1PostTagById.ts";
export type { GetApiV1PostTagByIdSuspenseQueryKey } from "./useGetApiV1PostTagByIdSuspense.ts";
export type { GetApiV1RoleByIdQueryKey } from "./useGetApiV1RoleById.ts";
export type { GetApiV1RoleByIdSuspenseQueryKey } from "./useGetApiV1RoleByIdSuspense.ts";
export type { GetApiV1RolesQueryKey } from "./useGetApiV1Roles.ts";
export type { GetApiV1RolesSuspenseQueryKey } from "./useGetApiV1RolesSuspense.ts";
export type { GetApiV1SportByIdQueryKey } from "./useGetApiV1SportById.ts";
export type { GetApiV1SportByIdSuspenseQueryKey } from "./useGetApiV1SportByIdSuspense.ts";
export type { GetApiV1SportByNameByNameQueryKey } from "./useGetApiV1SportByNameByName.ts";
export type { GetApiV1SportByNameByNameSuspenseQueryKey } from "./useGetApiV1SportByNameByNameSuspense.ts";
export type { GetApiV1SportsQueryKey } from "./useGetApiV1Sports.ts";
export type { GetApiV1SportsSuspenseQueryKey } from "./useGetApiV1SportsSuspense.ts";
export type { GetApiV1StripeCustomersByIdQueryKey } from "./useGetApiV1StripeCustomersById.ts";
export type { GetApiV1StripeCustomersByIdSuspenseQueryKey } from "./useGetApiV1StripeCustomersByIdSuspense.ts";
export type { GetApiV1StripeCustomersEmailByEmailQueryKey } from "./useGetApiV1StripeCustomersEmailByEmail.ts";
export type { GetApiV1StripeCustomersEmailByEmailSuspenseQueryKey } from "./useGetApiV1StripeCustomersEmailByEmailSuspense.ts";
export type { GetApiV1StripePriceByIdQueryKey } from "./useGetApiV1StripePriceById.ts";
export type { GetApiV1StripePriceByIdSuspenseQueryKey } from "./useGetApiV1StripePriceByIdSuspense.ts";
export type { GetApiV1StripeProductByIdQueryKey } from "./useGetApiV1StripeProductById.ts";
export type { GetApiV1StripeProductByIdSuspenseQueryKey } from "./useGetApiV1StripeProductByIdSuspense.ts";
export type { GetApiV1TagByIdQueryKey } from "./useGetApiV1TagById.ts";
export type { GetApiV1TagByIdSuspenseQueryKey } from "./useGetApiV1TagByIdSuspense.ts";
export type { GetApiV1TagByTagIdPostsQueryKey } from "./useGetApiV1TagByTagIdPosts.ts";
export type { GetApiV1TagByTagIdPostsSuspenseQueryKey } from "./useGetApiV1TagByTagIdPostsSuspense.ts";
export type { GetApiV1TagNameByNameQueryKey } from "./useGetApiV1TagNameByName.ts";
export type { GetApiV1TagNameByNameSuspenseQueryKey } from "./useGetApiV1TagNameByNameSuspense.ts";
export type { GetApiV1UserByIdQueryKey } from "./useGetApiV1UserById.ts";
export type { GetApiV1UserByIdSuspenseQueryKey } from "./useGetApiV1UserByIdSuspense.ts";
export type { GetApiV1UserCurrentQueryKey } from "./useGetApiV1UserCurrent.ts";
export type { GetApiV1UserCurrentSuspenseQueryKey } from "./useGetApiV1UserCurrentSuspense.ts";
export type { ListApiV1CheckoutSessionsQueryKey } from "./useListApiV1CheckoutSessions.ts";
export type { ListApiV1CheckoutSessionsSuspenseQueryKey } from "./useListApiV1CheckoutSessionsSuspense.ts";
export type { ListApiV1CommentByIdRepliesQueryKey } from "./useListApiV1CommentByIdReplies.ts";
export type { ListApiV1CommentByIdRepliesSuspenseQueryKey } from "./useListApiV1CommentByIdRepliesSuspense.ts";
export type { ListApiV1PostByPostIdCommentsQueryKey } from "./useListApiV1PostByPostIdComments.ts";
export type { ListApiV1PostByPostIdCommentsSuspenseQueryKey } from "./useListApiV1PostByPostIdCommentsSuspense.ts";
export type { ListApiV1StripePricesByIdQueryKey } from "./useListApiV1StripePricesById.ts";
export type { ListApiV1StripePricesByIdSuspenseQueryKey } from "./useListApiV1StripePricesByIdSuspense.ts";
export type { ListApiV1StripeProductsQueryKey } from "./useListApiV1StripeProducts.ts";
export type { ListApiV1StripeProductsSuspenseQueryKey } from "./useListApiV1StripeProductsSuspense.ts";
export type { ListApiV1TagTypeByTypeQueryKey } from "./useListApiV1TagTypeByType.ts";
export type { ListApiV1TagTypeByTypeSuspenseQueryKey } from "./useListApiV1TagTypeByTypeSuspense.ts";
export type { PatchApiV1CommentByIdMutationKey } from "./usePatchApiV1CommentById.ts";
export type { PatchApiV1PermissionByIdMutationKey } from "./usePatchApiV1PermissionById.ts";
export type { PatchApiV1PostByIdMutationKey } from "./usePatchApiV1PostById.ts";
export type { PatchApiV1PostTagByIdMutationKey } from "./usePatchApiV1PostTagById.ts";
export type { PatchApiV1RoleByIdMutationKey } from "./usePatchApiV1RoleById.ts";
export type { PatchApiV1SportByIdMutationKey } from "./usePatchApiV1SportById.ts";
export type { PatchApiV1StripeCustomersByIdMutationKey } from "./usePatchApiV1StripeCustomersById.ts";
export type { PatchApiV1StripePriceByIdMutationKey } from "./usePatchApiV1StripePriceById.ts";
export type { PatchApiV1StripeProductByIdMutationKey } from "./usePatchApiV1StripeProductById.ts";
export type { PatchApiV1TagByIdMutationKey } from "./usePatchApiV1TagById.ts";
export type { PatchApiV1UserMutationKey } from "./usePatchApiV1User.ts";
export type { PostApiV1CheckoutSessionsMutationKey } from "./usePostApiV1CheckoutSessions.ts";
export type { PostApiV1CollegeMutationKey } from "./usePostApiV1College.ts";
export type { PostApiV1CommentMutationKey } from "./usePostApiV1Comment.ts";
export type { PostApiV1CommentLikeMutationKey } from "./usePostApiV1CommentLike.ts";
export type { PostApiV1ContentConfirmUploadMutationKey } from "./usePostApiV1ContentConfirmUpload.ts";
export type { PostApiV1ContentUploadUrlMutationKey } from "./usePostApiV1ContentUploadUrl.ts";
export type { PostApiV1PermissionMutationKey } from "./usePostApiV1Permission.ts";
export type { PostApiV1PostMutationKey } from "./usePostApiV1Post.ts";
export type { PostApiV1PostLikeMutationKey } from "./usePostApiV1PostLike.ts";
export type { PostApiV1PostTagMutationKey } from "./usePostApiV1PostTag.ts";
export type { PostApiV1RoleMutationKey } from "./usePostApiV1Role.ts";
export type { PostApiV1RoleBasicMutationKey } from "./usePostApiV1RoleBasic.ts";
export type { PostApiV1SportMutationKey } from "./usePostApiV1Sport.ts";
export type { PostApiV1StripeCustomersMutationKey } from "./usePostApiV1StripeCustomers.ts";
export type { PostApiV1StripePriceMutationKey } from "./usePostApiV1StripePrice.ts";
export type { PostApiV1StripeProductMutationKey } from "./usePostApiV1StripeProduct.ts";
export type { PostApiV1TagMutationKey } from "./usePostApiV1Tag.ts";
export type { PostApiV1UserMutationKey } from "./usePostApiV1User.ts";
export type { PostApiV1UserByIdRolesMutationKey } from "./usePostApiV1UserByIdRoles.ts";
export type { PutApiV1CollegeByIdMutationKey } from "./usePutApiV1CollegeById.ts";
export { deleteApiV1CheckoutSessionsByIdMutationKey } from "./useDeleteApiV1CheckoutSessionsById.ts";
export { deleteApiV1CheckoutSessionsByIdMutationOptions } from "./useDeleteApiV1CheckoutSessionsById.ts";
export { useDeleteApiV1CheckoutSessionsById } from "./useDeleteApiV1CheckoutSessionsById.ts";
export { deleteApiV1CollegeByIdMutationKey } from "./useDeleteApiV1CollegeById.ts";
export { deleteApiV1CollegeByIdMutationOptions } from "./useDeleteApiV1CollegeById.ts";
export { useDeleteApiV1CollegeById } from "./useDeleteApiV1CollegeById.ts";
export { deleteApiV1CommentByIdMutationKey } from "./useDeleteApiV1CommentById.ts";
export { deleteApiV1CommentByIdMutationOptions } from "./useDeleteApiV1CommentById.ts";
export { useDeleteApiV1CommentById } from "./useDeleteApiV1CommentById.ts";
export { deleteApiV1CommentLikeByIdMutationKey } from "./useDeleteApiV1CommentLikeById.ts";
export { deleteApiV1CommentLikeByIdMutationOptions } from "./useDeleteApiV1CommentLikeById.ts";
export { useDeleteApiV1CommentLikeById } from "./useDeleteApiV1CommentLikeById.ts";
export { deleteApiV1ContentMutationKey } from "./useDeleteApiV1Content.ts";
export { deleteApiV1ContentMutationOptions } from "./useDeleteApiV1Content.ts";
export { useDeleteApiV1Content } from "./useDeleteApiV1Content.ts";
export { deleteApiV1PermissionByIdMutationKey } from "./useDeleteApiV1PermissionById.ts";
export { deleteApiV1PermissionByIdMutationOptions } from "./useDeleteApiV1PermissionById.ts";
export { useDeleteApiV1PermissionById } from "./useDeleteApiV1PermissionById.ts";
export { deleteApiV1PostByIdMutationKey } from "./useDeleteApiV1PostById.ts";
export { deleteApiV1PostByIdMutationOptions } from "./useDeleteApiV1PostById.ts";
export { useDeleteApiV1PostById } from "./useDeleteApiV1PostById.ts";
export { deleteApiV1PostLikeByIdMutationKey } from "./useDeleteApiV1PostLikeById.ts";
export { deleteApiV1PostLikeByIdMutationOptions } from "./useDeleteApiV1PostLikeById.ts";
export { useDeleteApiV1PostLikeById } from "./useDeleteApiV1PostLikeById.ts";
export { deleteApiV1PostTagByIdMutationKey } from "./useDeleteApiV1PostTagById.ts";
export { deleteApiV1PostTagByIdMutationOptions } from "./useDeleteApiV1PostTagById.ts";
export { useDeleteApiV1PostTagById } from "./useDeleteApiV1PostTagById.ts";
export { deleteApiV1RoleByIdMutationKey } from "./useDeleteApiV1RoleById.ts";
export { deleteApiV1RoleByIdMutationOptions } from "./useDeleteApiV1RoleById.ts";
export { useDeleteApiV1RoleById } from "./useDeleteApiV1RoleById.ts";
export { deleteApiV1SportByIdMutationKey } from "./useDeleteApiV1SportById.ts";
export { deleteApiV1SportByIdMutationOptions } from "./useDeleteApiV1SportById.ts";
export { useDeleteApiV1SportById } from "./useDeleteApiV1SportById.ts";
export { deleteApiV1StripeCustomersByIdMutationKey } from "./useDeleteApiV1StripeCustomersById.ts";
export { deleteApiV1StripeCustomersByIdMutationOptions } from "./useDeleteApiV1StripeCustomersById.ts";
export { useDeleteApiV1StripeCustomersById } from "./useDeleteApiV1StripeCustomersById.ts";
export { deleteApiV1StripePriceByIdMutationKey } from "./useDeleteApiV1StripePriceById.ts";
export { deleteApiV1StripePriceByIdMutationOptions } from "./useDeleteApiV1StripePriceById.ts";
export { useDeleteApiV1StripePriceById } from "./useDeleteApiV1StripePriceById.ts";
export { deleteApiV1StripeProductByIdMutationKey } from "./useDeleteApiV1StripeProductById.ts";
export { deleteApiV1StripeProductByIdMutationOptions } from "./useDeleteApiV1StripeProductById.ts";
export { useDeleteApiV1StripeProductById } from "./useDeleteApiV1StripeProductById.ts";
export { deleteApiV1TagByIdMutationKey } from "./useDeleteApiV1TagById.ts";
export { deleteApiV1TagByIdMutationOptions } from "./useDeleteApiV1TagById.ts";
export { useDeleteApiV1TagById } from "./useDeleteApiV1TagById.ts";
export { deleteApiV1UserByIdMutationKey } from "./useDeleteApiV1UserById.ts";
export { deleteApiV1UserByIdMutationOptions } from "./useDeleteApiV1UserById.ts";
export { useDeleteApiV1UserById } from "./useDeleteApiV1UserById.ts";
export { getApiV1CheckoutSessionsByIdQueryKey } from "./useGetApiV1CheckoutSessionsById.ts";
export { getApiV1CheckoutSessionsByIdQueryOptions } from "./useGetApiV1CheckoutSessionsById.ts";
export { useGetApiV1CheckoutSessionsById } from "./useGetApiV1CheckoutSessionsById.ts";
export { getApiV1CheckoutSessionsByIdSuspenseQueryKey } from "./useGetApiV1CheckoutSessionsByIdSuspense.ts";
export { getApiV1CheckoutSessionsByIdSuspenseQueryOptions } from "./useGetApiV1CheckoutSessionsByIdSuspense.ts";
export { useGetApiV1CheckoutSessionsByIdSuspense } from "./useGetApiV1CheckoutSessionsByIdSuspense.ts";
export { getApiV1CollegeByIdQueryKey } from "./useGetApiV1CollegeById.ts";
export { getApiV1CollegeByIdQueryOptions } from "./useGetApiV1CollegeById.ts";
export { useGetApiV1CollegeById } from "./useGetApiV1CollegeById.ts";
export { getApiV1CollegeByIdSuspenseQueryKey } from "./useGetApiV1CollegeByIdSuspense.ts";
export { getApiV1CollegeByIdSuspenseQueryOptions } from "./useGetApiV1CollegeByIdSuspense.ts";
export { useGetApiV1CollegeByIdSuspense } from "./useGetApiV1CollegeByIdSuspense.ts";
export { getApiV1CollegesQueryKey } from "./useGetApiV1Colleges.ts";
export { getApiV1CollegesQueryOptions } from "./useGetApiV1Colleges.ts";
export { useGetApiV1Colleges } from "./useGetApiV1Colleges.ts";
export { getApiV1CollegesSuspenseQueryKey } from "./useGetApiV1CollegesSuspense.ts";
export { getApiV1CollegesSuspenseQueryOptions } from "./useGetApiV1CollegesSuspense.ts";
export { useGetApiV1CollegesSuspense } from "./useGetApiV1CollegesSuspense.ts";
export { getApiV1CommentByIdQueryKey } from "./useGetApiV1CommentById.ts";
export { getApiV1CommentByIdQueryOptions } from "./useGetApiV1CommentById.ts";
export { useGetApiV1CommentById } from "./useGetApiV1CommentById.ts";
export { getApiV1CommentByIdSuspenseQueryKey } from "./useGetApiV1CommentByIdSuspense.ts";
export { getApiV1CommentByIdSuspenseQueryOptions } from "./useGetApiV1CommentByIdSuspense.ts";
export { useGetApiV1CommentByIdSuspense } from "./useGetApiV1CommentByIdSuspense.ts";
export { getApiV1CommentLikeByCommentIdLikesQueryKey } from "./useGetApiV1CommentLikeByCommentIdLikes.ts";
export { getApiV1CommentLikeByCommentIdLikesQueryOptions } from "./useGetApiV1CommentLikeByCommentIdLikes.ts";
export { useGetApiV1CommentLikeByCommentIdLikes } from "./useGetApiV1CommentLikeByCommentIdLikes.ts";
export { getApiV1CommentLikeByCommentIdLikesSuspenseQueryKey } from "./useGetApiV1CommentLikeByCommentIdLikesSuspense.ts";
export { getApiV1CommentLikeByCommentIdLikesSuspenseQueryOptions } from "./useGetApiV1CommentLikeByCommentIdLikesSuspense.ts";
export { useGetApiV1CommentLikeByCommentIdLikesSuspense } from "./useGetApiV1CommentLikeByCommentIdLikesSuspense.ts";
export { getApiV1CommentLikeByIdQueryKey } from "./useGetApiV1CommentLikeById.ts";
export { getApiV1CommentLikeByIdQueryOptions } from "./useGetApiV1CommentLikeById.ts";
export { useGetApiV1CommentLikeById } from "./useGetApiV1CommentLikeById.ts";
export { getApiV1CommentLikeByIdSuspenseQueryKey } from "./useGetApiV1CommentLikeByIdSuspense.ts";
export { getApiV1CommentLikeByIdSuspenseQueryOptions } from "./useGetApiV1CommentLikeByIdSuspense.ts";
export { useGetApiV1CommentLikeByIdSuspense } from "./useGetApiV1CommentLikeByIdSuspense.ts";
export { getApiV1ContentDownloadUrlQueryKey } from "./useGetApiV1ContentDownloadUrl.ts";
export { getApiV1ContentDownloadUrlQueryOptions } from "./useGetApiV1ContentDownloadUrl.ts";
export { useGetApiV1ContentDownloadUrl } from "./useGetApiV1ContentDownloadUrl.ts";
export { getApiV1ContentDownloadUrlSuspenseQueryKey } from "./useGetApiV1ContentDownloadUrlSuspense.ts";
export { getApiV1ContentDownloadUrlSuspenseQueryOptions } from "./useGetApiV1ContentDownloadUrlSuspense.ts";
export { useGetApiV1ContentDownloadUrlSuspense } from "./useGetApiV1ContentDownloadUrlSuspense.ts";
export { getApiV1HealthQueryKey } from "./useGetApiV1Health.ts";
export { getApiV1HealthQueryOptions } from "./useGetApiV1Health.ts";
export { useGetApiV1Health } from "./useGetApiV1Health.ts";
export { getApiV1HealthHealthcheckQueryKey } from "./useGetApiV1HealthHealthcheck.ts";
export { getApiV1HealthHealthcheckQueryOptions } from "./useGetApiV1HealthHealthcheck.ts";
export { useGetApiV1HealthHealthcheck } from "./useGetApiV1HealthHealthcheck.ts";
export { getApiV1HealthHealthcheckSuspenseQueryKey } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export { getApiV1HealthHealthcheckSuspenseQueryOptions } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export { useGetApiV1HealthHealthcheckSuspense } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export { getApiV1HealthSuspenseQueryKey } from "./useGetApiV1HealthSuspense.ts";
export { getApiV1HealthSuspenseQueryOptions } from "./useGetApiV1HealthSuspense.ts";
export { useGetApiV1HealthSuspense } from "./useGetApiV1HealthSuspense.ts";
export { getApiV1PermissionByIdQueryKey } from "./useGetApiV1PermissionById.ts";
export { getApiV1PermissionByIdQueryOptions } from "./useGetApiV1PermissionById.ts";
export { useGetApiV1PermissionById } from "./useGetApiV1PermissionById.ts";
export { getApiV1PermissionByIdSuspenseQueryKey } from "./useGetApiV1PermissionByIdSuspense.ts";
export { getApiV1PermissionByIdSuspenseQueryOptions } from "./useGetApiV1PermissionByIdSuspense.ts";
export { useGetApiV1PermissionByIdSuspense } from "./useGetApiV1PermissionByIdSuspense.ts";
export { getApiV1PermissionsQueryKey } from "./useGetApiV1Permissions.ts";
export { getApiV1PermissionsQueryOptions } from "./useGetApiV1Permissions.ts";
export { useGetApiV1Permissions } from "./useGetApiV1Permissions.ts";
export { getApiV1PermissionsSuspenseQueryKey } from "./useGetApiV1PermissionsSuspense.ts";
export { getApiV1PermissionsSuspenseQueryOptions } from "./useGetApiV1PermissionsSuspense.ts";
export { useGetApiV1PermissionsSuspense } from "./useGetApiV1PermissionsSuspense.ts";
export { getApiV1PostByIdQueryKey } from "./useGetApiV1PostById.ts";
export { getApiV1PostByIdQueryOptions } from "./useGetApiV1PostById.ts";
export { useGetApiV1PostById } from "./useGetApiV1PostById.ts";
export { getApiV1PostByIdSuspenseQueryKey } from "./useGetApiV1PostByIdSuspense.ts";
export { getApiV1PostByIdSuspenseQueryOptions } from "./useGetApiV1PostByIdSuspense.ts";
export { useGetApiV1PostByIdSuspense } from "./useGetApiV1PostByIdSuspense.ts";
export { getApiV1PostLikeByIdQueryKey } from "./useGetApiV1PostLikeById.ts";
export { getApiV1PostLikeByIdQueryOptions } from "./useGetApiV1PostLikeById.ts";
export { useGetApiV1PostLikeById } from "./useGetApiV1PostLikeById.ts";
export { getApiV1PostLikeByIdSuspenseQueryKey } from "./useGetApiV1PostLikeByIdSuspense.ts";
export { getApiV1PostLikeByIdSuspenseQueryOptions } from "./useGetApiV1PostLikeByIdSuspense.ts";
export { useGetApiV1PostLikeByIdSuspense } from "./useGetApiV1PostLikeByIdSuspense.ts";
export { getApiV1PostLikeByPostIdLikesQueryKey } from "./useGetApiV1PostLikeByPostIdLikes.ts";
export { getApiV1PostLikeByPostIdLikesQueryOptions } from "./useGetApiV1PostLikeByPostIdLikes.ts";
export { useGetApiV1PostLikeByPostIdLikes } from "./useGetApiV1PostLikeByPostIdLikes.ts";
export { getApiV1PostLikeByPostIdLikesSuspenseQueryKey } from "./useGetApiV1PostLikeByPostIdLikesSuspense.ts";
export { getApiV1PostLikeByPostIdLikesSuspenseQueryOptions } from "./useGetApiV1PostLikeByPostIdLikesSuspense.ts";
export { useGetApiV1PostLikeByPostIdLikesSuspense } from "./useGetApiV1PostLikeByPostIdLikesSuspense.ts";
export { getApiV1PostsQueryKey } from "./useGetApiV1Posts.ts";
export { getApiV1PostsQueryOptions } from "./useGetApiV1Posts.ts";
export { useGetApiV1Posts } from "./useGetApiV1Posts.ts";
export { getApiV1PostsByAuthorByAuthorIdQueryKey } from "./useGetApiV1PostsByAuthorByAuthorId.ts";
export { getApiV1PostsByAuthorByAuthorIdQueryOptions } from "./useGetApiV1PostsByAuthorByAuthorId.ts";
export { useGetApiV1PostsByAuthorByAuthorId } from "./useGetApiV1PostsByAuthorByAuthorId.ts";
export { getApiV1PostsByAuthorByAuthorIdSuspenseQueryKey } from "./useGetApiV1PostsByAuthorByAuthorIdSuspense.ts";
export { getApiV1PostsByAuthorByAuthorIdSuspenseQueryOptions } from "./useGetApiV1PostsByAuthorByAuthorIdSuspense.ts";
export { useGetApiV1PostsByAuthorByAuthorIdSuspense } from "./useGetApiV1PostsByAuthorByAuthorIdSuspense.ts";
export { getApiV1PostsBySportBySportIdQueryKey } from "./useGetApiV1PostsBySportBySportId.ts";
export { getApiV1PostsBySportBySportIdQueryOptions } from "./useGetApiV1PostsBySportBySportId.ts";
export { useGetApiV1PostsBySportBySportId } from "./useGetApiV1PostsBySportBySportId.ts";
export { getApiV1PostsBySportBySportIdSuspenseQueryKey } from "./useGetApiV1PostsBySportBySportIdSuspense.ts";
export { getApiV1PostsBySportBySportIdSuspenseQueryOptions } from "./useGetApiV1PostsBySportBySportIdSuspense.ts";
export { useGetApiV1PostsBySportBySportIdSuspense } from "./useGetApiV1PostsBySportBySportIdSuspense.ts";
export { getApiV1PostsSuspenseQueryKey } from "./useGetApiV1PostsSuspense.ts";
export { getApiV1PostsSuspenseQueryOptions } from "./useGetApiV1PostsSuspense.ts";
export { useGetApiV1PostsSuspense } from "./useGetApiV1PostsSuspense.ts";
export { getApiV1PostTagByIdQueryKey } from "./useGetApiV1PostTagById.ts";
export { getApiV1PostTagByIdQueryOptions } from "./useGetApiV1PostTagById.ts";
export { useGetApiV1PostTagById } from "./useGetApiV1PostTagById.ts";
export { getApiV1PostTagByIdSuspenseQueryKey } from "./useGetApiV1PostTagByIdSuspense.ts";
export { getApiV1PostTagByIdSuspenseQueryOptions } from "./useGetApiV1PostTagByIdSuspense.ts";
export { useGetApiV1PostTagByIdSuspense } from "./useGetApiV1PostTagByIdSuspense.ts";
export { getApiV1RoleByIdQueryKey } from "./useGetApiV1RoleById.ts";
export { getApiV1RoleByIdQueryOptions } from "./useGetApiV1RoleById.ts";
export { useGetApiV1RoleById } from "./useGetApiV1RoleById.ts";
export { getApiV1RoleByIdSuspenseQueryKey } from "./useGetApiV1RoleByIdSuspense.ts";
export { getApiV1RoleByIdSuspenseQueryOptions } from "./useGetApiV1RoleByIdSuspense.ts";
export { useGetApiV1RoleByIdSuspense } from "./useGetApiV1RoleByIdSuspense.ts";
export { getApiV1RolesQueryKey } from "./useGetApiV1Roles.ts";
export { getApiV1RolesQueryOptions } from "./useGetApiV1Roles.ts";
export { useGetApiV1Roles } from "./useGetApiV1Roles.ts";
export { getApiV1RolesSuspenseQueryKey } from "./useGetApiV1RolesSuspense.ts";
export { getApiV1RolesSuspenseQueryOptions } from "./useGetApiV1RolesSuspense.ts";
export { useGetApiV1RolesSuspense } from "./useGetApiV1RolesSuspense.ts";
export { getApiV1SportByIdQueryKey } from "./useGetApiV1SportById.ts";
export { getApiV1SportByIdQueryOptions } from "./useGetApiV1SportById.ts";
export { useGetApiV1SportById } from "./useGetApiV1SportById.ts";
export { getApiV1SportByIdSuspenseQueryKey } from "./useGetApiV1SportByIdSuspense.ts";
export { getApiV1SportByIdSuspenseQueryOptions } from "./useGetApiV1SportByIdSuspense.ts";
export { useGetApiV1SportByIdSuspense } from "./useGetApiV1SportByIdSuspense.ts";
export { getApiV1SportByNameByNameQueryKey } from "./useGetApiV1SportByNameByName.ts";
export { getApiV1SportByNameByNameQueryOptions } from "./useGetApiV1SportByNameByName.ts";
export { useGetApiV1SportByNameByName } from "./useGetApiV1SportByNameByName.ts";
export { getApiV1SportByNameByNameSuspenseQueryKey } from "./useGetApiV1SportByNameByNameSuspense.ts";
export { getApiV1SportByNameByNameSuspenseQueryOptions } from "./useGetApiV1SportByNameByNameSuspense.ts";
export { useGetApiV1SportByNameByNameSuspense } from "./useGetApiV1SportByNameByNameSuspense.ts";
export { getApiV1SportsQueryKey } from "./useGetApiV1Sports.ts";
export { getApiV1SportsQueryOptions } from "./useGetApiV1Sports.ts";
export { useGetApiV1Sports } from "./useGetApiV1Sports.ts";
export { getApiV1SportsSuspenseQueryKey } from "./useGetApiV1SportsSuspense.ts";
export { getApiV1SportsSuspenseQueryOptions } from "./useGetApiV1SportsSuspense.ts";
export { useGetApiV1SportsSuspense } from "./useGetApiV1SportsSuspense.ts";
export { getApiV1StripeCustomersByIdQueryKey } from "./useGetApiV1StripeCustomersById.ts";
export { getApiV1StripeCustomersByIdQueryOptions } from "./useGetApiV1StripeCustomersById.ts";
export { useGetApiV1StripeCustomersById } from "./useGetApiV1StripeCustomersById.ts";
export { getApiV1StripeCustomersByIdSuspenseQueryKey } from "./useGetApiV1StripeCustomersByIdSuspense.ts";
export { getApiV1StripeCustomersByIdSuspenseQueryOptions } from "./useGetApiV1StripeCustomersByIdSuspense.ts";
export { useGetApiV1StripeCustomersByIdSuspense } from "./useGetApiV1StripeCustomersByIdSuspense.ts";
export { getApiV1StripeCustomersEmailByEmailQueryKey } from "./useGetApiV1StripeCustomersEmailByEmail.ts";
export { getApiV1StripeCustomersEmailByEmailQueryOptions } from "./useGetApiV1StripeCustomersEmailByEmail.ts";
export { useGetApiV1StripeCustomersEmailByEmail } from "./useGetApiV1StripeCustomersEmailByEmail.ts";
export { getApiV1StripeCustomersEmailByEmailSuspenseQueryKey } from "./useGetApiV1StripeCustomersEmailByEmailSuspense.ts";
export { getApiV1StripeCustomersEmailByEmailSuspenseQueryOptions } from "./useGetApiV1StripeCustomersEmailByEmailSuspense.ts";
export { useGetApiV1StripeCustomersEmailByEmailSuspense } from "./useGetApiV1StripeCustomersEmailByEmailSuspense.ts";
export { getApiV1StripePriceByIdQueryKey } from "./useGetApiV1StripePriceById.ts";
export { getApiV1StripePriceByIdQueryOptions } from "./useGetApiV1StripePriceById.ts";
export { useGetApiV1StripePriceById } from "./useGetApiV1StripePriceById.ts";
export { getApiV1StripePriceByIdSuspenseQueryKey } from "./useGetApiV1StripePriceByIdSuspense.ts";
export { getApiV1StripePriceByIdSuspenseQueryOptions } from "./useGetApiV1StripePriceByIdSuspense.ts";
export { useGetApiV1StripePriceByIdSuspense } from "./useGetApiV1StripePriceByIdSuspense.ts";
export { getApiV1StripeProductByIdQueryKey } from "./useGetApiV1StripeProductById.ts";
export { getApiV1StripeProductByIdQueryOptions } from "./useGetApiV1StripeProductById.ts";
export { useGetApiV1StripeProductById } from "./useGetApiV1StripeProductById.ts";
export { getApiV1StripeProductByIdSuspenseQueryKey } from "./useGetApiV1StripeProductByIdSuspense.ts";
export { getApiV1StripeProductByIdSuspenseQueryOptions } from "./useGetApiV1StripeProductByIdSuspense.ts";
export { useGetApiV1StripeProductByIdSuspense } from "./useGetApiV1StripeProductByIdSuspense.ts";
export { getApiV1TagByIdQueryKey } from "./useGetApiV1TagById.ts";
export { getApiV1TagByIdQueryOptions } from "./useGetApiV1TagById.ts";
export { useGetApiV1TagById } from "./useGetApiV1TagById.ts";
export { getApiV1TagByIdSuspenseQueryKey } from "./useGetApiV1TagByIdSuspense.ts";
export { getApiV1TagByIdSuspenseQueryOptions } from "./useGetApiV1TagByIdSuspense.ts";
export { useGetApiV1TagByIdSuspense } from "./useGetApiV1TagByIdSuspense.ts";
export { getApiV1TagByTagIdPostsQueryKey } from "./useGetApiV1TagByTagIdPosts.ts";
export { getApiV1TagByTagIdPostsQueryOptions } from "./useGetApiV1TagByTagIdPosts.ts";
export { useGetApiV1TagByTagIdPosts } from "./useGetApiV1TagByTagIdPosts.ts";
export { getApiV1TagByTagIdPostsSuspenseQueryKey } from "./useGetApiV1TagByTagIdPostsSuspense.ts";
export { getApiV1TagByTagIdPostsSuspenseQueryOptions } from "./useGetApiV1TagByTagIdPostsSuspense.ts";
export { useGetApiV1TagByTagIdPostsSuspense } from "./useGetApiV1TagByTagIdPostsSuspense.ts";
export { getApiV1TagNameByNameQueryKey } from "./useGetApiV1TagNameByName.ts";
export { getApiV1TagNameByNameQueryOptions } from "./useGetApiV1TagNameByName.ts";
export { useGetApiV1TagNameByName } from "./useGetApiV1TagNameByName.ts";
export { getApiV1TagNameByNameSuspenseQueryKey } from "./useGetApiV1TagNameByNameSuspense.ts";
export { getApiV1TagNameByNameSuspenseQueryOptions } from "./useGetApiV1TagNameByNameSuspense.ts";
export { useGetApiV1TagNameByNameSuspense } from "./useGetApiV1TagNameByNameSuspense.ts";
export { getApiV1UserByIdQueryKey } from "./useGetApiV1UserById.ts";
export { getApiV1UserByIdQueryOptions } from "./useGetApiV1UserById.ts";
export { useGetApiV1UserById } from "./useGetApiV1UserById.ts";
export { getApiV1UserByIdSuspenseQueryKey } from "./useGetApiV1UserByIdSuspense.ts";
export { getApiV1UserByIdSuspenseQueryOptions } from "./useGetApiV1UserByIdSuspense.ts";
export { useGetApiV1UserByIdSuspense } from "./useGetApiV1UserByIdSuspense.ts";
export { getApiV1UserCurrentQueryKey } from "./useGetApiV1UserCurrent.ts";
export { getApiV1UserCurrentQueryOptions } from "./useGetApiV1UserCurrent.ts";
export { useGetApiV1UserCurrent } from "./useGetApiV1UserCurrent.ts";
export { getApiV1UserCurrentSuspenseQueryKey } from "./useGetApiV1UserCurrentSuspense.ts";
export { getApiV1UserCurrentSuspenseQueryOptions } from "./useGetApiV1UserCurrentSuspense.ts";
export { useGetApiV1UserCurrentSuspense } from "./useGetApiV1UserCurrentSuspense.ts";
export { listApiV1CheckoutSessionsQueryKey } from "./useListApiV1CheckoutSessions.ts";
export { listApiV1CheckoutSessionsQueryOptions } from "./useListApiV1CheckoutSessions.ts";
export { useListApiV1CheckoutSessions } from "./useListApiV1CheckoutSessions.ts";
export { listApiV1CheckoutSessionsSuspenseQueryKey } from "./useListApiV1CheckoutSessionsSuspense.ts";
export { listApiV1CheckoutSessionsSuspenseQueryOptions } from "./useListApiV1CheckoutSessionsSuspense.ts";
export { useListApiV1CheckoutSessionsSuspense } from "./useListApiV1CheckoutSessionsSuspense.ts";
export { listApiV1CommentByIdRepliesQueryKey } from "./useListApiV1CommentByIdReplies.ts";
export { listApiV1CommentByIdRepliesQueryOptions } from "./useListApiV1CommentByIdReplies.ts";
export { useListApiV1CommentByIdReplies } from "./useListApiV1CommentByIdReplies.ts";
export { listApiV1CommentByIdRepliesSuspenseQueryKey } from "./useListApiV1CommentByIdRepliesSuspense.ts";
export { listApiV1CommentByIdRepliesSuspenseQueryOptions } from "./useListApiV1CommentByIdRepliesSuspense.ts";
export { useListApiV1CommentByIdRepliesSuspense } from "./useListApiV1CommentByIdRepliesSuspense.ts";
export { listApiV1PostByPostIdCommentsQueryKey } from "./useListApiV1PostByPostIdComments.ts";
export { listApiV1PostByPostIdCommentsQueryOptions } from "./useListApiV1PostByPostIdComments.ts";
export { useListApiV1PostByPostIdComments } from "./useListApiV1PostByPostIdComments.ts";
export { listApiV1PostByPostIdCommentsSuspenseQueryKey } from "./useListApiV1PostByPostIdCommentsSuspense.ts";
export { listApiV1PostByPostIdCommentsSuspenseQueryOptions } from "./useListApiV1PostByPostIdCommentsSuspense.ts";
export { useListApiV1PostByPostIdCommentsSuspense } from "./useListApiV1PostByPostIdCommentsSuspense.ts";
export { listApiV1StripePricesByIdQueryKey } from "./useListApiV1StripePricesById.ts";
export { listApiV1StripePricesByIdQueryOptions } from "./useListApiV1StripePricesById.ts";
export { useListApiV1StripePricesById } from "./useListApiV1StripePricesById.ts";
export { listApiV1StripePricesByIdSuspenseQueryKey } from "./useListApiV1StripePricesByIdSuspense.ts";
export { listApiV1StripePricesByIdSuspenseQueryOptions } from "./useListApiV1StripePricesByIdSuspense.ts";
export { useListApiV1StripePricesByIdSuspense } from "./useListApiV1StripePricesByIdSuspense.ts";
export { listApiV1StripeProductsQueryKey } from "./useListApiV1StripeProducts.ts";
export { listApiV1StripeProductsQueryOptions } from "./useListApiV1StripeProducts.ts";
export { useListApiV1StripeProducts } from "./useListApiV1StripeProducts.ts";
export { listApiV1StripeProductsSuspenseQueryKey } from "./useListApiV1StripeProductsSuspense.ts";
export { listApiV1StripeProductsSuspenseQueryOptions } from "./useListApiV1StripeProductsSuspense.ts";
export { useListApiV1StripeProductsSuspense } from "./useListApiV1StripeProductsSuspense.ts";
export { listApiV1TagTypeByTypeQueryKey } from "./useListApiV1TagTypeByType.ts";
export { listApiV1TagTypeByTypeQueryOptions } from "./useListApiV1TagTypeByType.ts";
export { useListApiV1TagTypeByType } from "./useListApiV1TagTypeByType.ts";
export { listApiV1TagTypeByTypeSuspenseQueryKey } from "./useListApiV1TagTypeByTypeSuspense.ts";
export { listApiV1TagTypeByTypeSuspenseQueryOptions } from "./useListApiV1TagTypeByTypeSuspense.ts";
export { useListApiV1TagTypeByTypeSuspense } from "./useListApiV1TagTypeByTypeSuspense.ts";
export { patchApiV1CommentByIdMutationKey } from "./usePatchApiV1CommentById.ts";
export { patchApiV1CommentByIdMutationOptions } from "./usePatchApiV1CommentById.ts";
export { usePatchApiV1CommentById } from "./usePatchApiV1CommentById.ts";
export { patchApiV1PermissionByIdMutationKey } from "./usePatchApiV1PermissionById.ts";
export { patchApiV1PermissionByIdMutationOptions } from "./usePatchApiV1PermissionById.ts";
export { usePatchApiV1PermissionById } from "./usePatchApiV1PermissionById.ts";
export { patchApiV1PostByIdMutationKey } from "./usePatchApiV1PostById.ts";
export { patchApiV1PostByIdMutationOptions } from "./usePatchApiV1PostById.ts";
export { usePatchApiV1PostById } from "./usePatchApiV1PostById.ts";
export { patchApiV1PostTagByIdMutationKey } from "./usePatchApiV1PostTagById.ts";
export { patchApiV1PostTagByIdMutationOptions } from "./usePatchApiV1PostTagById.ts";
export { usePatchApiV1PostTagById } from "./usePatchApiV1PostTagById.ts";
export { patchApiV1RoleByIdMutationKey } from "./usePatchApiV1RoleById.ts";
export { patchApiV1RoleByIdMutationOptions } from "./usePatchApiV1RoleById.ts";
export { usePatchApiV1RoleById } from "./usePatchApiV1RoleById.ts";
export { patchApiV1SportByIdMutationKey } from "./usePatchApiV1SportById.ts";
export { patchApiV1SportByIdMutationOptions } from "./usePatchApiV1SportById.ts";
export { usePatchApiV1SportById } from "./usePatchApiV1SportById.ts";
export { patchApiV1StripeCustomersByIdMutationKey } from "./usePatchApiV1StripeCustomersById.ts";
export { patchApiV1StripeCustomersByIdMutationOptions } from "./usePatchApiV1StripeCustomersById.ts";
export { usePatchApiV1StripeCustomersById } from "./usePatchApiV1StripeCustomersById.ts";
export { patchApiV1StripePriceByIdMutationKey } from "./usePatchApiV1StripePriceById.ts";
export { patchApiV1StripePriceByIdMutationOptions } from "./usePatchApiV1StripePriceById.ts";
export { usePatchApiV1StripePriceById } from "./usePatchApiV1StripePriceById.ts";
export { patchApiV1StripeProductByIdMutationKey } from "./usePatchApiV1StripeProductById.ts";
export { patchApiV1StripeProductByIdMutationOptions } from "./usePatchApiV1StripeProductById.ts";
export { usePatchApiV1StripeProductById } from "./usePatchApiV1StripeProductById.ts";
export { patchApiV1TagByIdMutationKey } from "./usePatchApiV1TagById.ts";
export { patchApiV1TagByIdMutationOptions } from "./usePatchApiV1TagById.ts";
export { usePatchApiV1TagById } from "./usePatchApiV1TagById.ts";
export { patchApiV1UserMutationKey } from "./usePatchApiV1User.ts";
export { patchApiV1UserMutationOptions } from "./usePatchApiV1User.ts";
export { usePatchApiV1User } from "./usePatchApiV1User.ts";
export { postApiV1CheckoutSessionsMutationKey } from "./usePostApiV1CheckoutSessions.ts";
export { postApiV1CheckoutSessionsMutationOptions } from "./usePostApiV1CheckoutSessions.ts";
export { usePostApiV1CheckoutSessions } from "./usePostApiV1CheckoutSessions.ts";
export { postApiV1CollegeMutationKey } from "./usePostApiV1College.ts";
export { postApiV1CollegeMutationOptions } from "./usePostApiV1College.ts";
export { usePostApiV1College } from "./usePostApiV1College.ts";
export { postApiV1CommentMutationKey } from "./usePostApiV1Comment.ts";
export { postApiV1CommentMutationOptions } from "./usePostApiV1Comment.ts";
export { usePostApiV1Comment } from "./usePostApiV1Comment.ts";
export { postApiV1CommentLikeMutationKey } from "./usePostApiV1CommentLike.ts";
export { postApiV1CommentLikeMutationOptions } from "./usePostApiV1CommentLike.ts";
export { usePostApiV1CommentLike } from "./usePostApiV1CommentLike.ts";
export { postApiV1ContentConfirmUploadMutationKey } from "./usePostApiV1ContentConfirmUpload.ts";
export { postApiV1ContentConfirmUploadMutationOptions } from "./usePostApiV1ContentConfirmUpload.ts";
export { usePostApiV1ContentConfirmUpload } from "./usePostApiV1ContentConfirmUpload.ts";
export { postApiV1ContentUploadUrlMutationKey } from "./usePostApiV1ContentUploadUrl.ts";
export { postApiV1ContentUploadUrlMutationOptions } from "./usePostApiV1ContentUploadUrl.ts";
export { usePostApiV1ContentUploadUrl } from "./usePostApiV1ContentUploadUrl.ts";
export { postApiV1PermissionMutationKey } from "./usePostApiV1Permission.ts";
export { postApiV1PermissionMutationOptions } from "./usePostApiV1Permission.ts";
export { usePostApiV1Permission } from "./usePostApiV1Permission.ts";
export { postApiV1PostMutationKey } from "./usePostApiV1Post.ts";
export { postApiV1PostMutationOptions } from "./usePostApiV1Post.ts";
export { usePostApiV1Post } from "./usePostApiV1Post.ts";
export { postApiV1PostLikeMutationKey } from "./usePostApiV1PostLike.ts";
export { postApiV1PostLikeMutationOptions } from "./usePostApiV1PostLike.ts";
export { usePostApiV1PostLike } from "./usePostApiV1PostLike.ts";
export { postApiV1PostTagMutationKey } from "./usePostApiV1PostTag.ts";
export { postApiV1PostTagMutationOptions } from "./usePostApiV1PostTag.ts";
export { usePostApiV1PostTag } from "./usePostApiV1PostTag.ts";
export { postApiV1RoleMutationKey } from "./usePostApiV1Role.ts";
export { postApiV1RoleMutationOptions } from "./usePostApiV1Role.ts";
export { usePostApiV1Role } from "./usePostApiV1Role.ts";
export { postApiV1RoleBasicMutationKey } from "./usePostApiV1RoleBasic.ts";
export { postApiV1RoleBasicMutationOptions } from "./usePostApiV1RoleBasic.ts";
export { usePostApiV1RoleBasic } from "./usePostApiV1RoleBasic.ts";
export { postApiV1SportMutationKey } from "./usePostApiV1Sport.ts";
export { postApiV1SportMutationOptions } from "./usePostApiV1Sport.ts";
export { usePostApiV1Sport } from "./usePostApiV1Sport.ts";
export { postApiV1StripeCustomersMutationKey } from "./usePostApiV1StripeCustomers.ts";
export { postApiV1StripeCustomersMutationOptions } from "./usePostApiV1StripeCustomers.ts";
export { usePostApiV1StripeCustomers } from "./usePostApiV1StripeCustomers.ts";
export { postApiV1StripePriceMutationKey } from "./usePostApiV1StripePrice.ts";
export { postApiV1StripePriceMutationOptions } from "./usePostApiV1StripePrice.ts";
export { usePostApiV1StripePrice } from "./usePostApiV1StripePrice.ts";
export { postApiV1StripeProductMutationKey } from "./usePostApiV1StripeProduct.ts";
export { postApiV1StripeProductMutationOptions } from "./usePostApiV1StripeProduct.ts";
export { usePostApiV1StripeProduct } from "./usePostApiV1StripeProduct.ts";
export { postApiV1TagMutationKey } from "./usePostApiV1Tag.ts";
export { postApiV1TagMutationOptions } from "./usePostApiV1Tag.ts";
export { usePostApiV1Tag } from "./usePostApiV1Tag.ts";
export { postApiV1UserMutationKey } from "./usePostApiV1User.ts";
export { postApiV1UserMutationOptions } from "./usePostApiV1User.ts";
export { usePostApiV1User } from "./usePostApiV1User.ts";
export { postApiV1UserByIdRolesMutationKey } from "./usePostApiV1UserByIdRoles.ts";
export { postApiV1UserByIdRolesMutationOptions } from "./usePostApiV1UserByIdRoles.ts";
export { usePostApiV1UserByIdRoles } from "./usePostApiV1UserByIdRoles.ts";
export { putApiV1CollegeByIdMutationKey } from "./usePutApiV1CollegeById.ts";
export { putApiV1CollegeByIdMutationOptions } from "./usePutApiV1CollegeById.ts";
export { usePutApiV1CollegeById } from "./usePutApiV1CollegeById.ts";
