export type { DeleteApiV1CollegeByIdMutationKey } from "./useDeleteApiV1CollegeById.ts";
export type { DeleteApiV1SportByIdMutationKey } from "./useDeleteApiV1SportById.ts";
export type { DeleteApiV1UserByIdMutationKey } from "./useDeleteApiV1UserById.ts";
export type { GetApiV1CollegeByIdQueryKey } from "./useGetApiV1CollegeById.ts";
export type { GetApiV1CollegeByIdSuspenseQueryKey } from "./useGetApiV1CollegeByIdSuspense.ts";
export type { GetApiV1HealthQueryKey } from "./useGetApiV1Health.ts";
export type { GetApiV1HealthHealthcheckQueryKey } from "./useGetApiV1HealthHealthcheck.ts";
export type { GetApiV1HealthHealthcheckSuspenseQueryKey } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export type { GetApiV1HealthSuspenseQueryKey } from "./useGetApiV1HealthSuspense.ts";
export type { GetApiV1SportByIdQueryKey } from "./useGetApiV1SportById.ts";
export type { GetApiV1SportByIdSuspenseQueryKey } from "./useGetApiV1SportByIdSuspense.ts";
export type { GetApiV1SportByNameByNameQueryKey } from "./useGetApiV1SportByNameByName.ts";
export type { GetApiV1SportByNameByNameSuspenseQueryKey } from "./useGetApiV1SportByNameByNameSuspense.ts";
export type { GetApiV1SportsQueryKey } from "./useGetApiV1Sports.ts";
export type { GetApiV1SportsSuspenseQueryKey } from "./useGetApiV1SportsSuspense.ts";
export type { GetApiV1UserByIdQueryKey } from "./useGetApiV1UserById.ts";
export type { GetApiV1UserByIdSuspenseQueryKey } from "./useGetApiV1UserByIdSuspense.ts";
export type { GetApiV1UserCurrentQueryKey } from "./useGetApiV1UserCurrent.ts";
export type { GetApiV1UserCurrentSuspenseQueryKey } from "./useGetApiV1UserCurrentSuspense.ts";
export type { PatchApiV1SportByIdMutationKey } from "./usePatchApiV1SportById.ts";
export type { PatchApiV1UserByIdMutationKey } from "./usePatchApiV1UserById.ts";
export type { PostApiV1CollegeMutationKey } from "./usePostApiV1College.ts";
export type { PostApiV1SportMutationKey } from "./usePostApiV1Sport.ts";
export type { PostApiV1UserMutationKey } from "./usePostApiV1User.ts";
export type { PutApiV1CollegeByIdMutationKey } from "./usePutApiV1CollegeById.ts";
export { deleteApiV1CollegeByIdMutationKey } from "./useDeleteApiV1CollegeById.ts";
export { deleteApiV1CollegeByIdMutationOptions } from "./useDeleteApiV1CollegeById.ts";
export { useDeleteApiV1CollegeById } from "./useDeleteApiV1CollegeById.ts";
export { deleteApiV1SportByIdMutationKey } from "./useDeleteApiV1SportById.ts";
export { deleteApiV1SportByIdMutationOptions } from "./useDeleteApiV1SportById.ts";
export { useDeleteApiV1SportById } from "./useDeleteApiV1SportById.ts";
export { deleteApiV1UserByIdMutationKey } from "./useDeleteApiV1UserById.ts";
export { deleteApiV1UserByIdMutationOptions } from "./useDeleteApiV1UserById.ts";
export { useDeleteApiV1UserById } from "./useDeleteApiV1UserById.ts";
export { getApiV1CollegeByIdQueryKey } from "./useGetApiV1CollegeById.ts";
export { getApiV1CollegeByIdQueryOptions } from "./useGetApiV1CollegeById.ts";
export { useGetApiV1CollegeById } from "./useGetApiV1CollegeById.ts";
export { getApiV1CollegeByIdSuspenseQueryKey } from "./useGetApiV1CollegeByIdSuspense.ts";
export { getApiV1CollegeByIdSuspenseQueryOptions } from "./useGetApiV1CollegeByIdSuspense.ts";
export { useGetApiV1CollegeByIdSuspense } from "./useGetApiV1CollegeByIdSuspense.ts";
export { getApiV1HealthQueryKey } from "./useGetApiV1Health.ts";
export { getApiV1HealthQueryOptions } from "./useGetApiV1Health.ts";
export { useGetApiV1Health } from "./useGetApiV1Health.ts";
export { getApiV1HealthHealthcheckQueryKey } from "./useGetApiV1HealthHealthcheck.ts";
export { getApiV1HealthHealthcheckQueryOptions } from "./useGetApiV1HealthHealthcheck.ts";
export { useGetApiV1HealthHealthcheck } from "./useGetApiV1HealthHealthcheck.ts";
export { getApiV1HealthHealthcheckSuspenseQueryKey } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export { getApiV1HealthHealthcheckSuspenseQueryOptions } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export { useGetApiV1HealthHealthcheckSuspense } from "./useGetApiV1HealthHealthcheckSuspense.ts";
export { getApiV1HealthSuspenseQueryKey } from "./useGetApiV1HealthSuspense.ts";
export { getApiV1HealthSuspenseQueryOptions } from "./useGetApiV1HealthSuspense.ts";
export { useGetApiV1HealthSuspense } from "./useGetApiV1HealthSuspense.ts";
export { getApiV1SportByIdQueryKey } from "./useGetApiV1SportById.ts";
export { getApiV1SportByIdQueryOptions } from "./useGetApiV1SportById.ts";
export { useGetApiV1SportById } from "./useGetApiV1SportById.ts";
export { getApiV1SportByIdSuspenseQueryKey } from "./useGetApiV1SportByIdSuspense.ts";
export { getApiV1SportByIdSuspenseQueryOptions } from "./useGetApiV1SportByIdSuspense.ts";
export { useGetApiV1SportByIdSuspense } from "./useGetApiV1SportByIdSuspense.ts";
export { getApiV1SportByNameByNameQueryKey } from "./useGetApiV1SportByNameByName.ts";
export { getApiV1SportByNameByNameQueryOptions } from "./useGetApiV1SportByNameByName.ts";
export { useGetApiV1SportByNameByName } from "./useGetApiV1SportByNameByName.ts";
export { getApiV1SportByNameByNameSuspenseQueryKey } from "./useGetApiV1SportByNameByNameSuspense.ts";
export { getApiV1SportByNameByNameSuspenseQueryOptions } from "./useGetApiV1SportByNameByNameSuspense.ts";
export { useGetApiV1SportByNameByNameSuspense } from "./useGetApiV1SportByNameByNameSuspense.ts";
export { getApiV1SportsQueryKey } from "./useGetApiV1Sports.ts";
export { getApiV1SportsQueryOptions } from "./useGetApiV1Sports.ts";
export { useGetApiV1Sports } from "./useGetApiV1Sports.ts";
export { getApiV1SportsSuspenseQueryKey } from "./useGetApiV1SportsSuspense.ts";
export { getApiV1SportsSuspenseQueryOptions } from "./useGetApiV1SportsSuspense.ts";
export { useGetApiV1SportsSuspense } from "./useGetApiV1SportsSuspense.ts";
export { getApiV1UserByIdQueryKey } from "./useGetApiV1UserById.ts";
export { getApiV1UserByIdQueryOptions } from "./useGetApiV1UserById.ts";
export { useGetApiV1UserById } from "./useGetApiV1UserById.ts";
export { getApiV1UserByIdSuspenseQueryKey } from "./useGetApiV1UserByIdSuspense.ts";
export { getApiV1UserByIdSuspenseQueryOptions } from "./useGetApiV1UserByIdSuspense.ts";
export { useGetApiV1UserByIdSuspense } from "./useGetApiV1UserByIdSuspense.ts";
export { getApiV1UserCurrentQueryKey } from "./useGetApiV1UserCurrent.ts";
export { getApiV1UserCurrentQueryOptions } from "./useGetApiV1UserCurrent.ts";
export { useGetApiV1UserCurrent } from "./useGetApiV1UserCurrent.ts";
export { getApiV1UserCurrentSuspenseQueryKey } from "./useGetApiV1UserCurrentSuspense.ts";
export { getApiV1UserCurrentSuspenseQueryOptions } from "./useGetApiV1UserCurrentSuspense.ts";
export { useGetApiV1UserCurrentSuspense } from "./useGetApiV1UserCurrentSuspense.ts";
export { patchApiV1SportByIdMutationKey } from "./usePatchApiV1SportById.ts";
export { patchApiV1SportByIdMutationOptions } from "./usePatchApiV1SportById.ts";
export { usePatchApiV1SportById } from "./usePatchApiV1SportById.ts";
export { patchApiV1UserByIdMutationKey } from "./usePatchApiV1UserById.ts";
export { patchApiV1UserByIdMutationOptions } from "./usePatchApiV1UserById.ts";
export { usePatchApiV1UserById } from "./usePatchApiV1UserById.ts";
export { postApiV1CollegeMutationKey } from "./usePostApiV1College.ts";
export { postApiV1CollegeMutationOptions } from "./usePostApiV1College.ts";
export { usePostApiV1College } from "./usePostApiV1College.ts";
export { postApiV1SportMutationKey } from "./usePostApiV1Sport.ts";
export { postApiV1SportMutationOptions } from "./usePostApiV1Sport.ts";
export { usePostApiV1Sport } from "./usePostApiV1Sport.ts";
export { postApiV1UserMutationKey } from "./usePostApiV1User.ts";
export { postApiV1UserMutationOptions } from "./usePostApiV1User.ts";
export { usePostApiV1User } from "./usePostApiV1User.ts";
export { putApiV1CollegeByIdMutationKey } from "./usePutApiV1CollegeById.ts";
export { putApiV1CollegeByIdMutationOptions } from "./usePutApiV1CollegeById.ts";
export { usePutApiV1CollegeById } from "./usePutApiV1CollegeById.ts";