/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1SurveyByIdMutationResponse,
  DeleteApiV1SurveyByIdPathParams,
} from "../models/DeleteApiV1SurveyById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1SurveyById } from "../clients/deleteApiV1SurveyById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1SurveyByIdMutationKey = () =>
  [{ url: "/api/v1/survey/:id" }] as const;

export type DeleteApiV1SurveyByIdMutationKey = ReturnType<
  typeof deleteApiV1SurveyByIdMutationKey
>;

export function deleteApiV1SurveyByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1SurveyByIdMutationKey();
  return mutationOptions<
    DeleteApiV1SurveyByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1SurveyByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1SurveyById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 survey by ID
 * {@link /api/v1/survey/:id}
 */
export function useDeleteApiV1SurveyById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1SurveyByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1SurveyByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1SurveyByIdMutationKey();

  const baseOptions = deleteApiV1SurveyByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1SurveyByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1SurveyByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1SurveyByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1SurveyByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1SurveyByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1SurveyByIdPathParams["id"] },
    TContext
  >;
}
