/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1RoleByIdMutationResponse, DeleteApiV1RoleByIdPathParams } from "../models/DeleteApiV1RoleById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteApiV1RoleById } from "../clients/deleteApiV1RoleById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1RoleByIdMutationKey = () => [{ url: '/api/v1/role/:id' }] as const

export type DeleteApiV1RoleByIdMutationKey = ReturnType<typeof deleteApiV1RoleByIdMutationKey>

export function deleteApiV1RoleByIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteApiV1RoleByIdMutationKey()
        return mutationOptions<DeleteApiV1RoleByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1RoleByIdPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteApiV1RoleById(id, config)
          },
        })

}

/**
 * @summary Delete API v1 role by ID
 * {@link /api/v1/role/:id}
 */
export function useDeleteApiV1RoleById<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteApiV1RoleByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1RoleByIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteApiV1RoleByIdMutationKey()

          const baseOptions = deleteApiV1RoleByIdMutationOptions(config) as UseMutationOptions<DeleteApiV1RoleByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1RoleByIdPathParams["id"]}, TContext>
          

          return useMutation<DeleteApiV1RoleByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1RoleByIdPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteApiV1RoleByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1RoleByIdPathParams["id"]}, TContext>
      
}