/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteApiV1StripePriceByIdMutationResponse,
  DeleteApiV1StripePriceByIdPathParams,
} from "../models/DeleteApiV1StripePriceById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1StripePriceById } from "../clients/deleteApiV1StripePriceById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1StripePriceByIdMutationKey = () =>
  [{ url: "/api/v1/stripe_price/:id" }] as const;

export type DeleteApiV1StripePriceByIdMutationKey = ReturnType<
  typeof deleteApiV1StripePriceByIdMutationKey
>;

export function deleteApiV1StripePriceByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1StripePriceByIdMutationKey();
  return mutationOptions<
    DeleteApiV1StripePriceByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1StripePriceByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1StripePriceById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 stripe price by ID
 * {@link /api/v1/stripe_price/:id}
 */
export function useDeleteApiV1StripePriceById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1StripePriceByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1StripePriceByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1StripePriceByIdMutationKey();

  const baseOptions = deleteApiV1StripePriceByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1StripePriceByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1StripePriceByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1StripePriceByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1StripePriceByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1StripePriceByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1StripePriceByIdPathParams["id"] },
    TContext
  >;
}
