/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  DeleteApiV1PostTagByIdMutationResponse,
  DeleteApiV1PostTagByIdPathParams,
} from "../models/DeleteApiV1PostTagById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteApiV1PostTagById } from "../clients/deleteApiV1PostTagById.ts";

export const deleteApiV1PostTagByIdMutationKey = () =>
  [{ url: "/api/v1/post/tag/:id" }] as const;

export type DeleteApiV1PostTagByIdMutationKey = ReturnType<
  typeof deleteApiV1PostTagByIdMutationKey
>;

export function deleteApiV1PostTagByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1PostTagByIdMutationKey();
  return mutationOptions<
    DeleteApiV1PostTagByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostTagByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1PostTagById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 post tag by ID
 * {@link /api/v1/post/tag/:id}
 */
export function useDeleteApiV1PostTagById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1PostTagByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1PostTagByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1PostTagByIdMutationKey();

  const baseOptions = deleteApiV1PostTagByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1PostTagByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostTagByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1PostTagByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostTagByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1PostTagByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostTagByIdPathParams["id"] },
    TContext
  >;
}
