/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteApiV1PostLikeByIdMutationResponse,
  DeleteApiV1PostLikeByIdPathParams,
} from "../models/DeleteApiV1PostLikeById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1PostLikeById } from "../clients/deleteApiV1PostLikeById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1PostLikeByIdMutationKey = () =>
  [{ url: "/api/v1/post/like/:id" }] as const;

export type DeleteApiV1PostLikeByIdMutationKey = ReturnType<
  typeof deleteApiV1PostLikeByIdMutationKey
>;

export function deleteApiV1PostLikeByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1PostLikeByIdMutationKey();
  return mutationOptions<
    DeleteApiV1PostLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostLikeByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1PostLikeById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 post like by ID
 * {@link /api/v1/post/like/:id}
 */
export function useDeleteApiV1PostLikeById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1PostLikeByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1PostLikeByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1PostLikeByIdMutationKey();

  const baseOptions = deleteApiV1PostLikeByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1PostLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostLikeByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1PostLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostLikeByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1PostLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostLikeByIdPathParams["id"] },
    TContext
  >;
}
