/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1CollegeByIdMutationResponse, DeleteApiV1CollegeByIdPathParams } from "../models/DeleteApiV1CollegeById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteApiV1CollegeById } from "../clients/deleteApiV1CollegeById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1CollegeByIdMutationKey = () => [{ url: '/api/v1/college/:id' }] as const

export type DeleteApiV1CollegeByIdMutationKey = ReturnType<typeof deleteApiV1CollegeByIdMutationKey>

export function deleteApiV1CollegeByIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteApiV1CollegeByIdMutationKey()
        return mutationOptions<DeleteApiV1CollegeByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1CollegeByIdPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteApiV1CollegeById(id, config)
          },
        })

}

/**
 * @summary Delete API v1 college by ID
 * {@link /api/v1/college/:id}
 */
export function useDeleteApiV1CollegeById<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteApiV1CollegeByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1CollegeByIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteApiV1CollegeByIdMutationKey()

          const baseOptions = deleteApiV1CollegeByIdMutationOptions(config) as UseMutationOptions<DeleteApiV1CollegeByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1CollegeByIdPathParams["id"]}, TContext>
          

          return useMutation<DeleteApiV1CollegeByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1CollegeByIdPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteApiV1CollegeByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1CollegeByIdPathParams["id"]}, TContext>
      
}