/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1UserSportByIdMutationResponse,
  DeleteApiV1UserSportByIdPathParams,
} from "../models/DeleteApiV1UserSportById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1UserSportById } from "../clients/deleteApiV1UserSportById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1UserSportByIdMutationKey = () =>
  [{ url: "/api/v1/user/sport/:id" }] as const;

export type DeleteApiV1UserSportByIdMutationKey = ReturnType<
  typeof deleteApiV1UserSportByIdMutationKey
>;

export function deleteApiV1UserSportByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1UserSportByIdMutationKey();
  return mutationOptions<
    DeleteApiV1UserSportByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserSportByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1UserSportById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 user sport by ID
 * {@link /api/v1/user/sport/:id}
 */
export function useDeleteApiV1UserSportById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1UserSportByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1UserSportByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1UserSportByIdMutationKey();

  const baseOptions = deleteApiV1UserSportByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1UserSportByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserSportByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1UserSportByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserSportByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1UserSportByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserSportByIdPathParams["id"] },
    TContext
  >;
}
