/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteApiV1UserByIdRolesMutationRequest,
  DeleteApiV1UserByIdRolesMutationResponse,
  DeleteApiV1UserByIdRolesPathParams,
} from "../models/DeleteApiV1UserByIdRoles.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1UserByIdRoles } from "../clients/deleteApiV1UserByIdRoles.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1UserByIdRolesMutationKey = () =>
  [{ url: "/api/v1/user/:id/roles" }] as const;

export type DeleteApiV1UserByIdRolesMutationKey = ReturnType<
  typeof deleteApiV1UserByIdRolesMutationKey
>;

export function deleteApiV1UserByIdRolesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<DeleteApiV1UserByIdRolesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = deleteApiV1UserByIdRolesMutationKey();
  return mutationOptions<
    DeleteApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DeleteApiV1UserByIdRolesPathParams["id"];
      data: DeleteApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return deleteApiV1UserByIdRoles(id, data, config);
    },
  });
}

/**
 * @summary Delete API v1 user by ID roles
 * {@link /api/v1/user/:id/roles}
 */
export function useDeleteApiV1UserByIdRoles<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1UserByIdRolesMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: DeleteApiV1UserByIdRolesPathParams["id"];
        data: DeleteApiV1UserByIdRolesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<DeleteApiV1UserByIdRolesMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1UserByIdRolesMutationKey();

  const baseOptions = deleteApiV1UserByIdRolesMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DeleteApiV1UserByIdRolesPathParams["id"];
      data: DeleteApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    DeleteApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DeleteApiV1UserByIdRolesPathParams["id"];
      data: DeleteApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: DeleteApiV1UserByIdRolesPathParams["id"];
      data: DeleteApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >;
}
