/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1StripeCustomersByIdMutationResponse } from "../models/DeleteApiV1StripeCustomersById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1StripeCustomersById } from "../clients/deleteApiV1StripeCustomersById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1StripeCustomersByIdMutationKey = () =>
  [{ url: "/api/v1/stripe_customers/:id" }] as const;

export type DeleteApiV1StripeCustomersByIdMutationKey = ReturnType<
  typeof deleteApiV1StripeCustomersByIdMutationKey
>;

export function deleteApiV1StripeCustomersByIdMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteApiV1StripeCustomersByIdMutationKey();
  return mutationOptions<
    DeleteApiV1StripeCustomersByIdMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return deleteApiV1StripeCustomersById(config);
    },
  });
}

/**
 * @summary Delete API v1 stripe customers by ID
 * {@link /api/v1/stripe_customers/:id}
 */
export function useDeleteApiV1StripeCustomersById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1StripeCustomersByIdMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1StripeCustomersByIdMutationKey();

  const baseOptions = deleteApiV1StripeCustomersByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1StripeCustomersByIdMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    DeleteApiV1StripeCustomersByIdMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1StripeCustomersByIdMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
