/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1SportByIdMutationResponse, DeleteApiV1SportByIdPathParams } from "../models/DeleteApiV1SportById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteApiV1SportById } from "../clients/deleteApiV1SportById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1SportByIdMutationKey = () => [{ url: '/api/v1/sport/:id' }] as const

export type DeleteApiV1SportByIdMutationKey = ReturnType<typeof deleteApiV1SportByIdMutationKey>

export function deleteApiV1SportByIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteApiV1SportByIdMutationKey()
        return mutationOptions<DeleteApiV1SportByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1SportByIdPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteApiV1SportById(id, config)
          },
        })

}

/**
 * @summary Delete API v1 sport by ID
 * {@link /api/v1/sport/:id}
 */
export function useDeleteApiV1SportById<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteApiV1SportByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1SportByIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteApiV1SportByIdMutationKey()

          const baseOptions = deleteApiV1SportByIdMutationOptions(config) as UseMutationOptions<DeleteApiV1SportByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1SportByIdPathParams["id"]}, TContext>
          

          return useMutation<DeleteApiV1SportByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1SportByIdPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteApiV1SportByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1SportByIdPathParams["id"]}, TContext>
      
}