/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteApiV1UserCollegeByIdMutationResponse,
  DeleteApiV1UserCollegeByIdPathParams,
} from "../models/DeleteApiV1UserCollegeById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1UserCollegeById } from "../clients/deleteApiV1UserCollegeById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1UserCollegeByIdMutationKey = () =>
  [{ url: "/api/v1/user/college/:id" }] as const;

export type DeleteApiV1UserCollegeByIdMutationKey = ReturnType<
  typeof deleteApiV1UserCollegeByIdMutationKey
>;

export function deleteApiV1UserCollegeByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1UserCollegeByIdMutationKey();
  return mutationOptions<
    DeleteApiV1UserCollegeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserCollegeByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1UserCollegeById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 user college by ID
 * {@link /api/v1/user/college/:id}
 */
export function useDeleteApiV1UserCollegeById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1UserCollegeByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1UserCollegeByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1UserCollegeByIdMutationKey();

  const baseOptions = deleteApiV1UserCollegeByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1UserCollegeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserCollegeByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1UserCollegeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserCollegeByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1UserCollegeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1UserCollegeByIdPathParams["id"] },
    TContext
  >;
}
