/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteApiV1PostByIdMutationResponse,
  DeleteApiV1PostByIdPathParams,
} from "../models/DeleteApiV1PostById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1PostById } from "../clients/deleteApiV1PostById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1PostByIdMutationKey = () =>
  [{ url: "/api/v1/post/:id" }] as const;

export type DeleteApiV1PostByIdMutationKey = ReturnType<
  typeof deleteApiV1PostByIdMutationKey
>;

export function deleteApiV1PostByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1PostByIdMutationKey();
  return mutationOptions<
    DeleteApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1PostById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 post by ID
 * {@link /api/v1/post/:id}
 */
export function useDeleteApiV1PostById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1PostByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1PostByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1PostByIdMutationKey();

  const baseOptions = deleteApiV1PostByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostByIdPathParams["id"] },
    TContext
  >;
}
