/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1UserByIdMutationResponse, DeleteApiV1UserByIdPathParams } from "../models/DeleteApiV1UserById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteApiV1UserById } from "../clients/deleteApiV1UserById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1UserByIdMutationKey = () => [{ url: '/api/v1/user/:id' }] as const

export type DeleteApiV1UserByIdMutationKey = ReturnType<typeof deleteApiV1UserByIdMutationKey>

export function deleteApiV1UserByIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteApiV1UserByIdMutationKey()
        return mutationOptions<DeleteApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1UserByIdPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteApiV1UserById(id, config)
          },
        })

}

/**
 * @summary Delete API v1 user by ID
 * {@link /api/v1/user/:id}
 */
export function useDeleteApiV1UserById<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1UserByIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteApiV1UserByIdMutationKey()

          const baseOptions = deleteApiV1UserByIdMutationOptions(config) as UseMutationOptions<DeleteApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1UserByIdPathParams["id"]}, TContext>
          

          return useMutation<DeleteApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1UserByIdPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: DeleteApiV1UserByIdPathParams["id"]}, TContext>
      
}