/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  DeleteApiV1CommentLikeByIdMutationResponse,
  DeleteApiV1CommentLikeByIdPathParams,
} from "../models/DeleteApiV1CommentLikeById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1CommentLikeById } from "../clients/deleteApiV1CommentLikeById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1CommentLikeByIdMutationKey = () =>
  [{ url: "/api/v1/comment/like/:id" }] as const;

export type DeleteApiV1CommentLikeByIdMutationKey = ReturnType<
  typeof deleteApiV1CommentLikeByIdMutationKey
>;

export function deleteApiV1CommentLikeByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1CommentLikeByIdMutationKey();
  return mutationOptions<
    DeleteApiV1CommentLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1CommentLikeByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1CommentLikeById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 comment like by ID
 * {@link /api/v1/comment/like/:id}
 */
export function useDeleteApiV1CommentLikeById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1CommentLikeByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1CommentLikeByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1CommentLikeByIdMutationKey();

  const baseOptions = deleteApiV1CommentLikeByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1CommentLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1CommentLikeByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1CommentLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1CommentLikeByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1CommentLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1CommentLikeByIdPathParams["id"] },
    TContext
  >;
}
