/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1PostsPremiumByIdMutationResponse,
  DeleteApiV1PostsPremiumByIdPathParams,
} from "../models/DeleteApiV1PostsPremiumById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { deleteApiV1PostsPremiumById } from "../clients/deleteApiV1PostsPremiumById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1PostsPremiumByIdMutationKey = () =>
  [{ url: "/api/v1/posts/premium/:id" }] as const;

export type DeleteApiV1PostsPremiumByIdMutationKey = ReturnType<
  typeof deleteApiV1PostsPremiumByIdMutationKey
>;

export function deleteApiV1PostsPremiumByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteApiV1PostsPremiumByIdMutationKey();
  return mutationOptions<
    DeleteApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostsPremiumByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteApiV1PostsPremiumById(id, config);
    },
  });
}

/**
 * @summary Delete API v1 posts premium by ID
 * {@link /api/v1/posts/premium/:id}
 */
export function useDeleteApiV1PostsPremiumById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1PostsPremiumByIdMutationResponse,
      ResponseErrorConfig<Error>,
      { id: DeleteApiV1PostsPremiumByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1PostsPremiumByIdMutationKey();

  const baseOptions = deleteApiV1PostsPremiumByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostsPremiumByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostsPremiumByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    { id: DeleteApiV1PostsPremiumByIdPathParams["id"] },
    TContext
  >;
}
