/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1PostLikeByPostIdLikesQueryResponse, GetApiV1PostLikeByPostIdLikesPathParams } from "../models/GetApiV1PostLikeByPostIdLikes.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApiV1PostLikeByPostIdLikes } from "../clients/getApiV1PostLikeByPostIdLikes.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostLikeByPostIdLikesQueryKey = (post_id: GetApiV1PostLikeByPostIdLikesPathParams["post_id"]) => [{ url: '/api/v1/post/like/:post_id/likes', params: {post_id:post_id} }] as const

export type GetApiV1PostLikeByPostIdLikesQueryKey = ReturnType<typeof getApiV1PostLikeByPostIdLikesQueryKey>

export function getApiV1PostLikeByPostIdLikesQueryOptions(post_id: GetApiV1PostLikeByPostIdLikesPathParams["post_id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1PostLikeByPostIdLikesQueryKey(post_id)
        return queryOptions<GetApiV1PostLikeByPostIdLikesQueryResponse, ResponseErrorConfig<Error>, GetApiV1PostLikeByPostIdLikesQueryResponse, typeof queryKey>({
         enabled: !!(post_id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1PostLikeByPostIdLikes(post_id, config)
         },
        })

}

/**
 * @summary Get API v1 post like by post ID likes
 * {@link /api/v1/post/like/:post_id/likes}
 */
export function useGetApiV1PostLikeByPostIdLikes<TData = GetApiV1PostLikeByPostIdLikesQueryResponse, TQueryData = GetApiV1PostLikeByPostIdLikesQueryResponse, TQueryKey extends QueryKey = GetApiV1PostLikeByPostIdLikesQueryKey>(post_id: GetApiV1PostLikeByPostIdLikesPathParams["post_id"], options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1PostLikeByPostIdLikesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1PostLikeByPostIdLikesQueryKey(post_id)
         

         const query = useQuery({
          ...getApiV1PostLikeByPostIdLikesQueryOptions(post_id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}