/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetApiV1PostTagByIdQueryResponse,
  GetApiV1PostTagByIdPathParams,
} from "../models/GetApiV1PostTagById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1PostTagById } from "../clients/getApiV1PostTagById.ts";

export const getApiV1PostTagByIdSuspenseQueryKey = (
  id: GetApiV1PostTagByIdPathParams["id"],
) => [{ url: "/api/v1/post/tag/:id", params: { id: id } }] as const;

export type GetApiV1PostTagByIdSuspenseQueryKey = ReturnType<
  typeof getApiV1PostTagByIdSuspenseQueryKey
>;

export function getApiV1PostTagByIdSuspenseQueryOptions(
  id: GetApiV1PostTagByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostTagByIdSuspenseQueryKey(id);
  return queryOptions<
    GetApiV1PostTagByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostTagByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1PostTagById(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 post tag by ID
 * {@link /api/v1/post/tag/:id}
 */
export function useGetApiV1PostTagByIdSuspense<
  TData = GetApiV1PostTagByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostTagByIdSuspenseQueryKey,
>(
  id: GetApiV1PostTagByIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1PostTagByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1PostTagByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getApiV1PostTagByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
