/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1SurveyAveragesQueryResponse,
  GetApiV1SurveyAveragesQueryParams,
} from "../models/GetApiV1SurveyAverages.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1SurveyAverages } from "../clients/getApiV1SurveyAverages.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1SurveyAveragesQueryKey = (
  params?: GetApiV1SurveyAveragesQueryParams,
) => [{ url: "/api/v1/survey/averages" }, ...(params ? [params] : [])] as const;

export type GetApiV1SurveyAveragesQueryKey = ReturnType<
  typeof getApiV1SurveyAveragesQueryKey
>;

export function getApiV1SurveyAveragesQueryOptions(
  params?: GetApiV1SurveyAveragesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1SurveyAveragesQueryKey(params);
  return queryOptions<
    GetApiV1SurveyAveragesQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1SurveyAveragesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1SurveyAverages(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 survey averages
 * {@link /api/v1/survey/averages}
 */
export function useGetApiV1SurveyAverages<
  TData = GetApiV1SurveyAveragesQueryResponse,
  TQueryData = GetApiV1SurveyAveragesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1SurveyAveragesQueryKey,
>(
  params?: GetApiV1SurveyAveragesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1SurveyAveragesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1SurveyAveragesQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1SurveyAveragesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
