/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1SportByIdQueryResponse, GetApiV1SportByIdPathParams } from "../models/GetApiV1SportById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getApiV1SportById } from "../clients/getApiV1SportById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1SportByIdSuspenseQueryKey = (id: GetApiV1SportByIdPathParams["id"]) => [{ url: '/api/v1/sport/:id', params: {id:id} }] as const

export type GetApiV1SportByIdSuspenseQueryKey = ReturnType<typeof getApiV1SportByIdSuspenseQueryKey>

export function getApiV1SportByIdSuspenseQueryOptions(id: GetApiV1SportByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1SportByIdSuspenseQueryKey(id)
        return queryOptions<GetApiV1SportByIdQueryResponse, ResponseErrorConfig<Error>, GetApiV1SportByIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1SportById(id, config)
         },
        })

}

/**
 * @summary Get API v1 sport by ID
 * {@link /api/v1/sport/:id}
 */
export function useGetApiV1SportByIdSuspense<TData = GetApiV1SportByIdQueryResponse, TQueryKey extends QueryKey = GetApiV1SportByIdSuspenseQueryKey>(id: GetApiV1SportByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetApiV1SportByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1SportByIdSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...getApiV1SportByIdSuspenseQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}