/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1TagsSearchQueryResponse,
  GetApiV1TagsSearchQueryParams,
} from "../models/GetApiV1TagsSearch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1TagsSearch } from "../clients/getApiV1TagsSearch.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1TagsSearchSuspenseQueryKey = (
  params: GetApiV1TagsSearchQueryParams = {},
) => [{ url: "/api/v1/tags/search" }, ...(params ? [params] : [])] as const;

export type GetApiV1TagsSearchSuspenseQueryKey = ReturnType<
  typeof getApiV1TagsSearchSuspenseQueryKey
>;

export function getApiV1TagsSearchSuspenseQueryOptions(
  params?: GetApiV1TagsSearchQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1TagsSearchSuspenseQueryKey(params);
  return queryOptions<
    GetApiV1TagsSearchQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1TagsSearchQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1TagsSearch(params, config);
    },
  });
}

/**
 * @summary Get API v1 tags search
 * {@link /api/v1/tags/search}
 */
export function useGetApiV1TagsSearchSuspense<
  TData = GetApiV1TagsSearchQueryResponse,
  TQueryKey extends QueryKey = GetApiV1TagsSearchSuspenseQueryKey,
>(
  params?: GetApiV1TagsSearchQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1TagsSearchQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1TagsSearchSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getApiV1TagsSearchSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
