/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetApiV1UserCurrentQueryResponse } from "../models/GetApiV1UserCurrent.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1UserCurrent } from "../clients/getApiV1UserCurrent.ts";

export const getApiV1UserCurrentSuspenseQueryKey = () =>
  [{ url: "/api/v1/user/current" }] as const;

export type GetApiV1UserCurrentSuspenseQueryKey = ReturnType<
  typeof getApiV1UserCurrentSuspenseQueryKey
>;

export function getApiV1UserCurrentSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1UserCurrentSuspenseQueryKey();
  return queryOptions<
    GetApiV1UserCurrentQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1UserCurrentQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1UserCurrent({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 user current
 * {@link /api/v1/user/current}
 */
export function useGetApiV1UserCurrentSuspense<
  TData = GetApiV1UserCurrentQueryResponse,
  TQueryKey extends QueryKey = GetApiV1UserCurrentSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1UserCurrentQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1UserCurrentSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getApiV1UserCurrentSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
