/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetApiV1TagNameByNameQueryResponse,
  GetApiV1TagNameByNamePathParams,
} from "../models/GetApiV1TagNameByName.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1TagNameByName } from "../clients/getApiV1TagNameByName.ts";

export const getApiV1TagNameByNameSuspenseQueryKey = (
  name: GetApiV1TagNameByNamePathParams["name"],
) => [{ url: "/api/v1/tag/name/:name", params: { name: name } }] as const;

export type GetApiV1TagNameByNameSuspenseQueryKey = ReturnType<
  typeof getApiV1TagNameByNameSuspenseQueryKey
>;

export function getApiV1TagNameByNameSuspenseQueryOptions(
  name: GetApiV1TagNameByNamePathParams["name"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1TagNameByNameSuspenseQueryKey(name);
  return queryOptions<
    GetApiV1TagNameByNameQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1TagNameByNameQueryResponse,
    typeof queryKey
  >({
    enabled: !!name,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1TagNameByName(name, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 tag name by name
 * {@link /api/v1/tag/name/:name}
 */
export function useGetApiV1TagNameByNameSuspense<
  TData = GetApiV1TagNameByNameQueryResponse,
  TQueryKey extends QueryKey = GetApiV1TagNameByNameSuspenseQueryKey,
>(
  name: GetApiV1TagNameByNamePathParams["name"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1TagNameByNameQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1TagNameByNameSuspenseQueryKey(name);

  const query = useSuspenseQuery(
    {
      ...getApiV1TagNameByNameSuspenseQueryOptions(name, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
