/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1HealthQueryResponse } from "../models/GetApiV1Health.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApiV1Health } from "../clients/getApiV1Health.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1HealthQueryKey = () => [{ url: '/api/v1/health/' }] as const

export type GetApiV1HealthQueryKey = ReturnType<typeof getApiV1HealthQueryKey>

export function getApiV1HealthQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1HealthQueryKey()
        return queryOptions<GetApiV1HealthQueryResponse, ResponseErrorConfig<Error>, GetApiV1HealthQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1Health(config)
         },
        })

}

/**
 * @summary Get API v1 health
 * {@link /api/v1/health/}
 */
export function useGetApiV1Health<TData = GetApiV1HealthQueryResponse, TQueryData = GetApiV1HealthQueryResponse, TQueryKey extends QueryKey = GetApiV1HealthQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1HealthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1HealthQueryKey()
         

         const query = useQuery({
          ...getApiV1HealthQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}