/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1CommentLikeByIdQueryResponse,
  GetApiV1CommentLikeByIdPathParams,
} from "../models/GetApiV1CommentLikeById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1CommentLikeById } from "../clients/getApiV1CommentLikeById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1CommentLikeByIdSuspenseQueryKey = (
  id: GetApiV1CommentLikeByIdPathParams["id"],
) => [{ url: "/api/v1/comment/like/:id", params: { id: id } }] as const;

export type GetApiV1CommentLikeByIdSuspenseQueryKey = ReturnType<
  typeof getApiV1CommentLikeByIdSuspenseQueryKey
>;

export function getApiV1CommentLikeByIdSuspenseQueryOptions(
  id: GetApiV1CommentLikeByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CommentLikeByIdSuspenseQueryKey(id);
  return queryOptions<
    GetApiV1CommentLikeByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CommentLikeByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1CommentLikeById(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 comment like by ID
 * {@link /api/v1/comment/like/:id}
 */
export function useGetApiV1CommentLikeByIdSuspense<
  TData = GetApiV1CommentLikeByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CommentLikeByIdSuspenseQueryKey,
>(
  id: GetApiV1CommentLikeByIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1CommentLikeByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1CommentLikeByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getApiV1CommentLikeByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
