/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1PermissionsQueryResponse,
  GetApiV1PermissionsQueryParams,
} from "../models/GetApiV1Permissions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1Permissions } from "../clients/getApiV1Permissions.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PermissionsQueryKey = (
  params?: GetApiV1PermissionsQueryParams,
) => [{ url: "/api/v1/permissions/" }, ...(params ? [params] : [])] as const;

export type GetApiV1PermissionsQueryKey = ReturnType<
  typeof getApiV1PermissionsQueryKey
>;

export function getApiV1PermissionsQueryOptions(
  params?: GetApiV1PermissionsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PermissionsQueryKey(params);
  return queryOptions<
    GetApiV1PermissionsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PermissionsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Permissions(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 permissions
 * {@link /api/v1/permissions/}
 */
export function useGetApiV1Permissions<
  TData = GetApiV1PermissionsQueryResponse,
  TQueryData = GetApiV1PermissionsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PermissionsQueryKey,
>(
  params?: GetApiV1PermissionsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PermissionsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1PermissionsQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1PermissionsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
