/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1StripeCustomersByIdQueryResponse, GetApiV1StripeCustomersByIdPathParams } from "../models/GetApiV1StripeCustomersById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApiV1StripeCustomersById } from "../clients/getApiV1StripeCustomersById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1StripeCustomersByIdQueryKey = (id: GetApiV1StripeCustomersByIdPathParams["id"]) => [{ url: '/api/v1/stripe_customers/:id', params: {id:id} }] as const

export type GetApiV1StripeCustomersByIdQueryKey = ReturnType<typeof getApiV1StripeCustomersByIdQueryKey>

export function getApiV1StripeCustomersByIdQueryOptions(id: GetApiV1StripeCustomersByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1StripeCustomersByIdQueryKey(id)
        return queryOptions<GetApiV1StripeCustomersByIdQueryResponse, ResponseErrorConfig<Error>, GetApiV1StripeCustomersByIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1StripeCustomersById(id, config)
         },
        })

}

/**
 * @summary Get API v1 stripe customers by ID
 * {@link /api/v1/stripe_customers/:id}
 */
export function useGetApiV1StripeCustomersById<TData = GetApiV1StripeCustomersByIdQueryResponse, TQueryData = GetApiV1StripeCustomersByIdQueryResponse, TQueryKey extends QueryKey = GetApiV1StripeCustomersByIdQueryKey>(id: GetApiV1StripeCustomersByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1StripeCustomersByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1StripeCustomersByIdQueryKey(id)
         

         const query = useQuery({
          ...getApiV1StripeCustomersByIdQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}