/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1SportsQueryResponse, GetApiV1SportsQueryParams } from "../models/GetApiV1Sports.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getApiV1Sports } from "../clients/getApiV1Sports.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1SportsSuspenseQueryKey = (params: GetApiV1SportsQueryParams = {}) => [{ url: '/api/v1/sports/' }, ...(params ? [params] : [])] as const

export type GetApiV1SportsSuspenseQueryKey = ReturnType<typeof getApiV1SportsSuspenseQueryKey>

export function getApiV1SportsSuspenseQueryOptions(params?: GetApiV1SportsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1SportsSuspenseQueryKey(params)
        return queryOptions<GetApiV1SportsQueryResponse, ResponseErrorConfig<Error>, GetApiV1SportsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1Sports(params, config)
         },
        })

}

/**
 * @summary Get API v1 sports
 * {@link /api/v1/sports/}
 */
export function useGetApiV1SportsSuspense<TData = GetApiV1SportsQueryResponse, TQueryKey extends QueryKey = GetApiV1SportsSuspenseQueryKey>(params?: GetApiV1SportsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetApiV1SportsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1SportsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getApiV1SportsSuspenseQueryOptions(params, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}