/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1PostsFilterQueryResponse,
  GetApiV1PostsFilterQueryParams,
} from "../models/GetApiV1PostsFilter.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsFilter } from "../clients/getApiV1PostsFilter.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostsFilterQueryKey = (
  params?: GetApiV1PostsFilterQueryParams,
) => [{ url: "/api/v1/posts/filter" }, ...(params ? [params] : [])] as const;

export type GetApiV1PostsFilterQueryKey = ReturnType<
  typeof getApiV1PostsFilterQueryKey
>;

export function getApiV1PostsFilterQueryOptions(
  params?: GetApiV1PostsFilterQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsFilterQueryKey(params);
  return queryOptions<
    GetApiV1PostsFilterQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsFilterQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1PostsFilter(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 posts filter
 * {@link /api/v1/posts/filter}
 */
export function useGetApiV1PostsFilter<
  TData = GetApiV1PostsFilterQueryResponse,
  TQueryData = GetApiV1PostsFilterQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsFilterQueryKey,
>(
  params?: GetApiV1PostsFilterQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostsFilterQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1PostsFilterQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1PostsFilterQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
