/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetApiV1CommentByIdQueryResponse,
  GetApiV1CommentByIdPathParams,
} from "../models/GetApiV1CommentById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1CommentById } from "../clients/getApiV1CommentById.ts";

export const getApiV1CommentByIdSuspenseQueryKey = (
  id: GetApiV1CommentByIdPathParams["id"],
) => [{ url: "/api/v1/comment/:id", params: { id: id } }] as const;

export type GetApiV1CommentByIdSuspenseQueryKey = ReturnType<
  typeof getApiV1CommentByIdSuspenseQueryKey
>;

export function getApiV1CommentByIdSuspenseQueryOptions(
  id: GetApiV1CommentByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CommentByIdSuspenseQueryKey(id);
  return queryOptions<
    GetApiV1CommentByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CommentByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1CommentById(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 comment by ID
 * {@link /api/v1/comment/:id}
 */
export function useGetApiV1CommentByIdSuspense<
  TData = GetApiV1CommentByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CommentByIdSuspenseQueryKey,
>(
  id: GetApiV1CommentByIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1CommentByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1CommentByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getApiV1CommentByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
