/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1CollegesSearchQueryResponse,
  GetApiV1CollegesSearchQueryParams,
} from "../models/GetApiV1CollegesSearch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1CollegesSearch } from "../clients/getApiV1CollegesSearch.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1CollegesSearchSuspenseQueryKey = (
  params: GetApiV1CollegesSearchQueryParams = {},
) => [{ url: "/api/v1/colleges/search" }, ...(params ? [params] : [])] as const;

export type GetApiV1CollegesSearchSuspenseQueryKey = ReturnType<
  typeof getApiV1CollegesSearchSuspenseQueryKey
>;

export function getApiV1CollegesSearchSuspenseQueryOptions(
  params?: GetApiV1CollegesSearchQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CollegesSearchSuspenseQueryKey(params);
  return queryOptions<
    GetApiV1CollegesSearchQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CollegesSearchQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1CollegesSearch(params, config);
    },
  });
}

/**
 * @summary Get API v1 colleges search
 * {@link /api/v1/colleges/search}
 */
export function useGetApiV1CollegesSearchSuspense<
  TData = GetApiV1CollegesSearchQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CollegesSearchSuspenseQueryKey,
>(
  params?: GetApiV1CollegesSearchQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1CollegesSearchQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1CollegesSearchSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getApiV1CollegesSearchSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
