/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserTagByUserIdFollowsQueryResponse,
  GetApiV1UserTagByUserIdFollowsPathParams,
} from "../models/GetApiV1UserTagByUserIdFollows.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1UserTagByUserIdFollows } from "../clients/getApiV1UserTagByUserIdFollows.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1UserTagByUserIdFollowsQueryKey = (
  user_id: GetApiV1UserTagByUserIdFollowsPathParams["user_id"],
) =>
  [{ url: "/api/v1/user/tag/follows", params: { user_id: user_id } }] as const;

export type GetApiV1UserTagByUserIdFollowsQueryKey = ReturnType<
  typeof getApiV1UserTagByUserIdFollowsQueryKey
>;

export function getApiV1UserTagByUserIdFollowsQueryOptions(
  user_id: GetApiV1UserTagByUserIdFollowsPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1UserTagByUserIdFollowsQueryKey(user_id);
  return queryOptions<
    GetApiV1UserTagByUserIdFollowsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1UserTagByUserIdFollowsQueryResponse,
    typeof queryKey
  >({
    enabled: !!user_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1UserTagByUserIdFollows(user_id, config);
    },
  });
}

/**
 * @summary Get API v1 user tag by user ID follows
 * {@link /api/v1/user/tag/follows}
 */
export function useGetApiV1UserTagByUserIdFollows<
  TData = GetApiV1UserTagByUserIdFollowsQueryResponse,
  TQueryData = GetApiV1UserTagByUserIdFollowsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1UserTagByUserIdFollowsQueryKey,
>(
  user_id: GetApiV1UserTagByUserIdFollowsPathParams["user_id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1UserTagByUserIdFollowsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1UserTagByUserIdFollowsQueryKey(user_id);

  const query = useQuery(
    {
      ...getApiV1UserTagByUserIdFollowsQueryOptions(user_id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
