/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1PostsPremiumByTagByTagIdQueryResponse,
  GetApiV1PostsPremiumByTagByTagIdPathParams,
  GetApiV1PostsPremiumByTagByTagIdQueryParams,
} from "../models/GetApiV1PostsPremiumByTagByTagId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsPremiumByTagByTagId } from "../clients/getApiV1PostsPremiumByTagByTagId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostsPremiumByTagByTagIdQueryKey = (
  tag_id: GetApiV1PostsPremiumByTagByTagIdPathParams["tag_id"],
  params?: GetApiV1PostsPremiumByTagByTagIdQueryParams,
) =>
  [
    { url: "/api/v1/posts/premium/by-tag/:tag_id", params: { tag_id: tag_id } },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1PostsPremiumByTagByTagIdQueryKey = ReturnType<
  typeof getApiV1PostsPremiumByTagByTagIdQueryKey
>;

export function getApiV1PostsPremiumByTagByTagIdQueryOptions(
  tag_id: GetApiV1PostsPremiumByTagByTagIdPathParams["tag_id"],
  params?: GetApiV1PostsPremiumByTagByTagIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsPremiumByTagByTagIdQueryKey(tag_id, params);
  return queryOptions<
    GetApiV1PostsPremiumByTagByTagIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsPremiumByTagByTagIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!tag_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1PostsPremiumByTagByTagId(tag_id, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 posts premium by tag by tag ID
 * {@link /api/v1/posts/premium/by-tag/:tag_id}
 */
export function useGetApiV1PostsPremiumByTagByTagId<
  TData = GetApiV1PostsPremiumByTagByTagIdQueryResponse,
  TQueryData = GetApiV1PostsPremiumByTagByTagIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsPremiumByTagByTagIdQueryKey,
>(
  tag_id: GetApiV1PostsPremiumByTagByTagIdPathParams["tag_id"],
  params?: GetApiV1PostsPremiumByTagByTagIdQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostsPremiumByTagByTagIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1PostsPremiumByTagByTagIdQueryKey(tag_id, params);

  const query = useQuery(
    {
      ...getApiV1PostsPremiumByTagByTagIdQueryOptions(tag_id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
