/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1StripeProductByIdQueryResponse,
  GetApiV1StripeProductByIdPathParams,
} from "../models/GetApiV1StripeProductById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1StripeProductById } from "../clients/getApiV1StripeProductById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1StripeProductByIdQueryKey = (
  id: GetApiV1StripeProductByIdPathParams["id"],
) => [{ url: "/api/v1/stripe_product/:id", params: { id: id } }] as const;

export type GetApiV1StripeProductByIdQueryKey = ReturnType<
  typeof getApiV1StripeProductByIdQueryKey
>;

export function getApiV1StripeProductByIdQueryOptions(
  id: GetApiV1StripeProductByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1StripeProductByIdQueryKey(id);
  return queryOptions<
    GetApiV1StripeProductByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1StripeProductByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1StripeProductById(id, config);
    },
  });
}

/**
 * @summary Get API v1 stripe product by ID
 * {@link /api/v1/stripe_product/:id}
 */
export function useGetApiV1StripeProductById<
  TData = GetApiV1StripeProductByIdQueryResponse,
  TQueryData = GetApiV1StripeProductByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1StripeProductByIdQueryKey,
>(
  id: GetApiV1StripeProductByIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1StripeProductByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1StripeProductByIdQueryKey(id);

  const query = useQuery(
    {
      ...getApiV1StripeProductByIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
