/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumBySportBySportIdQueryResponse,
  GetApiV1PostsPremiumBySportBySportIdPathParams,
  GetApiV1PostsPremiumBySportBySportIdQueryParams,
} from "../models/GetApiV1PostsPremiumBySportBySportId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsPremiumBySportBySportId } from "../clients/getApiV1PostsPremiumBySportBySportId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1PostsPremiumBySportBySportIdSuspenseQueryKey = (
  sport_id: GetApiV1PostsPremiumBySportBySportIdPathParams["sport_id"],
  params: GetApiV1PostsPremiumBySportBySportIdQueryParams = {},
) =>
  [
    {
      url: "/api/v1/posts/premium/by-sport/:sport_id",
      params: { sport_id: sport_id },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1PostsPremiumBySportBySportIdSuspenseQueryKey = ReturnType<
  typeof getApiV1PostsPremiumBySportBySportIdSuspenseQueryKey
>;

export function getApiV1PostsPremiumBySportBySportIdSuspenseQueryOptions(
  sport_id: GetApiV1PostsPremiumBySportBySportIdPathParams["sport_id"],
  params?: GetApiV1PostsPremiumBySportBySportIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsPremiumBySportBySportIdSuspenseQueryKey(
    sport_id,
    params,
  );
  return queryOptions<
    GetApiV1PostsPremiumBySportBySportIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsPremiumBySportBySportIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!sport_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostsPremiumBySportBySportId(sport_id, params, config);
    },
  });
}

/**
 * @summary Get API v1 posts premium by sport by sport ID
 * {@link /api/v1/posts/premium/by-sport/:sport_id}
 */
export function useGetApiV1PostsPremiumBySportBySportIdSuspense<
  TData = GetApiV1PostsPremiumBySportBySportIdQueryResponse,
  TQueryKey extends QueryKey =
    GetApiV1PostsPremiumBySportBySportIdSuspenseQueryKey,
>(
  sport_id: GetApiV1PostsPremiumBySportBySportIdPathParams["sport_id"],
  params?: GetApiV1PostsPremiumBySportBySportIdQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1PostsPremiumBySportBySportIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1PostsPremiumBySportBySportIdSuspenseQueryKey(sport_id, params);

  const query = useSuspenseQuery(
    {
      ...getApiV1PostsPremiumBySportBySportIdSuspenseQueryOptions(
        sport_id,
        params,
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
