/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1HealthHealthcheckQueryResponse } from "../models/GetApiV1HealthHealthcheck.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getApiV1HealthHealthcheck } from "../clients/getApiV1HealthHealthcheck.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1HealthHealthcheckSuspenseQueryKey = () => [{ url: '/api/v1/health/healthcheck' }] as const

export type GetApiV1HealthHealthcheckSuspenseQueryKey = ReturnType<typeof getApiV1HealthHealthcheckSuspenseQueryKey>

export function getApiV1HealthHealthcheckSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1HealthHealthcheckSuspenseQueryKey()
        return queryOptions<GetApiV1HealthHealthcheckQueryResponse, ResponseErrorConfig<Error>, GetApiV1HealthHealthcheckQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1HealthHealthcheck(config)
         },
        })

}

/**
 * @summary Get API v1 health healthcheck
 * {@link /api/v1/health/healthcheck}
 */
export function useGetApiV1HealthHealthcheckSuspense<TData = GetApiV1HealthHealthcheckQueryResponse, TQueryKey extends QueryKey = GetApiV1HealthHealthcheckSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetApiV1HealthHealthcheckQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1HealthHealthcheckSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getApiV1HealthHealthcheckSuspenseQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}