/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1SurveyUserByUserIdQueryResponse,
  GetApiV1SurveyUserByUserIdPathParams,
  GetApiV1SurveyUserByUserIdQueryParams,
} from "../models/GetApiV1SurveyUserByUserId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1SurveyUserByUserId } from "../clients/getApiV1SurveyUserByUserId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1SurveyUserByUserIdSuspenseQueryKey = (
  user_id: GetApiV1SurveyUserByUserIdPathParams["user_id"],
  params: GetApiV1SurveyUserByUserIdQueryParams = {},
) =>
  [
    { url: "/api/v1/survey/user/:user_id", params: { user_id: user_id } },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1SurveyUserByUserIdSuspenseQueryKey = ReturnType<
  typeof getApiV1SurveyUserByUserIdSuspenseQueryKey
>;

export function getApiV1SurveyUserByUserIdSuspenseQueryOptions(
  user_id: GetApiV1SurveyUserByUserIdPathParams["user_id"],
  params?: GetApiV1SurveyUserByUserIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1SurveyUserByUserIdSuspenseQueryKey(user_id, params);
  return queryOptions<
    GetApiV1SurveyUserByUserIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1SurveyUserByUserIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!user_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1SurveyUserByUserId(user_id, params, config);
    },
  });
}

/**
 * @summary Get API v1 survey user by user ID
 * {@link /api/v1/survey/user/:user_id}
 */
export function useGetApiV1SurveyUserByUserIdSuspense<
  TData = GetApiV1SurveyUserByUserIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1SurveyUserByUserIdSuspenseQueryKey,
>(
  user_id: GetApiV1SurveyUserByUserIdPathParams["user_id"],
  params?: GetApiV1SurveyUserByUserIdQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1SurveyUserByUserIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1SurveyUserByUserIdSuspenseQueryKey(user_id, params);

  const query = useSuspenseQuery(
    {
      ...getApiV1SurveyUserByUserIdSuspenseQueryOptions(
        user_id,
        params,
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
