/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsSearchQueryResponse,
  GetApiV1PostsSearchQueryParams,
} from "../models/GetApiV1PostsSearch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsSearch } from "../clients/getApiV1PostsSearch.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostsSearchQueryKey = (
  params: GetApiV1PostsSearchQueryParams = {},
) => [{ url: "/api/v1/posts/search" }, ...(params ? [params] : [])] as const;

export type GetApiV1PostsSearchQueryKey = ReturnType<
  typeof getApiV1PostsSearchQueryKey
>;

export function getApiV1PostsSearchQueryOptions(
  params?: GetApiV1PostsSearchQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsSearchQueryKey(params);
  return queryOptions<
    GetApiV1PostsSearchQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsSearchQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostsSearch(params, config);
    },
  });
}

/**
 * @summary Get API v1 posts search
 * {@link /api/v1/posts/search}
 */
export function useGetApiV1PostsSearch<
  TData = GetApiV1PostsSearchQueryResponse,
  TQueryData = GetApiV1PostsSearchQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsSearchQueryKey,
>(
  params?: GetApiV1PostsSearchQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostsSearchQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1PostsSearchQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1PostsSearchQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
