/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserSportBySportIdUsersQueryResponse,
  GetApiV1UserSportBySportIdUsersPathParams,
} from "../models/GetApiV1UserSportBySportIdUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1UserSportBySportIdUsers } from "../clients/getApiV1UserSportBySportIdUsers.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1UserSportBySportIdUsersSuspenseQueryKey = (
  sport_id: GetApiV1UserSportBySportIdUsersPathParams["sport_id"],
) =>
  [
    {
      url: "/api/v1/user/sport/:sport_id/users",
      params: { sport_id: sport_id },
    },
  ] as const;

export type GetApiV1UserSportBySportIdUsersSuspenseQueryKey = ReturnType<
  typeof getApiV1UserSportBySportIdUsersSuspenseQueryKey
>;

export function getApiV1UserSportBySportIdUsersSuspenseQueryOptions(
  sport_id: GetApiV1UserSportBySportIdUsersPathParams["sport_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1UserSportBySportIdUsersSuspenseQueryKey(sport_id);
  return queryOptions<
    GetApiV1UserSportBySportIdUsersQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1UserSportBySportIdUsersQueryResponse,
    typeof queryKey
  >({
    enabled: !!sport_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1UserSportBySportIdUsers(sport_id, config);
    },
  });
}

/**
 * @summary Get API v1 user sport by sport ID users
 * {@link /api/v1/user/sport/:sport_id/users}
 */
export function useGetApiV1UserSportBySportIdUsersSuspense<
  TData = GetApiV1UserSportBySportIdUsersQueryResponse,
  TQueryKey extends QueryKey = GetApiV1UserSportBySportIdUsersSuspenseQueryKey,
>(
  sport_id: GetApiV1UserSportBySportIdUsersPathParams["sport_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1UserSportBySportIdUsersQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1UserSportBySportIdUsersSuspenseQueryKey(sport_id);

  const query = useSuspenseQuery(
    {
      ...getApiV1UserSportBySportIdUsersSuspenseQueryOptions(sport_id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
