/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1RoleByIdQueryResponse,
  GetApiV1RoleByIdPathParams,
} from "../models/GetApiV1RoleById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1RoleById } from "../clients/getApiV1RoleById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1RoleByIdSuspenseQueryKey = (
  id: GetApiV1RoleByIdPathParams["id"],
) => [{ url: "/api/v1/role/:id", params: { id: id } }] as const;

export type GetApiV1RoleByIdSuspenseQueryKey = ReturnType<
  typeof getApiV1RoleByIdSuspenseQueryKey
>;

export function getApiV1RoleByIdSuspenseQueryOptions(
  id: GetApiV1RoleByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1RoleByIdSuspenseQueryKey(id);
  return queryOptions<
    GetApiV1RoleByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1RoleByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1RoleById(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 role by ID
 * {@link /api/v1/role/:id}
 */
export function useGetApiV1RoleByIdSuspense<
  TData = GetApiV1RoleByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1RoleByIdSuspenseQueryKey,
>(
  id: GetApiV1RoleByIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1RoleByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1RoleByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getApiV1RoleByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
