/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
  GetApiV1PostsPremiumByAuthorByAuthorIdPathParams,
  GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams,
} from "../models/GetApiV1PostsPremiumByAuthorByAuthorId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsPremiumByAuthorByAuthorId } from "../clients/getApiV1PostsPremiumByAuthorByAuthorId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostsPremiumByAuthorByAuthorIdQueryKey = (
  author_id: GetApiV1PostsPremiumByAuthorByAuthorIdPathParams["author_id"],
  params: GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams = {},
) =>
  [
    {
      url: "/api/v1/posts/premium/by-author/:author_id",
      params: { author_id: author_id },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1PostsPremiumByAuthorByAuthorIdQueryKey = ReturnType<
  typeof getApiV1PostsPremiumByAuthorByAuthorIdQueryKey
>;

export function getApiV1PostsPremiumByAuthorByAuthorIdQueryOptions(
  author_id: GetApiV1PostsPremiumByAuthorByAuthorIdPathParams["author_id"],
  params?: GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsPremiumByAuthorByAuthorIdQueryKey(
    author_id,
    params,
  );
  return queryOptions<
    GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!author_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostsPremiumByAuthorByAuthorId(author_id, params, config);
    },
  });
}

/**
 * @summary Get API v1 posts premium by author by author ID
 * {@link /api/v1/posts/premium/by-author/:author_id}
 */
export function useGetApiV1PostsPremiumByAuthorByAuthorId<
  TData = GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
  TQueryData = GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsPremiumByAuthorByAuthorIdQueryKey,
>(
  author_id: GetApiV1PostsPremiumByAuthorByAuthorIdPathParams["author_id"],
  params?: GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1PostsPremiumByAuthorByAuthorIdQueryKey(author_id, params);

  const query = useQuery(
    {
      ...getApiV1PostsPremiumByAuthorByAuthorIdQueryOptions(
        author_id,
        params,
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
