/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumFilterQueryResponse,
  GetApiV1PostsPremiumFilterQueryParams,
} from "../models/GetApiV1PostsPremiumFilter.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsPremiumFilter } from "../clients/getApiV1PostsPremiumFilter.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1PostsPremiumFilterSuspenseQueryKey = (
  params: GetApiV1PostsPremiumFilterQueryParams = {},
) =>
  [
    { url: "/api/v1/posts/premium/filter" },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1PostsPremiumFilterSuspenseQueryKey = ReturnType<
  typeof getApiV1PostsPremiumFilterSuspenseQueryKey
>;

export function getApiV1PostsPremiumFilterSuspenseQueryOptions(
  params?: GetApiV1PostsPremiumFilterQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsPremiumFilterSuspenseQueryKey(params);
  return queryOptions<
    GetApiV1PostsPremiumFilterQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsPremiumFilterQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostsPremiumFilter(params, config);
    },
  });
}

/**
 * @summary Get API v1 posts premium filter
 * {@link /api/v1/posts/premium/filter}
 */
export function useGetApiV1PostsPremiumFilterSuspense<
  TData = GetApiV1PostsPremiumFilterQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsPremiumFilterSuspenseQueryKey,
>(
  params?: GetApiV1PostsPremiumFilterQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1PostsPremiumFilterQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1PostsPremiumFilterSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getApiV1PostsPremiumFilterSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
