/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetApiV1PostsBySportBySportIdQueryResponse,
  GetApiV1PostsBySportBySportIdPathParams,
  GetApiV1PostsBySportBySportIdQueryParams,
} from "../models/GetApiV1PostsBySportBySportId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1PostsBySportBySportId } from "../clients/getApiV1PostsBySportBySportId.ts";

export const getApiV1PostsBySportBySportIdSuspenseQueryKey = (
  sport_id: GetApiV1PostsBySportBySportIdPathParams["sport_id"],
  params?: GetApiV1PostsBySportBySportIdQueryParams,
) =>
  [
    { url: "/api/v1/posts/by-sport/:sport_id", params: { sport_id: sport_id } },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1PostsBySportBySportIdSuspenseQueryKey = ReturnType<
  typeof getApiV1PostsBySportBySportIdSuspenseQueryKey
>;

export function getApiV1PostsBySportBySportIdSuspenseQueryOptions(
  sport_id: GetApiV1PostsBySportBySportIdPathParams["sport_id"],
  params?: GetApiV1PostsBySportBySportIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsBySportBySportIdSuspenseQueryKey(
    sport_id,
    params,
  );
  return queryOptions<
    GetApiV1PostsBySportBySportIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsBySportBySportIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!sport_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1PostsBySportBySportId(sport_id, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 posts by sport by sport ID
 * {@link /api/v1/posts/by-sport/:sport_id}
 */
export function useGetApiV1PostsBySportBySportIdSuspense<
  TData = GetApiV1PostsBySportBySportIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsBySportBySportIdSuspenseQueryKey,
>(
  sport_id: GetApiV1PostsBySportBySportIdPathParams["sport_id"],
  params?: GetApiV1PostsBySportBySportIdQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1PostsBySportBySportIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1PostsBySportBySportIdSuspenseQueryKey(sport_id, params);

  const query = useSuspenseQuery(
    {
      ...getApiV1PostsBySportBySportIdSuspenseQueryOptions(
        sport_id,
        params,
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
