/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1CollegesQueryResponse } from "../models/GetApiV1Colleges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1Colleges } from "../clients/getApiV1Colleges.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1CollegesQueryKey = () =>
  [{ url: "/api/v1/colleges/" }] as const;

export type GetApiV1CollegesQueryKey = ReturnType<
  typeof getApiV1CollegesQueryKey
>;

export function getApiV1CollegesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CollegesQueryKey();
  return queryOptions<
    GetApiV1CollegesQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CollegesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1Colleges(config);
    },
  });
}

/**
 * @summary Get API v1 colleges
 * {@link /api/v1/colleges/}
 */
export function useGetApiV1Colleges<
  TData = GetApiV1CollegesQueryResponse,
  TQueryData = GetApiV1CollegesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CollegesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1CollegesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getApiV1CollegesQueryKey();

  const query = useQuery(
    {
      ...getApiV1CollegesQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
