/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostByIdQueryResponse,
  GetApiV1PostByIdPathParams,
} from "../models/GetApiV1PostById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostById } from "../clients/getApiV1PostById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostByIdQueryKey = (
  id: GetApiV1PostByIdPathParams["id"],
) => [{ url: "/api/v1/post/:id", params: { id: id } }] as const;

export type GetApiV1PostByIdQueryKey = ReturnType<
  typeof getApiV1PostByIdQueryKey
>;

export function getApiV1PostByIdQueryOptions(
  id: GetApiV1PostByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostByIdQueryKey(id);
  return queryOptions<
    GetApiV1PostByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostById(id, config);
    },
  });
}

/**
 * @summary Get API v1 post by ID
 * {@link /api/v1/post/:id}
 */
export function useGetApiV1PostById<
  TData = GetApiV1PostByIdQueryResponse,
  TQueryData = GetApiV1PostByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostByIdQueryKey,
>(
  id: GetApiV1PostByIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getApiV1PostByIdQueryKey(id);

  const query = useQuery(
    {
      ...getApiV1PostByIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
