/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumFilterQueryResponse,
  GetApiV1PostsPremiumFilterQueryParams,
} from "../models/GetApiV1PostsPremiumFilter.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsPremiumFilter } from "../clients/getApiV1PostsPremiumFilter.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostsPremiumFilterQueryKey = (
  params: GetApiV1PostsPremiumFilterQueryParams = {},
) =>
  [
    { url: "/api/v1/posts/premium/filter" },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1PostsPremiumFilterQueryKey = ReturnType<
  typeof getApiV1PostsPremiumFilterQueryKey
>;

export function getApiV1PostsPremiumFilterQueryOptions(
  params?: GetApiV1PostsPremiumFilterQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsPremiumFilterQueryKey(params);
  return queryOptions<
    GetApiV1PostsPremiumFilterQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsPremiumFilterQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostsPremiumFilter(params, config);
    },
  });
}

/**
 * @summary Get API v1 posts premium filter
 * {@link /api/v1/posts/premium/filter}
 */
export function useGetApiV1PostsPremiumFilter<
  TData = GetApiV1PostsPremiumFilterQueryResponse,
  TQueryData = GetApiV1PostsPremiumFilterQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsPremiumFilterQueryKey,
>(
  params?: GetApiV1PostsPremiumFilterQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostsPremiumFilterQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1PostsPremiumFilterQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1PostsPremiumFilterQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
