/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1CollegesQueryResponse,
  GetApiV1CollegesQueryParams,
} from "../models/GetApiV1Colleges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1Colleges } from "../clients/getApiV1Colleges.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1CollegesQueryKey = (
  params?: GetApiV1CollegesQueryParams,
) => [{ url: "/api/v1/colleges/" }, ...(params ? [params] : [])] as const;

export type GetApiV1CollegesQueryKey = ReturnType<
  typeof getApiV1CollegesQueryKey
>;

export function getApiV1CollegesQueryOptions(
  params?: GetApiV1CollegesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CollegesQueryKey(params);
  return queryOptions<
    GetApiV1CollegesQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CollegesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Colleges(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 colleges
 * {@link /api/v1/colleges/}
 */
export function useGetApiV1Colleges<
  TData = GetApiV1CollegesQueryResponse,
  TQueryData = GetApiV1CollegesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CollegesQueryKey,
>(
  params?: GetApiV1CollegesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1CollegesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1CollegesQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1CollegesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
