/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1TagQueryResponse,
  GetApiV1TagQueryParams,
} from "../models/GetApiV1Tag.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1Tag } from "../clients/getApiV1Tag.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1TagQueryKey = (params?: GetApiV1TagQueryParams) =>
  [{ url: "/api/v1/tag" }, ...(params ? [params] : [])] as const;

export type GetApiV1TagQueryKey = ReturnType<typeof getApiV1TagQueryKey>;

export function getApiV1TagQueryOptions(
  params?: GetApiV1TagQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1TagQueryKey(params);
  return queryOptions<
    GetApiV1TagQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1TagQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Tag(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 tag
 * {@link /api/v1/tag}
 */
export function useGetApiV1Tag<
  TData = GetApiV1TagQueryResponse,
  TQueryData = GetApiV1TagQueryResponse,
  TQueryKey extends QueryKey = GetApiV1TagQueryKey,
>(
  params?: GetApiV1TagQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1TagQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiV1TagQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1TagQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
