/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1SportsSearchQueryResponse,
  GetApiV1SportsSearchQueryParams,
} from "../models/GetApiV1SportsSearch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1SportsSearch } from "../clients/getApiV1SportsSearch.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1SportsSearchSuspenseQueryKey = (
  params: GetApiV1SportsSearchQueryParams = {},
) => [{ url: "/api/v1/sports/search" }, ...(params ? [params] : [])] as const;

export type GetApiV1SportsSearchSuspenseQueryKey = ReturnType<
  typeof getApiV1SportsSearchSuspenseQueryKey
>;

export function getApiV1SportsSearchSuspenseQueryOptions(
  params?: GetApiV1SportsSearchQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1SportsSearchSuspenseQueryKey(params);
  return queryOptions<
    GetApiV1SportsSearchQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1SportsSearchQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1SportsSearch(params, config);
    },
  });
}

/**
 * @summary Get API v1 sports search
 * {@link /api/v1/sports/search}
 */
export function useGetApiV1SportsSearchSuspense<
  TData = GetApiV1SportsSearchQueryResponse,
  TQueryKey extends QueryKey = GetApiV1SportsSearchSuspenseQueryKey,
>(
  params?: GetApiV1SportsSearchQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1SportsSearchQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1SportsSearchSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getApiV1SportsSearchSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
