/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1CommentByIdQueryResponse, GetApiV1CommentByIdPathParams } from "../models/GetApiV1CommentById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApiV1CommentById } from "../clients/getApiV1CommentById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1CommentByIdQueryKey = (id: GetApiV1CommentByIdPathParams["id"]) => [{ url: '/api/v1/comment/:id', params: {id:id} }] as const

export type GetApiV1CommentByIdQueryKey = ReturnType<typeof getApiV1CommentByIdQueryKey>

export function getApiV1CommentByIdQueryOptions(id: GetApiV1CommentByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1CommentByIdQueryKey(id)
        return queryOptions<GetApiV1CommentByIdQueryResponse, ResponseErrorConfig<Error>, GetApiV1CommentByIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1CommentById(id, config)
         },
        })

}

/**
 * @summary Get API v1 comment by ID
 * {@link /api/v1/comment/:id}
 */
export function useGetApiV1CommentById<TData = GetApiV1CommentByIdQueryResponse, TQueryData = GetApiV1CommentByIdQueryResponse, TQueryKey extends QueryKey = GetApiV1CommentByIdQueryKey>(id: GetApiV1CommentByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1CommentByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1CommentByIdQueryKey(id)
         

         const query = useQuery({
          ...getApiV1CommentByIdQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}