/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserCollegeByUserIdFollowsQueryResponse,
  GetApiV1UserCollegeByUserIdFollowsPathParams,
} from "../models/GetApiV1UserCollegeByUserIdFollows.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1UserCollegeByUserIdFollows } from "../clients/getApiV1UserCollegeByUserIdFollows.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1UserCollegeByUserIdFollowsQueryKey = (
  user_id: GetApiV1UserCollegeByUserIdFollowsPathParams["user_id"],
) =>
  [
    {
      url: "/api/v1/user/college/:user_id/follows",
      params: { user_id: user_id },
    },
  ] as const;

export type GetApiV1UserCollegeByUserIdFollowsQueryKey = ReturnType<
  typeof getApiV1UserCollegeByUserIdFollowsQueryKey
>;

export function getApiV1UserCollegeByUserIdFollowsQueryOptions(
  user_id: GetApiV1UserCollegeByUserIdFollowsPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1UserCollegeByUserIdFollowsQueryKey(user_id);
  return queryOptions<
    GetApiV1UserCollegeByUserIdFollowsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1UserCollegeByUserIdFollowsQueryResponse,
    typeof queryKey
  >({
    enabled: !!user_id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1UserCollegeByUserIdFollows(user_id, config);
    },
  });
}

/**
 * @summary Get API v1 user college by user ID follows
 * {@link /api/v1/user/college/:user_id/follows}
 */
export function useGetApiV1UserCollegeByUserIdFollows<
  TData = GetApiV1UserCollegeByUserIdFollowsQueryResponse,
  TQueryData = GetApiV1UserCollegeByUserIdFollowsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1UserCollegeByUserIdFollowsQueryKey,
>(
  user_id: GetApiV1UserCollegeByUserIdFollowsPathParams["user_id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1UserCollegeByUserIdFollowsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1UserCollegeByUserIdFollowsQueryKey(user_id);

  const query = useQuery(
    {
      ...getApiV1UserCollegeByUserIdFollowsQueryOptions(user_id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
