/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumQueryResponse,
  GetApiV1PostsPremiumQueryParams,
} from "../models/GetApiV1PostsPremium.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1PostsPremium } from "../clients/getApiV1PostsPremium.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1PostsPremiumQueryKey = (
  params: GetApiV1PostsPremiumQueryParams = {},
) => [{ url: "/api/v1/posts/premium/" }, ...(params ? [params] : [])] as const;

export type GetApiV1PostsPremiumQueryKey = ReturnType<
  typeof getApiV1PostsPremiumQueryKey
>;

export function getApiV1PostsPremiumQueryOptions(
  params?: GetApiV1PostsPremiumQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1PostsPremiumQueryKey(params);
  return queryOptions<
    GetApiV1PostsPremiumQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1PostsPremiumQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1PostsPremium(params, config);
    },
  });
}

/**
 * @summary Get API v1 posts premium
 * {@link /api/v1/posts/premium/}
 */
export function useGetApiV1PostsPremium<
  TData = GetApiV1PostsPremiumQueryResponse,
  TQueryData = GetApiV1PostsPremiumQueryResponse,
  TQueryKey extends QueryKey = GetApiV1PostsPremiumQueryKey,
>(
  params?: GetApiV1PostsPremiumQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1PostsPremiumQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1PostsPremiumQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1PostsPremiumQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
