/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1RoleByIdQueryResponse,
  GetApiV1RoleByIdPathParams,
} from "../models/GetApiV1RoleById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1RoleById } from "../clients/getApiV1RoleById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1RoleByIdQueryKey = (
  id: GetApiV1RoleByIdPathParams["id"],
) => [{ url: "/api/v1/role/:id", params: { id: id } }] as const;

export type GetApiV1RoleByIdQueryKey = ReturnType<
  typeof getApiV1RoleByIdQueryKey
>;

export function getApiV1RoleByIdQueryOptions(
  id: GetApiV1RoleByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1RoleByIdQueryKey(id);
  return queryOptions<
    GetApiV1RoleByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1RoleByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1RoleById(id, config);
    },
  });
}

/**
 * @summary Get API v1 role by ID
 * {@link /api/v1/role/:id}
 */
export function useGetApiV1RoleById<
  TData = GetApiV1RoleByIdQueryResponse,
  TQueryData = GetApiV1RoleByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1RoleByIdQueryKey,
>(
  id: GetApiV1RoleByIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1RoleByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getApiV1RoleByIdQueryKey(id);

  const query = useQuery(
    {
      ...getApiV1RoleByIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
