/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1CheckoutSessionsByIdQueryResponse, GetApiV1CheckoutSessionsByIdPathParams } from "../models/GetApiV1CheckoutSessionsById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApiV1CheckoutSessionsById } from "../clients/getApiV1CheckoutSessionsById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1CheckoutSessionsByIdQueryKey = (id: GetApiV1CheckoutSessionsByIdPathParams["id"]) => [{ url: '/api/v1/checkout/sessions/:id', params: {id:id} }] as const

export type GetApiV1CheckoutSessionsByIdQueryKey = ReturnType<typeof getApiV1CheckoutSessionsByIdQueryKey>

export function getApiV1CheckoutSessionsByIdQueryOptions(id: GetApiV1CheckoutSessionsByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1CheckoutSessionsByIdQueryKey(id)
        return queryOptions<GetApiV1CheckoutSessionsByIdQueryResponse, ResponseErrorConfig<Error>, GetApiV1CheckoutSessionsByIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1CheckoutSessionsById(id, config)
         },
        })

}

/**
 * @summary Get API v1 checkout sessions by ID
 * {@link /api/v1/checkout/sessions/:id}
 */
export function useGetApiV1CheckoutSessionsById<TData = GetApiV1CheckoutSessionsByIdQueryResponse, TQueryData = GetApiV1CheckoutSessionsByIdQueryResponse, TQueryKey extends QueryKey = GetApiV1CheckoutSessionsByIdQueryKey>(id: GetApiV1CheckoutSessionsByIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1CheckoutSessionsByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1CheckoutSessionsByIdQueryKey(id)
         

         const query = useQuery({
          ...getApiV1CheckoutSessionsByIdQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}