/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1RolesQueryResponse,
  GetApiV1RolesQueryParams,
} from "../models/GetApiV1Roles.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1Roles } from "../clients/getApiV1Roles.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1RolesQueryKey = (params?: GetApiV1RolesQueryParams) =>
  [{ url: "/api/v1/roles/" }, ...(params ? [params] : [])] as const;

export type GetApiV1RolesQueryKey = ReturnType<typeof getApiV1RolesQueryKey>;

export function getApiV1RolesQueryOptions(
  params?: GetApiV1RolesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1RolesQueryKey(params);
  return queryOptions<
    GetApiV1RolesQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1RolesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Roles(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 roles
 * {@link /api/v1/roles/}
 */
export function useGetApiV1Roles<
  TData = GetApiV1RolesQueryResponse,
  TQueryData = GetApiV1RolesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1RolesQueryKey,
>(
  params?: GetApiV1RolesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1RolesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiV1RolesQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1RolesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
