/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1StripeCustomersEmailByEmailQueryResponse,
  GetApiV1StripeCustomersEmailByEmailPathParams,
} from "../models/GetApiV1StripeCustomersEmailByEmail.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1StripeCustomersEmailByEmail } from "../clients/getApiV1StripeCustomersEmailByEmail.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1StripeCustomersEmailByEmailQueryKey = (
  email: GetApiV1StripeCustomersEmailByEmailPathParams["email"],
) =>
  [
    { url: "/api/v1/stripe_customers/email/:email", params: { email: email } },
  ] as const;

export type GetApiV1StripeCustomersEmailByEmailQueryKey = ReturnType<
  typeof getApiV1StripeCustomersEmailByEmailQueryKey
>;

export function getApiV1StripeCustomersEmailByEmailQueryOptions(
  email: GetApiV1StripeCustomersEmailByEmailPathParams["email"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1StripeCustomersEmailByEmailQueryKey(email);
  return queryOptions<
    GetApiV1StripeCustomersEmailByEmailQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1StripeCustomersEmailByEmailQueryResponse,
    typeof queryKey
  >({
    enabled: !!email,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1StripeCustomersEmailByEmail(email, config);
    },
  });
}

/**
 * @summary Get API v1 stripe customers email by email
 * {@link /api/v1/stripe_customers/email/:email}
 */
export function useGetApiV1StripeCustomersEmailByEmail<
  TData = GetApiV1StripeCustomersEmailByEmailQueryResponse,
  TQueryData = GetApiV1StripeCustomersEmailByEmailQueryResponse,
  TQueryKey extends QueryKey = GetApiV1StripeCustomersEmailByEmailQueryKey,
>(
  email: GetApiV1StripeCustomersEmailByEmailPathParams["email"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1StripeCustomersEmailByEmailQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1StripeCustomersEmailByEmailQueryKey(email);

  const query = useQuery(
    {
      ...getApiV1StripeCustomersEmailByEmailQueryOptions(email, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
