/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1UserTagFollowsQueryResponse } from "../models/GetApiV1UserTagFollows.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1UserTagFollows } from "../clients/getApiV1UserTagFollows.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1UserTagFollowsSuspenseQueryKey = () =>
  [{ url: "/api/v1/user/tag/follows" }] as const;

export type GetApiV1UserTagFollowsSuspenseQueryKey = ReturnType<
  typeof getApiV1UserTagFollowsSuspenseQueryKey
>;

export function getApiV1UserTagFollowsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1UserTagFollowsSuspenseQueryKey();
  return queryOptions<
    GetApiV1UserTagFollowsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1UserTagFollowsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1UserTagFollows(config);
    },
  });
}

/**
 * @summary Get API v1 user tag follows
 * {@link /api/v1/user/tag/follows}
 */
export function useGetApiV1UserTagFollowsSuspense<
  TData = GetApiV1UserTagFollowsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1UserTagFollowsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1UserTagFollowsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1UserTagFollowsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getApiV1UserTagFollowsSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
