/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1TagQueryResponse,
  GetApiV1TagQueryParams,
} from "../models/GetApiV1Tag.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1Tag } from "../clients/getApiV1Tag.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1TagSuspenseQueryKey = (params?: GetApiV1TagQueryParams) =>
  [{ url: "/api/v1/tag" }, ...(params ? [params] : [])] as const;

export type GetApiV1TagSuspenseQueryKey = ReturnType<
  typeof getApiV1TagSuspenseQueryKey
>;

export function getApiV1TagSuspenseQueryOptions(
  params?: GetApiV1TagQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1TagSuspenseQueryKey(params);
  return queryOptions<
    GetApiV1TagQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1TagQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Tag(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 tag
 * {@link /api/v1/tag}
 */
export function useGetApiV1TagSuspense<
  TData = GetApiV1TagQueryResponse,
  TQueryKey extends QueryKey = GetApiV1TagSuspenseQueryKey,
>(
  params?: GetApiV1TagQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1TagQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1TagSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getApiV1TagSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
