/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1UserCurrentQueryResponse } from "../models/GetApiV1UserCurrent.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getApiV1UserCurrent } from "../clients/getApiV1UserCurrent.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1UserCurrentQueryKey = () => [{ url: '/api/v1/user/current' }] as const

export type GetApiV1UserCurrentQueryKey = ReturnType<typeof getApiV1UserCurrentQueryKey>

export function getApiV1UserCurrentQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1UserCurrentQueryKey()
        return queryOptions<GetApiV1UserCurrentQueryResponse, ResponseErrorConfig<Error>, GetApiV1UserCurrentQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return getApiV1UserCurrent(config)
         },
        })

}

/**
 * @summary Get API v1 user current
 * {@link /api/v1/user/current}
 */
export function useGetApiV1UserCurrent<TData = GetApiV1UserCurrentQueryResponse, TQueryData = GetApiV1UserCurrentQueryResponse, TQueryKey extends QueryKey = GetApiV1UserCurrentQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1UserCurrentQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? getApiV1UserCurrentQueryKey()
         

         const query = useQuery({
          ...getApiV1UserCurrentQueryOptions(config),
          queryKey,
          ...queryOptions
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}