/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetApiV1TagByIdQueryResponse,
  GetApiV1TagByIdPathParams,
} from "../models/GetApiV1TagById.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getApiV1TagById } from "../clients/getApiV1TagById.ts";

export const getApiV1TagByIdQueryKey = (id: GetApiV1TagByIdPathParams["id"]) =>
  [{ url: "/api/v1/tag/:id", params: { id: id } }] as const;

export type GetApiV1TagByIdQueryKey = ReturnType<
  typeof getApiV1TagByIdQueryKey
>;

export function getApiV1TagByIdQueryOptions(
  id: GetApiV1TagByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1TagByIdQueryKey(id);
  return queryOptions<
    GetApiV1TagByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1TagByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1TagById(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 tag by ID
 * {@link /api/v1/tag/:id}
 */
export function useGetApiV1TagById<
  TData = GetApiV1TagByIdQueryResponse,
  TQueryData = GetApiV1TagByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1TagByIdQueryKey,
>(
  id: GetApiV1TagByIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1TagByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiV1TagByIdQueryKey(id);

  const query = useQuery(
    {
      ...getApiV1TagByIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
