/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1CheckoutSessionsByIdQueryResponse,
  GetApiV1CheckoutSessionsByIdPathParams,
} from "../models/GetApiV1CheckoutSessionsById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { getApiV1CheckoutSessionsById } from "../clients/getApiV1CheckoutSessionsById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getApiV1CheckoutSessionsByIdSuspenseQueryKey = (
  id: GetApiV1CheckoutSessionsByIdPathParams["id"],
) => [{ url: "/api/v1/checkout/sessions/:id", params: { id: id } }] as const;

export type GetApiV1CheckoutSessionsByIdSuspenseQueryKey = ReturnType<
  typeof getApiV1CheckoutSessionsByIdSuspenseQueryKey
>;

export function getApiV1CheckoutSessionsByIdSuspenseQueryOptions(
  id: GetApiV1CheckoutSessionsByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CheckoutSessionsByIdSuspenseQueryKey(id);
  return queryOptions<
    GetApiV1CheckoutSessionsByIdQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CheckoutSessionsByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getApiV1CheckoutSessionsById(id, config);
    },
  });
}

/**
 * @summary Get API v1 checkout sessions by ID
 * {@link /api/v1/checkout/sessions/:id}
 */
export function useGetApiV1CheckoutSessionsByIdSuspense<
  TData = GetApiV1CheckoutSessionsByIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CheckoutSessionsByIdSuspenseQueryKey,
>(
  id: GetApiV1CheckoutSessionsByIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1CheckoutSessionsByIdQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getApiV1CheckoutSessionsByIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getApiV1CheckoutSessionsByIdSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
