/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetApiV1CollegeQueryResponse,
  GetApiV1CollegeQueryParams,
} from "../models/GetApiV1College.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { getApiV1College } from "../clients/getApiV1College.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getApiV1CollegeQueryKey = (params?: GetApiV1CollegeQueryParams) =>
  [{ url: "/api/v1/college/" }, ...(params ? [params] : [])] as const;

export type GetApiV1CollegeQueryKey = ReturnType<
  typeof getApiV1CollegeQueryKey
>;

export function getApiV1CollegeQueryOptions(
  params?: GetApiV1CollegeQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1CollegeQueryKey(params);
  return queryOptions<
    GetApiV1CollegeQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1CollegeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1College(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary Get API v1 college
 * {@link /api/v1/college/}
 */
export function useGetApiV1College<
  TData = GetApiV1CollegeQueryResponse,
  TQueryData = GetApiV1CollegeQueryResponse,
  TQueryKey extends QueryKey = GetApiV1CollegeQueryKey,
>(
  params?: GetApiV1CollegeQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1CollegeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getApiV1CollegeQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1CollegeQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
