/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListApiV1UserByUserIdCommentsQueryResponse,
  ListApiV1UserByUserIdCommentsPathParams,
} from "../models/ListApiV1UserByUserIdComments.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { listApiV1UserByUserIdComments } from "../clients/listApiV1UserByUserIdComments.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listApiV1UserByUserIdCommentsSuspenseQueryKey = (
  user_id: ListApiV1UserByUserIdCommentsPathParams["user_id"],
) =>
  [
    { url: "/api/v1/user/:user_id/comments", params: { user_id: user_id } },
  ] as const;

export type ListApiV1UserByUserIdCommentsSuspenseQueryKey = ReturnType<
  typeof listApiV1UserByUserIdCommentsSuspenseQueryKey
>;

export function listApiV1UserByUserIdCommentsSuspenseQueryOptions(
  user_id: ListApiV1UserByUserIdCommentsPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listApiV1UserByUserIdCommentsSuspenseQueryKey(user_id);
  return queryOptions<
    ListApiV1UserByUserIdCommentsQueryResponse,
    ResponseErrorConfig<Error>,
    ListApiV1UserByUserIdCommentsQueryResponse,
    typeof queryKey
  >({
    enabled: !!user_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return listApiV1UserByUserIdComments(user_id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List API v1 user by user ID comments
 * {@link /api/v1/user/:user_id/comments}
 */
export function useListApiV1UserByUserIdCommentsSuspense<
  TData = ListApiV1UserByUserIdCommentsQueryResponse,
  TQueryKey extends QueryKey = ListApiV1UserByUserIdCommentsSuspenseQueryKey,
>(
  user_id: ListApiV1UserByUserIdCommentsPathParams["user_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListApiV1UserByUserIdCommentsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    listApiV1UserByUserIdCommentsSuspenseQueryKey(user_id);

  const query = useSuspenseQuery(
    {
      ...listApiV1UserByUserIdCommentsSuspenseQueryOptions(user_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
