/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListApiV1CheckoutSessionsQueryResponse,
  ListApiV1CheckoutSessionsQueryParams,
} from "../models/ListApiV1CheckoutSessions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { listApiV1CheckoutSessions } from "../clients/listApiV1CheckoutSessions.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listApiV1CheckoutSessionsQueryKey = (
  params?: ListApiV1CheckoutSessionsQueryParams,
) =>
  [{ url: "/api/v1/checkout/sessions/" }, ...(params ? [params] : [])] as const;

export type ListApiV1CheckoutSessionsQueryKey = ReturnType<
  typeof listApiV1CheckoutSessionsQueryKey
>;

export function listApiV1CheckoutSessionsQueryOptions(
  params?: ListApiV1CheckoutSessionsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listApiV1CheckoutSessionsQueryKey(params);
  return queryOptions<
    ListApiV1CheckoutSessionsQueryResponse,
    ResponseErrorConfig<Error>,
    ListApiV1CheckoutSessionsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listApiV1CheckoutSessions(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List API v1 checkout sessions
 * {@link /api/v1/checkout/sessions/}
 */
export function useListApiV1CheckoutSessions<
  TData = ListApiV1CheckoutSessionsQueryResponse,
  TQueryData = ListApiV1CheckoutSessionsQueryResponse,
  TQueryKey extends QueryKey = ListApiV1CheckoutSessionsQueryKey,
>(
  params?: ListApiV1CheckoutSessionsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListApiV1CheckoutSessionsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? listApiV1CheckoutSessionsQueryKey(params);

  const query = useQuery(
    {
      ...listApiV1CheckoutSessionsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
