/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ListApiV1StripePricesByIdQueryResponse, ListApiV1StripePricesByIdPathParams } from "../models/ListApiV1StripePricesById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { listApiV1StripePricesById } from "../clients/listApiV1StripePricesById.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const listApiV1StripePricesByIdSuspenseQueryKey = (id: ListApiV1StripePricesByIdPathParams["id"]) => [{ url: '/api/v1/stripe_prices/:id', params: {id:id} }] as const

export type ListApiV1StripePricesByIdSuspenseQueryKey = ReturnType<typeof listApiV1StripePricesByIdSuspenseQueryKey>

export function listApiV1StripePricesByIdSuspenseQueryOptions(id: ListApiV1StripePricesByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listApiV1StripePricesByIdSuspenseQueryKey(id)
        return queryOptions<ListApiV1StripePricesByIdQueryResponse, ResponseErrorConfig<Error>, ListApiV1StripePricesByIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            config.signal = signal
            return listApiV1StripePricesById(id, config)
         },
        })

}

/**
 * @summary List API v1 stripe prices by ID
 * {@link /api/v1/stripe_prices/:id}
 */
export function useListApiV1StripePricesByIdSuspense<TData = ListApiV1StripePricesByIdQueryResponse, TQueryKey extends QueryKey = ListApiV1StripePricesByIdSuspenseQueryKey>(id: ListApiV1StripePricesByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListApiV1StripePricesByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...queryOptions } = queryConfig
         const queryKey = queryOptions?.queryKey ?? listApiV1StripePricesByIdSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...listApiV1StripePricesByIdSuspenseQueryOptions(id, config),
          queryKey,
          ...queryOptions
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}