/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { ListApiV1StripeProductsQueryResponse } from "../models/ListApiV1StripeProducts.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { listApiV1StripeProducts } from "../clients/listApiV1StripeProducts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listApiV1StripeProductsQueryKey = () =>
  [{ url: "/api/v1/stripe_products/" }] as const;

export type ListApiV1StripeProductsQueryKey = ReturnType<
  typeof listApiV1StripeProductsQueryKey
>;

export function listApiV1StripeProductsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listApiV1StripeProductsQueryKey();
  return queryOptions<
    ListApiV1StripeProductsQueryResponse,
    ResponseErrorConfig<Error>,
    ListApiV1StripeProductsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listApiV1StripeProducts(config);
    },
  });
}

/**
 * @summary List API v1 stripe products
 * {@link /api/v1/stripe_products/}
 */
export function useListApiV1StripeProducts<
  TData = ListApiV1StripeProductsQueryResponse,
  TQueryData = ListApiV1StripeProductsQueryResponse,
  TQueryKey extends QueryKey = ListApiV1StripeProductsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListApiV1StripeProductsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listApiV1StripeProductsQueryKey();

  const query = useQuery(
    {
      ...listApiV1StripeProductsQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
