/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  ListApiV1PostByPostIdCommentsQueryResponse,
  ListApiV1PostByPostIdCommentsPathParams,
} from "../models/ListApiV1PostByPostIdComments.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { listApiV1PostByPostIdComments } from "../clients/listApiV1PostByPostIdComments.ts";

export const listApiV1PostByPostIdCommentsSuspenseQueryKey = (
  post_id: ListApiV1PostByPostIdCommentsPathParams["post_id"],
) =>
  [
    { url: "/api/v1/post/:post_id/comments", params: { post_id: post_id } },
  ] as const;

export type ListApiV1PostByPostIdCommentsSuspenseQueryKey = ReturnType<
  typeof listApiV1PostByPostIdCommentsSuspenseQueryKey
>;

export function listApiV1PostByPostIdCommentsSuspenseQueryOptions(
  post_id: ListApiV1PostByPostIdCommentsPathParams["post_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listApiV1PostByPostIdCommentsSuspenseQueryKey(post_id);
  return queryOptions<
    ListApiV1PostByPostIdCommentsQueryResponse,
    ResponseErrorConfig<Error>,
    ListApiV1PostByPostIdCommentsQueryResponse,
    typeof queryKey
  >({
    enabled: !!post_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return listApiV1PostByPostIdComments(post_id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @summary List API v1 post by post ID comments
 * {@link /api/v1/post/:post_id/comments}
 */
export function useListApiV1PostByPostIdCommentsSuspense<
  TData = ListApiV1PostByPostIdCommentsQueryResponse,
  TQueryKey extends QueryKey = ListApiV1PostByPostIdCommentsSuspenseQueryKey,
>(
  post_id: ListApiV1PostByPostIdCommentsPathParams["post_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListApiV1PostByPostIdCommentsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    listApiV1PostByPostIdCommentsSuspenseQueryKey(post_id);

  const query = useSuspenseQuery(
    {
      ...listApiV1PostByPostIdCommentsSuspenseQueryOptions(post_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
