/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ListApiV1TagTypeByTypeQueryResponse,
  ListApiV1TagTypeByTypePathParams,
} from "../models/ListApiV1TagTypeByType.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { listApiV1TagTypeByType } from "../clients/listApiV1TagTypeByType.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listApiV1TagTypeByTypeQueryKey = (
  type: ListApiV1TagTypeByTypePathParams["type"],
) => [{ url: "/api/v1/tag/type/:type", params: { type: type } }] as const;

export type ListApiV1TagTypeByTypeQueryKey = ReturnType<
  typeof listApiV1TagTypeByTypeQueryKey
>;

export function listApiV1TagTypeByTypeQueryOptions(
  type: ListApiV1TagTypeByTypePathParams["type"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = listApiV1TagTypeByTypeQueryKey(type);
  return queryOptions<
    ListApiV1TagTypeByTypeQueryResponse,
    ResponseErrorConfig<Error>,
    ListApiV1TagTypeByTypeQueryResponse,
    typeof queryKey
  >({
    enabled: !!type,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return listApiV1TagTypeByType(type, config);
    },
  });
}

/**
 * @summary List API v1 tag type by type
 * {@link /api/v1/tag/type/:type}
 */
export function useListApiV1TagTypeByType<
  TData = ListApiV1TagTypeByTypeQueryResponse,
  TQueryData = ListApiV1TagTypeByTypeQueryResponse,
  TQueryKey extends QueryKey = ListApiV1TagTypeByTypeQueryKey,
>(
  type: ListApiV1TagTypeByTypePathParams["type"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListApiV1TagTypeByTypeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? listApiV1TagTypeByTypeQueryKey(type);

  const query = useQuery(
    {
      ...listApiV1TagTypeByTypeQueryOptions(type, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
