/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1UserSportMutationRequest,
  PostApiV1UserSportMutationResponse,
} from "../models/PostApiV1UserSport.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postApiV1UserSport } from "../clients/postApiV1UserSport.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1UserSportMutationKey = () =>
  [{ url: "/api/v1/user/sport/" }] as const;

export type PostApiV1UserSportMutationKey = ReturnType<
  typeof postApiV1UserSportMutationKey
>;

export function postApiV1UserSportMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1UserSportMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postApiV1UserSportMutationKey();
  return mutationOptions<
    PostApiV1UserSportMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserSportMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1UserSport(data, config);
    },
  });
}

/**
 * @summary Post API v1 user sport
 * {@link /api/v1/user/sport/}
 */
export function usePostApiV1UserSport<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1UserSportMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PostApiV1UserSportMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostApiV1UserSportMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1UserSportMutationKey();

  const baseOptions = postApiV1UserSportMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1UserSportMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserSportMutationRequest },
    TContext
  >;

  return useMutation<
    PostApiV1UserSportMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserSportMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1UserSportMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserSportMutationRequest },
    TContext
  >;
}
