/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1ContentConfirmUploadMutationRequest,
  PostApiV1ContentConfirmUploadMutationResponse,
} from "../models/PostApiV1ContentConfirmUpload.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postApiV1ContentConfirmUpload } from "../clients/postApiV1ContentConfirmUpload.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1ContentConfirmUploadMutationKey = () =>
  [{ url: "/api/v1/content/confirm-upload" }] as const;

export type PostApiV1ContentConfirmUploadMutationKey = ReturnType<
  typeof postApiV1ContentConfirmUploadMutationKey
>;

export function postApiV1ContentConfirmUploadMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiV1ContentConfirmUploadMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = postApiV1ContentConfirmUploadMutationKey();
  return mutationOptions<
    PostApiV1ContentConfirmUploadMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ContentConfirmUploadMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1ContentConfirmUpload(data, config);
    },
  });
}

/**
 * @summary Post API v1 content confirm upload
 * {@link /api/v1/content/confirm-upload}
 */
export function usePostApiV1ContentConfirmUpload<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1ContentConfirmUploadMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PostApiV1ContentConfirmUploadMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostApiV1ContentConfirmUploadMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1ContentConfirmUploadMutationKey();

  const baseOptions = postApiV1ContentConfirmUploadMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1ContentConfirmUploadMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ContentConfirmUploadMutationRequest },
    TContext
  >;

  return useMutation<
    PostApiV1ContentConfirmUploadMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ContentConfirmUploadMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1ContentConfirmUploadMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ContentConfirmUploadMutationRequest },
    TContext
  >;
}
