/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostApiV1SportMutationRequest, PostApiV1SportMutationResponse } from "../models/PostApiV1Sport.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { postApiV1Sport } from "../clients/postApiV1Sport.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1SportMutationKey = () => [{ url: '/api/v1/sport/' }] as const

export type PostApiV1SportMutationKey = ReturnType<typeof postApiV1SportMutationKey>

export function postApiV1SportMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiV1SportMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postApiV1SportMutationKey()
        return mutationOptions<PostApiV1SportMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1SportMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postApiV1Sport(data, config)
          },
        })

}

/**
 * @summary Post API v1 sport
 * {@link /api/v1/sport/}
 */
export function usePostApiV1Sport<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiV1SportMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1SportMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiV1SportMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiV1SportMutationKey()

          const baseOptions = postApiV1SportMutationOptions(config) as UseMutationOptions<PostApiV1SportMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1SportMutationRequest}, TContext>
          

          return useMutation<PostApiV1SportMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1SportMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiV1SportMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1SportMutationRequest}, TContext>
      
}