/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PatchApiV1PostByIdMutationRequest,
  PatchApiV1PostByIdMutationResponse,
  PatchApiV1PostByIdPathParams,
} from "../models/PatchApiV1PostById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchApiV1PostById } from "../clients/patchApiV1PostById.ts";

export const patchApiV1PostByIdMutationKey = () =>
  [{ url: "/api/v1/post/:id" }] as const;

export type PatchApiV1PostByIdMutationKey = ReturnType<
  typeof patchApiV1PostByIdMutationKey
>;

export function patchApiV1PostByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchApiV1PostByIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchApiV1PostByIdMutationKey();
  return mutationOptions<
    PatchApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostByIdPathParams["id"];
      data: PatchApiV1PostByIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchApiV1PostById(id, data, config);
    },
  });
}

/**
 * @summary Patch API v1 post by ID
 * {@link /api/v1/post/:id}
 */
export function usePatchApiV1PostById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchApiV1PostByIdMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PatchApiV1PostByIdPathParams["id"];
        data: PatchApiV1PostByIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchApiV1PostByIdMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchApiV1PostByIdMutationKey();

  const baseOptions = patchApiV1PostByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostByIdPathParams["id"];
      data: PatchApiV1PostByIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostByIdPathParams["id"];
      data: PatchApiV1PostByIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchApiV1PostByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostByIdPathParams["id"];
      data: PatchApiV1PostByIdMutationRequest;
    },
    TContext
  >;
}
