/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1UserCollegeMutationRequest,
  PostApiV1UserCollegeMutationResponse,
} from "../models/PostApiV1UserCollege.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postApiV1UserCollege } from "../clients/postApiV1UserCollege.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1UserCollegeMutationKey = () =>
  [{ url: "/api/v1/user/college/" }] as const;

export type PostApiV1UserCollegeMutationKey = ReturnType<
  typeof postApiV1UserCollegeMutationKey
>;

export function postApiV1UserCollegeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1UserCollegeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postApiV1UserCollegeMutationKey();
  return mutationOptions<
    PostApiV1UserCollegeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserCollegeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1UserCollege(data, config);
    },
  });
}

/**
 * @summary Post API v1 user college
 * {@link /api/v1/user/college/}
 */
export function usePostApiV1UserCollege<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1UserCollegeMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PostApiV1UserCollegeMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostApiV1UserCollegeMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1UserCollegeMutationKey();

  const baseOptions = postApiV1UserCollegeMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1UserCollegeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserCollegeMutationRequest },
    TContext
  >;

  return useMutation<
    PostApiV1UserCollegeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserCollegeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1UserCollegeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1UserCollegeMutationRequest },
    TContext
  >;
}
