/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostApiV1CollegeMutationRequest, PostApiV1CollegeMutationResponse } from "../models/PostApiV1College.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { postApiV1College } from "../clients/postApiV1College.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1CollegeMutationKey = () => [{ url: '/api/v1/college' }] as const

export type PostApiV1CollegeMutationKey = ReturnType<typeof postApiV1CollegeMutationKey>

export function postApiV1CollegeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiV1CollegeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postApiV1CollegeMutationKey()
        return mutationOptions<PostApiV1CollegeMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CollegeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postApiV1College(data, config)
          },
        })

}

/**
 * @summary Post API v1 college
 * {@link /api/v1/college}
 */
export function usePostApiV1College<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiV1CollegeMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CollegeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiV1CollegeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiV1CollegeMutationKey()

          const baseOptions = postApiV1CollegeMutationOptions(config) as UseMutationOptions<PostApiV1CollegeMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CollegeMutationRequest}, TContext>
          

          return useMutation<PostApiV1CollegeMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CollegeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiV1CollegeMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CollegeMutationRequest}, TContext>
      
}