/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PatchApiV1TagByIdMutationRequest, PatchApiV1TagByIdMutationResponse, PatchApiV1TagByIdPathParams } from "../models/PatchApiV1TagById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { patchApiV1TagById } from "../clients/patchApiV1TagById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchApiV1TagByIdMutationKey = () => [{ url: '/api/v1/tag/:id' }] as const

export type PatchApiV1TagByIdMutationKey = ReturnType<typeof patchApiV1TagByIdMutationKey>

export function patchApiV1TagByIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PatchApiV1TagByIdMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = patchApiV1TagByIdMutationKey()
        return mutationOptions<PatchApiV1TagByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1TagByIdPathParams["id"], data: PatchApiV1TagByIdMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return patchApiV1TagById(id, data, config)
          },
        })

}

/**
 * @summary Patch API v1 tag by ID
 * {@link /api/v1/tag/:id}
 */
export function usePatchApiV1TagById<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchApiV1TagByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1TagByIdPathParams["id"], data: PatchApiV1TagByIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PatchApiV1TagByIdMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? patchApiV1TagByIdMutationKey()

          const baseOptions = patchApiV1TagByIdMutationOptions(config) as UseMutationOptions<PatchApiV1TagByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1TagByIdPathParams["id"], data: PatchApiV1TagByIdMutationRequest}, TContext>
          

          return useMutation<PatchApiV1TagByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1TagByIdPathParams["id"], data: PatchApiV1TagByIdMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PatchApiV1TagByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1TagByIdPathParams["id"], data: PatchApiV1TagByIdMutationRequest}, TContext>
      
}