/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostApiV1UserMutationRequest, PostApiV1UserMutationResponse } from "../models/PostApiV1User.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { postApiV1User } from "../clients/postApiV1User.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1UserMutationKey = () => [{ url: '/api/v1/user/' }] as const

export type PostApiV1UserMutationKey = ReturnType<typeof postApiV1UserMutationKey>

export function postApiV1UserMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiV1UserMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postApiV1UserMutationKey()
        return mutationOptions<PostApiV1UserMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1UserMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postApiV1User(data, config)
          },
        })

}

/**
 * @summary Post API v1 user
 * {@link /api/v1/user/}
 */
export function usePostApiV1User<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiV1UserMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1UserMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiV1UserMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiV1UserMutationKey()

          const baseOptions = postApiV1UserMutationOptions(config) as UseMutationOptions<PostApiV1UserMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1UserMutationRequest}, TContext>
          

          return useMutation<PostApiV1UserMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1UserMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiV1UserMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1UserMutationRequest}, TContext>
      
}