/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostApiV1UserByIdRolesMutationRequest,
  PostApiV1UserByIdRolesMutationResponse,
  PostApiV1UserByIdRolesPathParams,
} from "../models/PostApiV1UserByIdRoles.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postApiV1UserByIdRoles } from "../clients/postApiV1UserByIdRoles.ts";

export const postApiV1UserByIdRolesMutationKey = () =>
  [{ url: "/api/v1/user/:id/roles" }] as const;

export type PostApiV1UserByIdRolesMutationKey = ReturnType<
  typeof postApiV1UserByIdRolesMutationKey
>;

export function postApiV1UserByIdRolesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1UserByIdRolesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postApiV1UserByIdRolesMutationKey();
  return mutationOptions<
    PostApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiV1UserByIdRolesPathParams["id"];
      data: PostApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postApiV1UserByIdRoles(id, data, config);
    },
  });
}

/**
 * @summary Post API v1 user by ID roles
 * {@link /api/v1/user/:id/roles}
 */
export function usePostApiV1UserByIdRoles<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1UserByIdRolesMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PostApiV1UserByIdRolesPathParams["id"];
        data: PostApiV1UserByIdRolesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostApiV1UserByIdRolesMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1UserByIdRolesMutationKey();

  const baseOptions = postApiV1UserByIdRolesMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiV1UserByIdRolesPathParams["id"];
      data: PostApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiV1UserByIdRolesPathParams["id"];
      data: PostApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PostApiV1UserByIdRolesPathParams["id"];
      data: PostApiV1UserByIdRolesMutationRequest;
    },
    TContext
  >;
}
