/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  PatchApiV1PostsPremiumByIdMutationRequest,
  PatchApiV1PostsPremiumByIdMutationResponse,
  PatchApiV1PostsPremiumByIdPathParams,
} from "../models/PatchApiV1PostsPremiumById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { patchApiV1PostsPremiumById } from "../clients/patchApiV1PostsPremiumById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchApiV1PostsPremiumByIdMutationKey = () =>
  [{ url: "/api/v1/posts/premium/:id" }] as const;

export type PatchApiV1PostsPremiumByIdMutationKey = ReturnType<
  typeof patchApiV1PostsPremiumByIdMutationKey
>;

export function patchApiV1PostsPremiumByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchApiV1PostsPremiumByIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchApiV1PostsPremiumByIdMutationKey();
  return mutationOptions<
    PatchApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostsPremiumByIdPathParams["id"];
      data: PatchApiV1PostsPremiumByIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchApiV1PostsPremiumById(id, data, config);
    },
  });
}

/**
 * @summary Patch API v1 posts premium by ID
 * {@link /api/v1/posts/premium/:id}
 */
export function usePatchApiV1PostsPremiumById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchApiV1PostsPremiumByIdMutationResponse,
      ResponseErrorConfig<Error>,
      {
        id: PatchApiV1PostsPremiumByIdPathParams["id"];
        data: PatchApiV1PostsPremiumByIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchApiV1PostsPremiumByIdMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchApiV1PostsPremiumByIdMutationKey();

  const baseOptions = patchApiV1PostsPremiumByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostsPremiumByIdPathParams["id"];
      data: PatchApiV1PostsPremiumByIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostsPremiumByIdPathParams["id"];
      data: PatchApiV1PostsPremiumByIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    {
      id: PatchApiV1PostsPremiumByIdPathParams["id"];
      data: PatchApiV1PostsPremiumByIdMutationRequest;
    },
    TContext
  >;
}
