/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PatchApiV1UserByIdMutationRequest, PatchApiV1UserByIdMutationResponse, PatchApiV1UserByIdPathParams } from "../models/PatchApiV1UserById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { patchApiV1UserById } from "../clients/patchApiV1UserById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchApiV1UserByIdMutationKey = () => [{ url: '/api/v1/user/:id' }] as const

export type PatchApiV1UserByIdMutationKey = ReturnType<typeof patchApiV1UserByIdMutationKey>

export function patchApiV1UserByIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PatchApiV1UserByIdMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = patchApiV1UserByIdMutationKey()
        return mutationOptions<PatchApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1UserByIdPathParams["id"], data?: PatchApiV1UserByIdMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return patchApiV1UserById(id, data, config)
          },
        })

}

/**
 * @summary Patch API v1 user by ID
 * {@link /api/v1/user/:id}
 */
export function usePatchApiV1UserById<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1UserByIdPathParams["id"], data?: PatchApiV1UserByIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PatchApiV1UserByIdMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? patchApiV1UserByIdMutationKey()

          const baseOptions = patchApiV1UserByIdMutationOptions(config) as UseMutationOptions<PatchApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1UserByIdPathParams["id"], data?: PatchApiV1UserByIdMutationRequest}, TContext>
          

          return useMutation<PatchApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1UserByIdPathParams["id"], data?: PatchApiV1UserByIdMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PatchApiV1UserByIdMutationResponse, ResponseErrorConfig<Error>, {id: PatchApiV1UserByIdPathParams["id"], data?: PatchApiV1UserByIdMutationRequest}, TContext>
      
}