/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1PostTagMutationRequest,
  PostApiV1PostTagMutationResponse,
} from "../models/PostApiV1PostTag.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { postApiV1PostTag } from "../clients/postApiV1PostTag.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1PostTagMutationKey = () =>
  [{ url: "/api/v1/post/tag/" }] as const;

export type PostApiV1PostTagMutationKey = ReturnType<
  typeof postApiV1PostTagMutationKey
>;

export function postApiV1PostTagMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1PostTagMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postApiV1PostTagMutationKey();
  return mutationOptions<
    PostApiV1PostTagMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1PostTagMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1PostTag(data, config);
    },
  });
}

/**
 * @summary Post API v1 post tag
 * {@link /api/v1/post/tag/}
 */
export function usePostApiV1PostTag<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1PostTagMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PostApiV1PostTagMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostApiV1PostTagMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1PostTagMutationKey();

  const baseOptions = postApiV1PostTagMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1PostTagMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1PostTagMutationRequest },
    TContext
  >;

  return useMutation<
    PostApiV1PostTagMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1PostTagMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1PostTagMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1PostTagMutationRequest },
    TContext
  >;
}
