/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostApiV1CommentMutationRequest, PostApiV1CommentMutationResponse } from "../models/PostApiV1Comment.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { postApiV1Comment } from "../clients/postApiV1Comment.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1CommentMutationKey = () => [{ url: '/api/v1/comment/' }] as const

export type PostApiV1CommentMutationKey = ReturnType<typeof postApiV1CommentMutationKey>

export function postApiV1CommentMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiV1CommentMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postApiV1CommentMutationKey()
        return mutationOptions<PostApiV1CommentMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CommentMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postApiV1Comment(data, config)
          },
        })

}

/**
 * @summary Post API v1 comment
 * {@link /api/v1/comment/}
 */
export function usePostApiV1Comment<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiV1CommentMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CommentMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiV1CommentMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiV1CommentMutationKey()

          const baseOptions = postApiV1CommentMutationOptions(config) as UseMutationOptions<PostApiV1CommentMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CommentMutationRequest}, TContext>
          

          return useMutation<PostApiV1CommentMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CommentMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiV1CommentMutationResponse, ResponseErrorConfig<Error>, {data: PostApiV1CommentMutationRequest}, TContext>
      
}