/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1UserCollegeByIdMutationResponse,
  DeleteApiV1UserCollegeByIdPathParams,
} from "../models/DeleteApiV1UserCollegeById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1UserCollegeByIdUrl(
  id: DeleteApiV1UserCollegeByIdPathParams["id"],
) {
  const res = { method: "DELETE", url: `/api/v1/user/college/${id}` as const };
  return res;
}

/**
 * @summary Delete API v1 user college by ID
 * {@link /api/v1/user/college/:id}
 */
export async function deleteApiV1UserCollegeById(
  id: DeleteApiV1UserCollegeByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1UserCollegeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1UserCollegeByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
