/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1PermissionByIdMutationResponse,
  DeleteApiV1PermissionByIdPathParams,
} from "../models/DeleteApiV1PermissionById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1PermissionByIdUrl(
  id: DeleteApiV1PermissionByIdPathParams["id"],
) {
  const res = { method: "DELETE", url: `/api/v1/permission/${id}` as const };
  return res;
}

/**
 * @summary Delete API v1 permission by ID
 * {@link /api/v1/permission/:id}
 */
export async function deleteApiV1PermissionById(
  id: DeleteApiV1PermissionByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1PermissionByIdMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1PermissionByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
