/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1UserByIdRolesMutationRequest,
  DeleteApiV1UserByIdRolesMutationResponse,
  DeleteApiV1UserByIdRolesPathParams,
} from "../models/DeleteApiV1UserByIdRoles.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1UserByIdRolesUrl(
  id: DeleteApiV1UserByIdRolesPathParams["id"],
) {
  const res = { method: "DELETE", url: `/api/v1/user/${id}/roles` as const };
  return res;
}

/**
 * @summary Delete API v1 user by ID roles
 * {@link /api/v1/user/:id/roles}
 */
export async function deleteApiV1UserByIdRoles(
  id: DeleteApiV1UserByIdRolesPathParams["id"],
  data: DeleteApiV1UserByIdRolesMutationRequest,
  config: Partial<RequestConfig<DeleteApiV1UserByIdRolesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DeleteApiV1UserByIdRolesMutationResponse,
    ResponseErrorConfig<Error>,
    DeleteApiV1UserByIdRolesMutationRequest
  >({
    method: "DELETE",
    url: getDeleteApiV1UserByIdRolesUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
