/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1PostsPremiumByIdMutationResponse,
  DeleteApiV1PostsPremiumByIdPathParams,
} from "../models/DeleteApiV1PostsPremiumById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1PostsPremiumByIdUrl(
  id: DeleteApiV1PostsPremiumByIdPathParams["id"],
) {
  const res = { method: "DELETE", url: `/api/v1/posts/premium/${id}` as const };
  return res;
}

/**
 * @summary Delete API v1 posts premium by ID
 * {@link /api/v1/posts/premium/:id}
 */
export async function deleteApiV1PostsPremiumById(
  id: DeleteApiV1PostsPremiumByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1PostsPremiumByIdMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1PostsPremiumByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
