/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1ContentMutationResponse,
  DeleteApiV1ContentQueryParams,
} from "../models/DeleteApiV1Content.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1ContentUrl() {
  const res = { method: "DELETE", url: `/api/v1/content` as const };
  return res;
}

/**
 * @summary Delete API v1 content
 * {@link /api/v1/content}
 */
export async function deleteApiV1Content(
  params: DeleteApiV1ContentQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1ContentMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1ContentUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
