/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1SportByIdMutationResponse, DeleteApiV1SportByIdPathParams } from "../models/DeleteApiV1SportById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1SportByIdUrl(id: DeleteApiV1SportByIdPathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/v1/sport/${id}` as const }
  return res
}

/**
 * @summary Delete API v1 sport by ID
 * {@link /api/v1/sport/:id}
 */
export async function deleteApiV1SportById(id: DeleteApiV1SportByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteApiV1SportByIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteApiV1SportByIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}