/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1PostByIdMutationResponse, DeleteApiV1PostByIdPathParams } from "../models/DeleteApiV1PostById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1PostByIdUrl(id: DeleteApiV1PostByIdPathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/v1/post/${id}` as const }
  return res
}

/**
 * @summary Delete API v1 post by ID
 * {@link /api/v1/post/:id}
 */
export async function deleteApiV1PostById(id: DeleteApiV1PostByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteApiV1PostByIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteApiV1PostByIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}