/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type { DeleteApiV1StripeProductByIdMutationResponse } from "../models/DeleteApiV1StripeProductById.ts";

function getDeleteApiV1StripeProductByIdUrl() {
  const res = {
    method: "DELETE",
    url: `/api/v1/stripe_product/${id}` as const,
  };
  return res;
}

/**
 * @summary Delete API v1 stripe product by ID
 * {@link /api/v1/stripe_product/:id}
 */
export async function deleteApiV1StripeProductById(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1StripeProductByIdMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1StripeProductByIdUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
