/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1CommentLikeByIdMutationResponse,
  DeleteApiV1CommentLikeByIdPathParams,
} from "../models/DeleteApiV1CommentLikeById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1CommentLikeByIdUrl(
  id: DeleteApiV1CommentLikeByIdPathParams["id"],
) {
  const res = { method: "DELETE", url: `/api/v1/comment/like/${id}` as const };
  return res;
}

/**
 * @summary Delete API v1 comment like by ID
 * {@link /api/v1/comment/like/:id}
 */
export async function deleteApiV1CommentLikeById(
  id: DeleteApiV1CommentLikeByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1CommentLikeByIdMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1CommentLikeByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
