/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteApiV1UserSportByIdMutationResponse,
  DeleteApiV1UserSportByIdPathParams,
} from "../models/DeleteApiV1UserSportById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDeleteApiV1UserSportByIdUrl(
  id: DeleteApiV1UserSportByIdPathParams["id"],
) {
  const res = { method: "DELETE", url: `/api/v1/user/sport/${id}` as const };
  return res;
}

/**
 * @summary Delete API v1 user sport by ID
 * {@link /api/v1/user/sport/:id}
 */
export async function deleteApiV1UserSportById(
  id: DeleteApiV1UserSportByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1UserSportByIdMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1UserSportByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
