/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserCollegeByCollegeIdUsersQueryResponse,
  GetApiV1UserCollegeByCollegeIdUsersPathParams,
} from "../models/GetApiV1UserCollegeByCollegeIdUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1UserCollegeByCollegeIdUsersUrl(
  college_id: GetApiV1UserCollegeByCollegeIdUsersPathParams["college_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/user/college/${college_id}/users` as const,
  };
  return res;
}

/**
 * @summary Get API v1 user college by college ID users
 * {@link /api/v1/user/college/:college_id/users}
 */
export async function getApiV1UserCollegeByCollegeIdUsers(
  college_id: GetApiV1UserCollegeByCollegeIdUsersPathParams["college_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1UserCollegeByCollegeIdUsersQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1UserCollegeByCollegeIdUsersUrl(college_id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
