/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
  GetApiV1PostsPremiumByAuthorByAuthorIdPathParams,
  GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams,
} from "../models/GetApiV1PostsPremiumByAuthorByAuthorId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsPremiumByAuthorByAuthorIdUrl(
  author_id: GetApiV1PostsPremiumByAuthorByAuthorIdPathParams["author_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/posts/premium/by-author/${author_id}` as const,
  };
  return res;
}

/**
 * @summary Get API v1 posts premium by author by author ID
 * {@link /api/v1/posts/premium/by-author/:author_id}
 */
export async function getApiV1PostsPremiumByAuthorByAuthorId(
  author_id: GetApiV1PostsPremiumByAuthorByAuthorIdPathParams["author_id"],
  params?: GetApiV1PostsPremiumByAuthorByAuthorIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostsPremiumByAuthorByAuthorIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostsPremiumByAuthorByAuthorIdUrl(author_id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
