/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserTagByTagIdUsersQueryResponse,
  GetApiV1UserTagByTagIdUsersPathParams,
} from "../models/GetApiV1UserTagByTagIdUsers.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1UserTagByTagIdUsersUrl(
  tag_id: GetApiV1UserTagByTagIdUsersPathParams["tag_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/user/tag/${tag_id}/users` as const,
  };
  return res;
}

/**
 * @summary Get API v1 user tag by tag ID users
 * {@link /api/v1/user/tag/:tag_id/users}
 */
export async function getApiV1UserTagByTagIdUsers(
  tag_id: GetApiV1UserTagByTagIdUsersPathParams["tag_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1UserTagByTagIdUsersQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1UserTagByTagIdUsersUrl(tag_id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
