/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumByTagByTagIdQueryResponse,
  GetApiV1PostsPremiumByTagByTagIdPathParams,
  GetApiV1PostsPremiumByTagByTagIdQueryParams,
} from "../models/GetApiV1PostsPremiumByTagByTagId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsPremiumByTagByTagIdUrl(
  tag_id: GetApiV1PostsPremiumByTagByTagIdPathParams["tag_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/posts/premium/by-tag/${tag_id}` as const,
  };
  return res;
}

/**
 * @summary Get API v1 posts premium by tag by tag ID
 * {@link /api/v1/posts/premium/by-tag/:tag_id}
 */
export async function getApiV1PostsPremiumByTagByTagId(
  tag_id: GetApiV1PostsPremiumByTagByTagIdPathParams["tag_id"],
  params?: GetApiV1PostsPremiumByTagByTagIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostsPremiumByTagByTagIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostsPremiumByTagByTagIdUrl(tag_id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
