/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumByCollegeByCollegeIdQueryResponse,
  GetApiV1PostsPremiumByCollegeByCollegeIdPathParams,
  GetApiV1PostsPremiumByCollegeByCollegeIdQueryParams,
} from "../models/GetApiV1PostsPremiumByCollegeByCollegeId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsPremiumByCollegeByCollegeIdUrl(
  college_id: GetApiV1PostsPremiumByCollegeByCollegeIdPathParams["college_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/posts/premium/by-college/${college_id}` as const,
  };
  return res;
}

/**
 * @summary Get API v1 posts premium by college by college ID
 * {@link /api/v1/posts/premium/by-college/:college_id}
 */
export async function getApiV1PostsPremiumByCollegeByCollegeId(
  college_id: GetApiV1PostsPremiumByCollegeByCollegeIdPathParams["college_id"],
  params?: GetApiV1PostsPremiumByCollegeByCollegeIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostsPremiumByCollegeByCollegeIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostsPremiumByCollegeByCollegeIdUrl(
      college_id,
    ).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
