/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1CollegesQueryResponse,
  GetApiV1CollegesQueryParams,
} from "../models/GetApiV1Colleges.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1CollegesUrl() {
  const res = { method: "GET", url: `/api/v1/colleges/` as const };
  return res;
}

/**
 * @summary Get API v1 colleges
 * {@link /api/v1/colleges/}
 */
export async function getApiV1Colleges(
  params?: GetApiV1CollegesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1CollegesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1CollegesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
