/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserCollegeByUserIdFollowsQueryResponse,
  GetApiV1UserCollegeByUserIdFollowsPathParams,
} from "../models/GetApiV1UserCollegeByUserIdFollows.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1UserCollegeByUserIdFollowsUrl(
  user_id: GetApiV1UserCollegeByUserIdFollowsPathParams["user_id"],
) {
  void user_id;
  const res = {
    method: "GET",
    url: `/api/v1/user/college/follows` as const,
  };
  return res;
}

/**
 * @summary Get API v1 user college by user ID follows
 * {@link /api/v1/user/college/:user_id/follows}
 */
export async function getApiV1UserCollegeByUserIdFollows(
  user_id: GetApiV1UserCollegeByUserIdFollowsPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1UserCollegeByUserIdFollowsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1UserCollegeByUserIdFollowsUrl(user_id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
