/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1StripeCustomersByIdQueryResponse,
  GetApiV1StripeCustomersByIdPathParams,
} from "../models/GetApiV1StripeCustomersById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1StripeCustomersByIdUrl(
  id: GetApiV1StripeCustomersByIdPathParams["id"],
) {
  const res = { method: "GET", url: `/api/v1/stripe_customers/${id}` as const };
  return res;
}

/**
 * @summary Get API v1 stripe customers by ID
 * {@link /api/v1/stripe_customers/:id}
 */
export async function getApiV1StripeCustomersById(
  id: GetApiV1StripeCustomersByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1StripeCustomersByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1StripeCustomersByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
