/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumBySportBySportIdQueryResponse,
  GetApiV1PostsPremiumBySportBySportIdPathParams,
  GetApiV1PostsPremiumBySportBySportIdQueryParams,
} from "../models/GetApiV1PostsPremiumBySportBySportId.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsPremiumBySportBySportIdUrl(
  sport_id: GetApiV1PostsPremiumBySportBySportIdPathParams["sport_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/posts/premium/by-sport/${sport_id}` as const,
  };
  return res;
}

/**
 * @summary Get API v1 posts premium by sport by sport ID
 * {@link /api/v1/posts/premium/by-sport/:sport_id}
 */
export async function getApiV1PostsPremiumBySportBySportId(
  sport_id: GetApiV1PostsPremiumBySportBySportIdPathParams["sport_id"],
  params?: GetApiV1PostsPremiumBySportBySportIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostsPremiumBySportBySportIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostsPremiumBySportBySportIdUrl(sport_id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
