/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1UserCollegeFollowsQueryResponse } from "../models/GetApiV1UserCollegeFollows.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1UserCollegeFollowsUrl() {
  const res = { method: "GET", url: `/api/v1/user/college/follows` as const };
  return res;
}

/**
 * @summary Get API v1 user college follows
 * {@link /api/v1/user/college/follows}
 */
export async function getApiV1UserCollegeFollows(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1UserCollegeFollowsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1UserCollegeFollowsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
