/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1SportsQueryResponse, GetApiV1SportsQueryParams } from "../models/GetApiV1Sports.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetApiV1SportsUrl() {
  const res = { method: 'GET', url: `/api/v1/sports/` as const }
  return res
}

/**
 * @summary Get API v1 sports
 * {@link /api/v1/sports/}
 */
export async function getApiV1Sports(params?: GetApiV1SportsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiV1SportsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiV1SportsUrl().url.toString(), params, ... requestConfig })
  return res.data
}