/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1TagByTagIdPostsQueryResponse,
  GetApiV1TagByTagIdPostsPathParams,
  GetApiV1TagByTagIdPostsQueryParams,
} from "../models/GetApiV1TagByTagIdPosts.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1TagByTagIdPostsUrl(
  tag_id: GetApiV1TagByTagIdPostsPathParams["tag_id"],
) {
  const res = { method: "GET", url: `/api/v1/tag/${tag_id}/posts` as const };
  return res;
}

/**
 * @summary Get API v1 tag by tag ID posts
 * {@link /api/v1/tag/:tag_id/posts}
 */
export async function getApiV1TagByTagIdPosts(
  tag_id: GetApiV1TagByTagIdPostsPathParams["tag_id"],
  params?: GetApiV1TagByTagIdPostsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1TagByTagIdPostsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1TagByTagIdPostsUrl(tag_id).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
