/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1SportByNameByNameQueryResponse, GetApiV1SportByNameByNamePathParams } from "../models/GetApiV1SportByNameByName.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetApiV1SportByNameByNameUrl(name: GetApiV1SportByNameByNamePathParams["name"]) {
  const res = { method: 'GET', url: `/api/v1/sport/by-name/${name}` as const }
  return res
}

/**
 * @summary Get API v1 sport by name by name
 * {@link /api/v1/sport/by-name/:name}
 */
export async function getApiV1SportByNameByName(name: GetApiV1SportByNameByNamePathParams["name"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiV1SportByNameByNameQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiV1SportByNameByNameUrl(name).url.toString(), ... requestConfig })
  return res.data
}