/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1SportsSearchQueryResponse,
  GetApiV1SportsSearchQueryParams,
} from "../models/GetApiV1SportsSearch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1SportsSearchUrl() {
  const res = { method: "GET", url: `/api/v1/sports/search` as const };
  return res;
}

/**
 * @summary Get API v1 sports search
 * {@link /api/v1/sports/search}
 */
export async function getApiV1SportsSearch(
  params?: GetApiV1SportsSearchQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1SportsSearchQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1SportsSearchUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
