/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPopularQueryResponse,
  GetApiV1PostsPopularQueryParams,
} from "../models/GetApiV1PostsPopular.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsPopularUrl() {
  const res = { method: "GET", url: `/api/v1/posts/popular` as const };
  return res;
}

/**
 * @summary Get API v1 posts popular
 * {@link /api/v1/posts/popular}
 */
export async function getApiV1PostsPopular(
  params?: GetApiV1PostsPopularQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostsPopularQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostsPopularUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
