/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostLikeByPostIdLikesQueryResponse,
  GetApiV1PostLikeByPostIdLikesPathParams,
} from "../models/GetApiV1PostLikeByPostIdLikes.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostLikeByPostIdLikesUrl(
  post_id: GetApiV1PostLikeByPostIdLikesPathParams["post_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/post/like/${post_id}/likes` as const,
  };
  return res;
}

/**
 * @summary Get API v1 post like by post ID likes
 * {@link /api/v1/post/like/:post_id/likes}
 */
export async function getApiV1PostLikeByPostIdLikes(
  post_id: GetApiV1PostLikeByPostIdLikesPathParams["post_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostLikeByPostIdLikesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostLikeByPostIdLikesUrl(post_id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
