/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostByIdQueryResponse,
  GetApiV1PostByIdPathParams,
} from "../models/GetApiV1PostById.ts";

function getGetApiV1PostByIdUrl(id: GetApiV1PostByIdPathParams["id"]) {
  const res = { method: "GET", url: `/api/v1/post/${id}` as const };
  return res;
}

/**
 * @summary Get API v1 post by ID
 * {@link /api/v1/post/:id}
 */
export async function getApiV1PostById(
  id: GetApiV1PostByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
