/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1PostTagByIdQueryResponse, GetApiV1PostTagByIdPathParams } from "../models/GetApiV1PostTagById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostTagByIdUrl(id: GetApiV1PostTagByIdPathParams["id"]) {
  const res = { method: 'GET', url: `/api/v1/post/tag/${id}` as const }
  return res
}

/**
 * @summary Get API v1 post tag by ID
 * {@link /api/v1/post/tag/:id}
 */
export async function getApiV1PostTagById(id: GetApiV1PostTagByIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiV1PostTagByIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiV1PostTagByIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}