/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetApiV1PostsByAuthorByAuthorIdQueryResponse, GetApiV1PostsByAuthorByAuthorIdPathParams, GetApiV1PostsByAuthorByAuthorIdQueryParams } from "../models/GetApiV1PostsByAuthorByAuthorId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsByAuthorByAuthorIdUrl(author_id: GetApiV1PostsByAuthorByAuthorIdPathParams["author_id"]) {
  const res = { method: 'GET', url: `/api/v1/posts/by-author/${author_id}` as const }
  return res
}

/**
 * @summary Get API v1 posts by author by author ID
 * {@link /api/v1/posts/by-author/:author_id}
 */
export async function getApiV1PostsByAuthorByAuthorId(author_id: GetApiV1PostsByAuthorByAuthorIdPathParams["author_id"], params?: GetApiV1PostsByAuthorByAuthorIdQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiV1PostsByAuthorByAuthorIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiV1PostsByAuthorByAuthorIdUrl(author_id).url.toString(), params, ... requestConfig })
  return res.data
}