/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1CommentByIdQueryResponse,
  GetApiV1CommentByIdPathParams,
} from "../models/GetApiV1CommentById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1CommentByIdUrl(id: GetApiV1CommentByIdPathParams["id"]) {
  const res = { method: "GET", url: `/api/v1/comment/${id}` as const };
  return res;
}

/**
 * @summary Get API v1 comment by ID
 * {@link /api/v1/comment/:id}
 */
export async function getApiV1CommentById(
  id: GetApiV1CommentByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1CommentByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1CommentByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
