/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1MediaByIdQueryResponse,
  GetApiV1MediaByIdPathParams,
} from "../models/GetApiV1MediaById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1MediaByIdUrl(id: GetApiV1MediaByIdPathParams["id"]) {
  const res = { method: "GET", url: `/api/v1/media/${id}` as const };
  return res;
}

/**
 * @summary Get API v1 media by ID
 * {@link /api/v1/media/:id}
 */
export async function getApiV1MediaById(
  id: GetApiV1MediaByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1MediaByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1MediaByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
