/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostLikeByIdQueryResponse,
  GetApiV1PostLikeByIdPathParams,
} from "../models/GetApiV1PostLikeById.ts";

function getGetApiV1PostLikeByIdUrl(id: GetApiV1PostLikeByIdPathParams["id"]) {
  const res = { method: "GET", url: `/api/v1/post/like/${id}` as const };
  return res;
}

/**
 * @summary Get API v1 post like by ID
 * {@link /api/v1/post/like/:id}
 */
export async function getApiV1PostLikeById(
  id: GetApiV1PostLikeByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostLikeByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostLikeByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
