/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1UserSportByUserIdFollowsQueryResponse,
  GetApiV1UserSportByUserIdFollowsPathParams,
} from "../models/GetApiV1UserSportByUserIdFollows.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1UserSportByUserIdFollowsUrl(
  user_id: GetApiV1UserSportByUserIdFollowsPathParams["user_id"],
) {
  const res = {
    method: "GET",
    url: `/api/v1/user/sport/${user_id}/follows` as const,
  };
  return res;
}

/**
 * @summary Get API v1 user sport by user ID follows
 * {@link /api/v1/user/sport/:user_id/follows}
 */
export async function getApiV1UserSportByUserIdFollows(
  user_id: GetApiV1UserSportByUserIdFollowsPathParams["user_id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1UserSportByUserIdFollowsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1UserSportByUserIdFollowsUrl(user_id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
