/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PermissionByIdQueryResponse,
  GetApiV1PermissionByIdPathParams,
} from "../models/GetApiV1PermissionById.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PermissionByIdUrl(
  id: GetApiV1PermissionByIdPathParams["id"],
) {
  const res = { method: "GET", url: `/api/v1/permission/${id}` as const };
  return res;
}

/**
 * @summary Get API v1 permission by ID
 * {@link /api/v1/permission/:id}
 */
export async function getApiV1PermissionById(
  id: GetApiV1PermissionByIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PermissionByIdQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PermissionByIdUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
