/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1CollegesSearchQueryResponse,
  GetApiV1CollegesSearchQueryParams,
} from "../models/GetApiV1CollegesSearch.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1CollegesSearchUrl() {
  const res = { method: "GET", url: `/api/v1/colleges/search` as const };
  return res;
}

/**
 * @summary Get API v1 colleges search
 * {@link /api/v1/colleges/search}
 */
export async function getApiV1CollegesSearch(
  params?: GetApiV1CollegesSearchQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1CollegesSearchQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1CollegesSearchUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
