/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1SurveyAveragesQueryResponse,
  GetApiV1SurveyAveragesQueryParams,
} from "../models/GetApiV1SurveyAverages.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1SurveyAveragesUrl() {
  const res = { method: "GET", url: `/api/v1/survey/averages` as const };
  return res;
}

/**
 * @summary Get API v1 survey averages
 * {@link /api/v1/survey/averages}
 */
export async function getApiV1SurveyAverages(
  params?: GetApiV1SurveyAveragesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1SurveyAveragesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1SurveyAveragesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
