/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetApiV1PostsPremiumFilterQueryResponse,
  GetApiV1PostsPremiumFilterQueryParams,
} from "../models/GetApiV1PostsPremiumFilter.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getGetApiV1PostsPremiumFilterUrl() {
  const res = { method: "GET", url: `/api/v1/posts/premium/filter` as const };
  return res;
}

/**
 * @summary Get API v1 posts premium filter
 * {@link /api/v1/posts/premium/filter}
 */
export async function getApiV1PostsPremiumFilter(
  params?: GetApiV1PostsPremiumFilterQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1PostsPremiumFilterQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1PostsPremiumFilterUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
