/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type { ListApiV1StripeProductsQueryResponse } from "../models/ListApiV1StripeProducts.ts";

function getListApiV1StripeProductsUrl() {
  const res = { method: "GET", url: `/api/v1/stripe_products/` as const };
  return res;
}

/**
 * @summary List API v1 stripe products
 * {@link /api/v1/stripe_products/}
 */
export async function listApiV1StripeProducts(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListApiV1StripeProductsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getListApiV1StripeProductsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
