/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ListApiV1CheckoutSessionsQueryResponse,
  ListApiV1CheckoutSessionsQueryParams,
} from "../models/ListApiV1CheckoutSessions.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getListApiV1CheckoutSessionsUrl() {
  const res = { method: "GET", url: `/api/v1/checkout/sessions/` as const };
  return res;
}

/**
 * @summary List API v1 checkout sessions
 * {@link /api/v1/checkout/sessions/}
 */
export async function listApiV1CheckoutSessions(
  params?: ListApiV1CheckoutSessionsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListApiV1CheckoutSessionsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getListApiV1CheckoutSessionsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
