/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  PatchApiV1CommentByIdMutationRequest,
  PatchApiV1CommentByIdMutationResponse,
  PatchApiV1CommentByIdPathParams,
} from "../models/PatchApiV1CommentById.ts";

function getPatchApiV1CommentByIdUrl(
  id: PatchApiV1CommentByIdPathParams["id"],
) {
  const res = { method: "PATCH", url: `/api/v1/comment/${id}` as const };
  return res;
}

/**
 * @summary Patch API v1 comment by ID
 * {@link /api/v1/comment/:id}
 */
export async function patchApiV1CommentById(
  id: PatchApiV1CommentByIdPathParams["id"],
  data: PatchApiV1CommentByIdMutationRequest,
  config: Partial<RequestConfig<PatchApiV1CommentByIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchApiV1CommentByIdMutationResponse,
    ResponseErrorConfig<Error>,
    PatchApiV1CommentByIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchApiV1CommentByIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
