/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PatchApiV1PostByIdMutationRequest, PatchApiV1PostByIdMutationResponse, PatchApiV1PostByIdPathParams } from "../models/PatchApiV1PostById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getPatchApiV1PostByIdUrl(id: PatchApiV1PostByIdPathParams["id"]) {
  const res = { method: 'PATCH', url: `/api/v1/post/${id}` as const }
  return res
}

/**
 * @summary Patch API v1 post by ID
 * {@link /api/v1/post/:id}
 */
export async function patchApiV1PostById(id: PatchApiV1PostByIdPathParams["id"], data?: PatchApiV1PostByIdMutationRequest, config: Partial<RequestConfig<PatchApiV1PostByIdMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PatchApiV1PostByIdMutationResponse, ResponseErrorConfig<Error>, PatchApiV1PostByIdMutationRequest>({ method : "PATCH", url : getPatchApiV1PostByIdUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}