/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PatchApiV1TagByIdMutationRequest, PatchApiV1TagByIdMutationResponse, PatchApiV1TagByIdPathParams } from "../models/PatchApiV1TagById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getPatchApiV1TagByIdUrl(id: PatchApiV1TagByIdPathParams["id"]) {
  const res = { method: 'PATCH', url: `/api/v1/tag/${id}` as const }
  return res
}

/**
 * @summary Patch API v1 tag by ID
 * {@link /api/v1/tag/:id}
 */
export async function patchApiV1TagById(id: PatchApiV1TagByIdPathParams["id"], data: PatchApiV1TagByIdMutationRequest, config: Partial<RequestConfig<PatchApiV1TagByIdMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PatchApiV1TagByIdMutationResponse, ResponseErrorConfig<Error>, PatchApiV1TagByIdMutationRequest>({ method : "PATCH", url : getPatchApiV1TagByIdUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}