/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1PostMutationRequest,
  PostApiV1PostMutationResponse,
} from "../models/PostApiV1Post.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getPostApiV1PostUrl() {
  const res = { method: "POST", url: `/api/v1/post/` as const };
  return res;
}

/**
 * @summary Post API v1 post
 * {@link /api/v1/post/}
 */
export async function postApiV1Post(
  data: PostApiV1PostMutationRequest,
  config: Partial<RequestConfig<PostApiV1PostMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1PostMutationResponse,
    ResponseErrorConfig<Error>,
    PostApiV1PostMutationRequest
  >({
    method: "POST",
    url: getPostApiV1PostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
