/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostApiV1SportMutationRequest, PostApiV1SportMutationResponse } from "../models/PostApiV1Sport.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getPostApiV1SportUrl() {
  const res = { method: 'POST', url: `/api/v1/sport/` as const }
  return res
}

/**
 * @summary Post API v1 sport
 * {@link /api/v1/sport/}
 */
export async function postApiV1Sport(data: PostApiV1SportMutationRequest, config: Partial<RequestConfig<PostApiV1SportMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostApiV1SportMutationResponse, ResponseErrorConfig<Error>, PostApiV1SportMutationRequest>({ method : "POST", url : getPostApiV1SportUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}