/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PostApiV1TagMutationRequest, PostApiV1TagMutationResponse } from "../models/PostApiV1Tag.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getPostApiV1TagUrl() {
  const res = { method: 'POST', url: `/api/v1/tag/` as const }
  return res
}

/**
 * @summary Post API v1 tag
 * {@link /api/v1/tag/}
 */
export async function postApiV1Tag(data: PostApiV1TagMutationRequest, config: Partial<RequestConfig<PostApiV1TagMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostApiV1TagMutationResponse, ResponseErrorConfig<Error>, PostApiV1TagMutationRequest>({ method : "POST", url : getPostApiV1TagUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}