/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1UserCollegeMutationRequest,
  PostApiV1UserCollegeMutationResponse,
} from "../models/PostApiV1UserCollege.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getPostApiV1UserCollegeUrl() {
  const res = { method: "POST", url: `/api/v1/user/college/` as const };
  return res;
}

/**
 * @summary Post API v1 user college
 * {@link /api/v1/user/college/}
 */
export async function postApiV1UserCollege(
  data: PostApiV1UserCollegeMutationRequest,
  config: Partial<RequestConfig<PostApiV1UserCollegeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1UserCollegeMutationResponse,
    ResponseErrorConfig<Error>,
    PostApiV1UserCollegeMutationRequest
  >({
    method: "POST",
    url: getPostApiV1UserCollegeUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
