/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1RoleBasicMutationRequest,
  PostApiV1RoleBasicMutationResponse,
} from "../models/PostApiV1RoleBasic.ts";

function getPostApiV1RoleBasicUrl() {
  const res = { method: "POST", url: `/api/v1/role/basic` as const };
  return res;
}

/**
 * @summary Post API v1 role basic
 * {@link /api/v1/role/basic}
 */
export async function postApiV1RoleBasic(
  data: PostApiV1RoleBasicMutationRequest,
  config: Partial<RequestConfig<PostApiV1RoleBasicMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1RoleBasicMutationResponse,
    ResponseErrorConfig<Error>,
    PostApiV1RoleBasicMutationRequest
  >({
    method: "POST",
    url: getPostApiV1RoleBasicUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
