/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostApiV1ContentConfirmUploadMutationRequest,
  PostApiV1ContentConfirmUploadMutationResponse,
} from "../models/PostApiV1ContentConfirmUpload.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getPostApiV1ContentConfirmUploadUrl() {
  const res = {
    method: "POST",
    url: `/api/v1/content/confirm-upload` as const,
  };
  return res;
}

/**
 * @summary Post API v1 content confirm upload
 * {@link /api/v1/content/confirm-upload}
 */
export async function postApiV1ContentConfirmUpload(
  data: PostApiV1ContentConfirmUploadMutationRequest,
  config: Partial<
    RequestConfig<PostApiV1ContentConfirmUploadMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1ContentConfirmUploadMutationResponse,
    ResponseErrorConfig<Error>,
    PostApiV1ContentConfirmUploadMutationRequest
  >({
    method: "POST",
    url: getPostApiV1ContentConfirmUploadUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
