/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { PutApiV1CollegeByIdMutationRequest, PutApiV1CollegeByIdMutationResponse, PutApiV1CollegeByIdPathParams } from "../models/PutApiV1CollegeById.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getPutApiV1CollegeByIdUrl(id: PutApiV1CollegeByIdPathParams["id"]) {
  const res = { method: 'PUT', url: `/api/v1/college/${id}` as const }
  return res
}

/**
 * @summary Put API v1 college by ID
 * {@link /api/v1/college/:id}
 */
export async function putApiV1CollegeById(id: PutApiV1CollegeByIdPathParams["id"], data: PutApiV1CollegeByIdMutationRequest, config: Partial<RequestConfig<PutApiV1CollegeByIdMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PutApiV1CollegeByIdMutationResponse, ResponseErrorConfig<Error>, PutApiV1CollegeByIdMutationRequest>({ method : "PUT", url : getPutApiV1CollegeByIdUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}