export type { DeleteApiV1CollegeByIdMutationKey } from "./hooks/useDeleteApiV1CollegeById.ts";
export type { DeleteApiV1SportByIdMutationKey } from "./hooks/useDeleteApiV1SportById.ts";
export type { DeleteApiV1UserByIdMutationKey } from "./hooks/useDeleteApiV1UserById.ts";
export type { GetApiV1CollegeByIdQueryKey } from "./hooks/useGetApiV1CollegeById.ts";
export type { GetApiV1CollegeByIdSuspenseQueryKey } from "./hooks/useGetApiV1CollegeByIdSuspense.ts";
export type { GetApiV1HealthQueryKey } from "./hooks/useGetApiV1Health.ts";
export type { GetApiV1HealthHealthcheckQueryKey } from "./hooks/useGetApiV1HealthHealthcheck.ts";
export type { GetApiV1HealthHealthcheckSuspenseQueryKey } from "./hooks/useGetApiV1HealthHealthcheckSuspense.ts";
export type { GetApiV1HealthSuspenseQueryKey } from "./hooks/useGetApiV1HealthSuspense.ts";
export type { GetApiV1SportByIdQueryKey } from "./hooks/useGetApiV1SportById.ts";
export type { GetApiV1SportByIdSuspenseQueryKey } from "./hooks/useGetApiV1SportByIdSuspense.ts";
export type { GetApiV1SportByNameByNameQueryKey } from "./hooks/useGetApiV1SportByNameByName.ts";
export type { GetApiV1SportByNameByNameSuspenseQueryKey } from "./hooks/useGetApiV1SportByNameByNameSuspense.ts";
export type { GetApiV1SportsQueryKey } from "./hooks/useGetApiV1Sports.ts";
export type { GetApiV1SportsSuspenseQueryKey } from "./hooks/useGetApiV1SportsSuspense.ts";
export type { GetApiV1UserByIdQueryKey } from "./hooks/useGetApiV1UserById.ts";
export type { GetApiV1UserByIdSuspenseQueryKey } from "./hooks/useGetApiV1UserByIdSuspense.ts";
export type { GetApiV1UserCurrentQueryKey } from "./hooks/useGetApiV1UserCurrent.ts";
export type { GetApiV1UserCurrentSuspenseQueryKey } from "./hooks/useGetApiV1UserCurrentSuspense.ts";
export type { PatchApiV1SportByIdMutationKey } from "./hooks/usePatchApiV1SportById.ts";
export type { PatchApiV1UserByIdMutationKey } from "./hooks/usePatchApiV1UserById.ts";
export type { PostApiV1CollegeMutationKey } from "./hooks/usePostApiV1College.ts";
export type { PostApiV1SportMutationKey } from "./hooks/usePostApiV1Sport.ts";
export type { PostApiV1UserMutationKey } from "./hooks/usePostApiV1User.ts";
export type { PutApiV1CollegeByIdMutationKey } from "./hooks/usePutApiV1CollegeById.ts";
export type { CreateCollegeRequest } from "./models/CreateCollegeRequest.ts";
export type { CreateCollegeResponse } from "./models/CreateCollegeResponse.ts";
export type { CreateSportRequest } from "./models/CreateSportRequest.ts";
export type { CreateUserBody } from "./models/CreateUserBody.ts";
export type { CreateUserResponse } from "./models/CreateUserResponse.ts";
export type { DeleteApiV1CollegeByIdPathParams, DeleteApiV1CollegeById200, DeleteApiV1CollegeByIdError, DeleteApiV1CollegeByIdMutationResponse, DeleteApiV1CollegeByIdMutation } from "./models/DeleteApiV1CollegeById.ts";
export type { DeleteApiV1SportByIdPathParams, DeleteApiV1SportById200, DeleteApiV1SportByIdError, DeleteApiV1SportByIdMutationResponse, DeleteApiV1SportByIdMutation } from "./models/DeleteApiV1SportById.ts";
export type { DeleteApiV1UserByIdPathParams, DeleteApiV1UserById200, DeleteApiV1UserByIdError, DeleteApiV1UserByIdMutationResponse, DeleteApiV1UserByIdMutation } from "./models/DeleteApiV1UserById.ts";
export type { DeleteCollegeResponse } from "./models/DeleteCollegeResponse.ts";
export type { DeleteUserResponse } from "./models/DeleteUserResponse.ts";
export type { ErrorDetail } from "./models/ErrorDetail.ts";
export type { ErrorModel } from "./models/ErrorModel.ts";
export type { GetAllSportsResponse } from "./models/GetAllSportsResponse.ts";
export type { GetApiV1CollegeByIdPathParams, GetApiV1CollegeById200, GetApiV1CollegeByIdError, GetApiV1CollegeByIdQueryResponse, GetApiV1CollegeByIdQuery } from "./models/GetApiV1CollegeById.ts";
export type { GetApiV1Health200, GetApiV1HealthError, GetApiV1HealthQueryResponse, GetApiV1HealthQuery } from "./models/GetApiV1Health.ts";
export type { GetApiV1HealthHealthcheck200, GetApiV1HealthHealthcheckError, GetApiV1HealthHealthcheckQueryResponse, GetApiV1HealthHealthcheckQuery } from "./models/GetApiV1HealthHealthcheck.ts";
export type { GetApiV1SportByIdPathParams, GetApiV1SportById200, GetApiV1SportByIdError, GetApiV1SportByIdQueryResponse, GetApiV1SportByIdQuery } from "./models/GetApiV1SportById.ts";
export type { GetApiV1SportByNameByNamePathParams, GetApiV1SportByNameByName200, GetApiV1SportByNameByNameError, GetApiV1SportByNameByNameQueryResponse, GetApiV1SportByNameByNameQuery } from "./models/GetApiV1SportByNameByName.ts";
export type { GetApiV1SportsQueryParams, GetApiV1Sports200, GetApiV1SportsError, GetApiV1SportsQueryResponse, GetApiV1SportsQuery } from "./models/GetApiV1Sports.ts";
export type { GetApiV1UserByIdPathParams, GetApiV1UserById200, GetApiV1UserByIdError, GetApiV1UserByIdQueryResponse, GetApiV1UserByIdQuery } from "./models/GetApiV1UserById.ts";
export type { GetApiV1UserCurrent200, GetApiV1UserCurrentError, GetApiV1UserCurrentQueryResponse, GetApiV1UserCurrentQuery } from "./models/GetApiV1UserCurrent.ts";
export type { GetCollegeResponse } from "./models/GetCollegeResponse.ts";
export type { GetCurrentUserIDResponse } from "./models/GetCurrentUserIDResponse.ts";
export type { GetUserResponse } from "./models/GetUserResponse.ts";
export type { HealthResponse } from "./models/HealthResponse.ts";
export type { PatchApiV1SportByIdPathParams, PatchApiV1SportById200, PatchApiV1SportByIdError, PatchApiV1SportByIdMutationRequest, PatchApiV1SportByIdMutationResponse, PatchApiV1SportByIdMutation } from "./models/PatchApiV1SportById.ts";
export type { PatchApiV1UserByIdPathParams, PatchApiV1UserById200, PatchApiV1UserByIdError, PatchApiV1UserByIdMutationRequest, PatchApiV1UserByIdMutationResponse, PatchApiV1UserByIdMutation } from "./models/PatchApiV1UserById.ts";
export type { PostApiV1College200, PostApiV1CollegeError, PostApiV1CollegeMutationRequest, PostApiV1CollegeMutationResponse, PostApiV1CollegeMutation } from "./models/PostApiV1College.ts";
export type { PostApiV1Sport200, PostApiV1SportError, PostApiV1SportMutationRequest, PostApiV1SportMutationResponse, PostApiV1SportMutation } from "./models/PostApiV1Sport.ts";
export type { PostApiV1User200, PostApiV1UserError, PostApiV1UserMutationRequest, PostApiV1UserMutationResponse, PostApiV1UserMutation } from "./models/PostApiV1User.ts";
export type { PutApiV1CollegeByIdPathParams, PutApiV1CollegeById200, PutApiV1CollegeByIdError, PutApiV1CollegeByIdMutationRequest, PutApiV1CollegeByIdMutationResponse, PutApiV1CollegeByIdMutation } from "./models/PutApiV1CollegeById.ts";
export type { SportResponse } from "./models/SportResponse.ts";
export type { UpdateCollegeRequest } from "./models/UpdateCollegeRequest.ts";
export type { UpdateCollegeResponse } from "./models/UpdateCollegeResponse.ts";
export type { UpdateSportRequest } from "./models/UpdateSportRequest.ts";
export type { UpdateUserBody } from "./models/UpdateUserBody.ts";
export type { UpdateUserResponse } from "./models/UpdateUserResponse.ts";
export { deleteApiV1CollegeById } from "./clients/deleteApiV1CollegeById.ts";
export { deleteApiV1SportById } from "./clients/deleteApiV1SportById.ts";
export { deleteApiV1UserById } from "./clients/deleteApiV1UserById.ts";
export { getApiV1CollegeById } from "./clients/getApiV1CollegeById.ts";
export { getApiV1Health } from "./clients/getApiV1Health.ts";
export { getApiV1HealthHealthcheck } from "./clients/getApiV1HealthHealthcheck.ts";
export { getApiV1SportById } from "./clients/getApiV1SportById.ts";
export { getApiV1SportByNameByName } from "./clients/getApiV1SportByNameByName.ts";
export { getApiV1Sports } from "./clients/getApiV1Sports.ts";
export { getApiV1UserById } from "./clients/getApiV1UserById.ts";
export { getApiV1UserCurrent } from "./clients/getApiV1UserCurrent.ts";
export { patchApiV1SportById } from "./clients/patchApiV1SportById.ts";
export { patchApiV1UserById } from "./clients/patchApiV1UserById.ts";
export { postApiV1College } from "./clients/postApiV1College.ts";
export { postApiV1Sport } from "./clients/postApiV1Sport.ts";
export { postApiV1User } from "./clients/postApiV1User.ts";
export { putApiV1CollegeById } from "./clients/putApiV1CollegeById.ts";
export { deleteApiV1CollegeByIdMutationKey } from "./hooks/useDeleteApiV1CollegeById.ts";
export { deleteApiV1CollegeByIdMutationOptions } from "./hooks/useDeleteApiV1CollegeById.ts";
export { useDeleteApiV1CollegeById } from "./hooks/useDeleteApiV1CollegeById.ts";
export { deleteApiV1SportByIdMutationKey } from "./hooks/useDeleteApiV1SportById.ts";
export { deleteApiV1SportByIdMutationOptions } from "./hooks/useDeleteApiV1SportById.ts";
export { useDeleteApiV1SportById } from "./hooks/useDeleteApiV1SportById.ts";
export { deleteApiV1UserByIdMutationKey } from "./hooks/useDeleteApiV1UserById.ts";
export { deleteApiV1UserByIdMutationOptions } from "./hooks/useDeleteApiV1UserById.ts";
export { useDeleteApiV1UserById } from "./hooks/useDeleteApiV1UserById.ts";
export { getApiV1CollegeByIdQueryKey } from "./hooks/useGetApiV1CollegeById.ts";
export { getApiV1CollegeByIdQueryOptions } from "./hooks/useGetApiV1CollegeById.ts";
export { useGetApiV1CollegeById } from "./hooks/useGetApiV1CollegeById.ts";
export { getApiV1CollegeByIdSuspenseQueryKey } from "./hooks/useGetApiV1CollegeByIdSuspense.ts";
export { getApiV1CollegeByIdSuspenseQueryOptions } from "./hooks/useGetApiV1CollegeByIdSuspense.ts";
export { useGetApiV1CollegeByIdSuspense } from "./hooks/useGetApiV1CollegeByIdSuspense.ts";
export { getApiV1HealthQueryKey } from "./hooks/useGetApiV1Health.ts";
export { getApiV1HealthQueryOptions } from "./hooks/useGetApiV1Health.ts";
export { useGetApiV1Health } from "./hooks/useGetApiV1Health.ts";
export { getApiV1HealthHealthcheckQueryKey } from "./hooks/useGetApiV1HealthHealthcheck.ts";
export { getApiV1HealthHealthcheckQueryOptions } from "./hooks/useGetApiV1HealthHealthcheck.ts";
export { useGetApiV1HealthHealthcheck } from "./hooks/useGetApiV1HealthHealthcheck.ts";
export { getApiV1HealthHealthcheckSuspenseQueryKey } from "./hooks/useGetApiV1HealthHealthcheckSuspense.ts";
export { getApiV1HealthHealthcheckSuspenseQueryOptions } from "./hooks/useGetApiV1HealthHealthcheckSuspense.ts";
export { useGetApiV1HealthHealthcheckSuspense } from "./hooks/useGetApiV1HealthHealthcheckSuspense.ts";
export { getApiV1HealthSuspenseQueryKey } from "./hooks/useGetApiV1HealthSuspense.ts";
export { getApiV1HealthSuspenseQueryOptions } from "./hooks/useGetApiV1HealthSuspense.ts";
export { useGetApiV1HealthSuspense } from "./hooks/useGetApiV1HealthSuspense.ts";
export { getApiV1SportByIdQueryKey } from "./hooks/useGetApiV1SportById.ts";
export { getApiV1SportByIdQueryOptions } from "./hooks/useGetApiV1SportById.ts";
export { useGetApiV1SportById } from "./hooks/useGetApiV1SportById.ts";
export { getApiV1SportByIdSuspenseQueryKey } from "./hooks/useGetApiV1SportByIdSuspense.ts";
export { getApiV1SportByIdSuspenseQueryOptions } from "./hooks/useGetApiV1SportByIdSuspense.ts";
export { useGetApiV1SportByIdSuspense } from "./hooks/useGetApiV1SportByIdSuspense.ts";
export { getApiV1SportByNameByNameQueryKey } from "./hooks/useGetApiV1SportByNameByName.ts";
export { getApiV1SportByNameByNameQueryOptions } from "./hooks/useGetApiV1SportByNameByName.ts";
export { useGetApiV1SportByNameByName } from "./hooks/useGetApiV1SportByNameByName.ts";
export { getApiV1SportByNameByNameSuspenseQueryKey } from "./hooks/useGetApiV1SportByNameByNameSuspense.ts";
export { getApiV1SportByNameByNameSuspenseQueryOptions } from "./hooks/useGetApiV1SportByNameByNameSuspense.ts";
export { useGetApiV1SportByNameByNameSuspense } from "./hooks/useGetApiV1SportByNameByNameSuspense.ts";
export { getApiV1SportsQueryKey } from "./hooks/useGetApiV1Sports.ts";
export { getApiV1SportsQueryOptions } from "./hooks/useGetApiV1Sports.ts";
export { useGetApiV1Sports } from "./hooks/useGetApiV1Sports.ts";
export { getApiV1SportsSuspenseQueryKey } from "./hooks/useGetApiV1SportsSuspense.ts";
export { getApiV1SportsSuspenseQueryOptions } from "./hooks/useGetApiV1SportsSuspense.ts";
export { useGetApiV1SportsSuspense } from "./hooks/useGetApiV1SportsSuspense.ts";
export { getApiV1UserByIdQueryKey } from "./hooks/useGetApiV1UserById.ts";
export { getApiV1UserByIdQueryOptions } from "./hooks/useGetApiV1UserById.ts";
export { useGetApiV1UserById } from "./hooks/useGetApiV1UserById.ts";
export { getApiV1UserByIdSuspenseQueryKey } from "./hooks/useGetApiV1UserByIdSuspense.ts";
export { getApiV1UserByIdSuspenseQueryOptions } from "./hooks/useGetApiV1UserByIdSuspense.ts";
export { useGetApiV1UserByIdSuspense } from "./hooks/useGetApiV1UserByIdSuspense.ts";
export { getApiV1UserCurrentQueryKey } from "./hooks/useGetApiV1UserCurrent.ts";
export { getApiV1UserCurrentQueryOptions } from "./hooks/useGetApiV1UserCurrent.ts";
export { useGetApiV1UserCurrent } from "./hooks/useGetApiV1UserCurrent.ts";
export { getApiV1UserCurrentSuspenseQueryKey } from "./hooks/useGetApiV1UserCurrentSuspense.ts";
export { getApiV1UserCurrentSuspenseQueryOptions } from "./hooks/useGetApiV1UserCurrentSuspense.ts";
export { useGetApiV1UserCurrentSuspense } from "./hooks/useGetApiV1UserCurrentSuspense.ts";
export { patchApiV1SportByIdMutationKey } from "./hooks/usePatchApiV1SportById.ts";
export { patchApiV1SportByIdMutationOptions } from "./hooks/usePatchApiV1SportById.ts";
export { usePatchApiV1SportById } from "./hooks/usePatchApiV1SportById.ts";
export { patchApiV1UserByIdMutationKey } from "./hooks/usePatchApiV1UserById.ts";
export { patchApiV1UserByIdMutationOptions } from "./hooks/usePatchApiV1UserById.ts";
export { usePatchApiV1UserById } from "./hooks/usePatchApiV1UserById.ts";
export { postApiV1CollegeMutationKey } from "./hooks/usePostApiV1College.ts";
export { postApiV1CollegeMutationOptions } from "./hooks/usePostApiV1College.ts";
export { usePostApiV1College } from "./hooks/usePostApiV1College.ts";
export { postApiV1SportMutationKey } from "./hooks/usePostApiV1Sport.ts";
export { postApiV1SportMutationOptions } from "./hooks/usePostApiV1Sport.ts";
export { usePostApiV1Sport } from "./hooks/usePostApiV1Sport.ts";
export { postApiV1UserMutationKey } from "./hooks/usePostApiV1User.ts";
export { postApiV1UserMutationOptions } from "./hooks/usePostApiV1User.ts";
export { usePostApiV1User } from "./hooks/usePostApiV1User.ts";
export { putApiV1CollegeByIdMutationKey } from "./hooks/usePutApiV1CollegeById.ts";
export { putApiV1CollegeByIdMutationOptions } from "./hooks/usePutApiV1CollegeById.ts";
export { usePutApiV1CollegeById } from "./hooks/usePutApiV1CollegeById.ts";
export { createCollegeRequestSchema } from "./zod/createCollegeRequestSchema.ts";
export { createCollegeResponseSchema } from "./zod/createCollegeResponseSchema.ts";
export { createSportRequestSchema } from "./zod/createSportRequestSchema.ts";
export { createUserBodySchema } from "./zod/createUserBodySchema.ts";
export { createUserResponseSchema } from "./zod/createUserResponseSchema.ts";
export { deleteApiV1CollegeByIdPathParamsSchema, deleteApiV1CollegeById200Schema, deleteApiV1CollegeByIdErrorSchema, deleteApiV1CollegeByIdMutationResponseSchema } from "./zod/deleteApiV1CollegeByIdSchema.ts";
export { deleteApiV1SportByIdPathParamsSchema, deleteApiV1SportById200Schema, deleteApiV1SportByIdErrorSchema, deleteApiV1SportByIdMutationResponseSchema } from "./zod/deleteApiV1SportByIdSchema.ts";
export { deleteApiV1UserByIdPathParamsSchema, deleteApiV1UserById200Schema, deleteApiV1UserByIdErrorSchema, deleteApiV1UserByIdMutationResponseSchema } from "./zod/deleteApiV1UserByIdSchema.ts";
export { deleteCollegeResponseSchema } from "./zod/deleteCollegeResponseSchema.ts";
export { deleteUserResponseSchema } from "./zod/deleteUserResponseSchema.ts";
export { errorDetailSchema } from "./zod/errorDetailSchema.ts";
export { errorModelSchema } from "./zod/errorModelSchema.ts";
export { getAllSportsResponseSchema } from "./zod/getAllSportsResponseSchema.ts";
export { getApiV1CollegeByIdPathParamsSchema, getApiV1CollegeById200Schema, getApiV1CollegeByIdErrorSchema, getApiV1CollegeByIdQueryResponseSchema } from "./zod/getApiV1CollegeByIdSchema.ts";
export { getApiV1HealthHealthcheck200Schema, getApiV1HealthHealthcheckErrorSchema, getApiV1HealthHealthcheckQueryResponseSchema } from "./zod/getApiV1HealthHealthcheckSchema.ts";
export { getApiV1Health200Schema, getApiV1HealthErrorSchema, getApiV1HealthQueryResponseSchema } from "./zod/getApiV1HealthSchema.ts";
export { getApiV1SportByIdPathParamsSchema, getApiV1SportById200Schema, getApiV1SportByIdErrorSchema, getApiV1SportByIdQueryResponseSchema } from "./zod/getApiV1SportByIdSchema.ts";
export { getApiV1SportByNameByNamePathParamsSchema, getApiV1SportByNameByName200Schema, getApiV1SportByNameByNameErrorSchema, getApiV1SportByNameByNameQueryResponseSchema } from "./zod/getApiV1SportByNameByNameSchema.ts";
export { getApiV1SportsQueryParamsSchema, getApiV1Sports200Schema, getApiV1SportsErrorSchema, getApiV1SportsQueryResponseSchema } from "./zod/getApiV1SportsSchema.ts";
export { getApiV1UserByIdPathParamsSchema, getApiV1UserById200Schema, getApiV1UserByIdErrorSchema, getApiV1UserByIdQueryResponseSchema } from "./zod/getApiV1UserByIdSchema.ts";
export { getApiV1UserCurrent200Schema, getApiV1UserCurrentErrorSchema, getApiV1UserCurrentQueryResponseSchema } from "./zod/getApiV1UserCurrentSchema.ts";
export { getCollegeResponseSchema } from "./zod/getCollegeResponseSchema.ts";
export { getCurrentUserIDResponseSchema } from "./zod/getCurrentUserIDResponseSchema.ts";
export { getUserResponseSchema } from "./zod/getUserResponseSchema.ts";
export { healthResponseSchema } from "./zod/healthResponseSchema.ts";
export { patchApiV1SportByIdPathParamsSchema, patchApiV1SportById200Schema, patchApiV1SportByIdErrorSchema, patchApiV1SportByIdMutationRequestSchema, patchApiV1SportByIdMutationResponseSchema } from "./zod/patchApiV1SportByIdSchema.ts";
export { patchApiV1UserByIdPathParamsSchema, patchApiV1UserById200Schema, patchApiV1UserByIdErrorSchema, patchApiV1UserByIdMutationRequestSchema, patchApiV1UserByIdMutationResponseSchema } from "./zod/patchApiV1UserByIdSchema.ts";
export { postApiV1College200Schema, postApiV1CollegeErrorSchema, postApiV1CollegeMutationRequestSchema, postApiV1CollegeMutationResponseSchema } from "./zod/postApiV1CollegeSchema.ts";
export { postApiV1Sport200Schema, postApiV1SportErrorSchema, postApiV1SportMutationRequestSchema, postApiV1SportMutationResponseSchema } from "./zod/postApiV1SportSchema.ts";
export { postApiV1User200Schema, postApiV1UserErrorSchema, postApiV1UserMutationRequestSchema, postApiV1UserMutationResponseSchema } from "./zod/postApiV1UserSchema.ts";
export { putApiV1CollegeByIdPathParamsSchema, putApiV1CollegeById200Schema, putApiV1CollegeByIdErrorSchema, putApiV1CollegeByIdMutationRequestSchema, putApiV1CollegeByIdMutationResponseSchema } from "./zod/putApiV1CollegeByIdSchema.ts";
export { sportResponseSchema } from "./zod/sportResponseSchema.ts";
export { updateCollegeRequestSchema } from "./zod/updateCollegeRequestSchema.ts";
export { updateCollegeResponseSchema } from "./zod/updateCollegeResponseSchema.ts";
export { updateSportRequestSchema } from "./zod/updateSportRequestSchema.ts";
export { updateUserBodySchema } from "./zod/updateUserBodySchema.ts";
export { updateUserResponseSchema } from "./zod/updateUserResponseSchema.ts";