/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userRoleResponseSchema } from "./userRoleResponseSchema.ts";
import { z } from "zod/v4";

export const assignRoleResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get role() {
    return userRoleResponseSchema.describe("Assigned role");
  },
  user_id: z.string().describe("ID of the user"),
});
