/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const averageRatingsRowSchema = z.object({
  academic_career_resources: z.number(),
  academics_athletics_priority: z.number(),
  college_id: z.string(),
  culture: z.number(),
  environment: z.number(),
  mental_health_priority: z.number(),
  player_dev: z.number(),
  response_count: z.int(),
  sport_id: z.string(),
  transparency: z.number(),
});
