/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const createCommentResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  description: z.string().max(1500).describe("Content of the comment"),
  id: z.string().describe("ID of comment"),
  is_anonymous: z
    .boolean()
    .describe(
      "True if posted as anonymous; frontend can show 'Anonymous' when user_id is omitted",
    ),
  parent_comment_id: z.string().describe("CommentID the comment belongs to"),
  post_id: z.string().describe("PostID the comment belongs to"),
  user: z.optional(
    z
      .string()
      .describe("The user who commented; omitted for anonymous comments"),
  ),
});
