/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createCollegeResponseSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
"academic_rank": z.nullable(z.int().describe("Academic rank of the college")),
"city": z.string().describe("City of the college"),
"division_rank": z.int().min(1).max(3).describe("NCAA division (1, 2, or 3)"),
"id": z.string().describe("ID of the college"),
"logo": z.nullable(z.string().describe("Logo of the college")),
"name": z.string().describe("Name of the college"),
"state": z.string().describe("State of the college"),
"website": z.string().describe("Website of the college")
    })