/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { mediaSchema } from "./mediaSchema.ts";
import { tagSchema } from "./tagSchema.ts";
import { z } from "zod/v4";

export const createPremiumPostResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  author: z.string(),
  college_id: z.string(),
  content: z.string(),
  id: z.string(),
  get media() {
    return mediaSchema.optional();
  },
  media_id: z.optional(z.string()),
  sport_id: z.string(),
  get tag() {
    return z.array(tagSchema).nullable();
  },
  title: z.string(),
});
