/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createTagResponseSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
"id": z.string().describe("ID of the tag created"),
"name": z.string().describe("The name of the tag created")
    })