/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const createStripeCheckoutSessionRequestSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  cancel_url: z.string(),
  price_id: z.string(),
  quantity: z.int(),
  success_url: z.string(),
});
