/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { tagRequestSchema } from "./tagRequestSchema.ts";
import { z } from "zod/v4";

export const createPostRequestSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  college_id: z.optional(z.string()),
  content: z.string().min(1).max(5000),
  is_anonymous: z.boolean(),
  sport_id: z.optional(z.string()),
  get tags() {
    return z.array(tagRequestSchema).nullish();
  },
  title: z.string().min(1).max(100),
});
