/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { tagSchema } from "./tagSchema.ts";
import { z } from "zod/v4";

export const createPostResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  author: z.string(),
  college: z.string(),
  content: z.string(),
  id: z.string(),
  is_anonymous: z.boolean(),
  sport: z.string(),
  get tags() {
    return z.array(tagSchema).nullable();
  },
  title: z.string(),
});
