/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const createTagFollowBodySchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  tag_id: z.string().describe("ID of the Tag"),
  user_id: z.string().describe("ID of the user"),
});
