/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deleteStripeCustomerResponseSchema } from "./deleteStripeCustomerResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const deleteApiV1StripeCustomersById200Schema = z.lazy(() => deleteStripeCustomerResponseSchema)

/**
 * @description Error
 */
export const deleteApiV1StripeCustomersByIdErrorSchema = z.lazy(() => errorModelSchema)

export const deleteApiV1StripeCustomersByIdMutationResponseSchema = z.lazy(() => deleteApiV1StripeCustomersById200Schema)