/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { deleteTagFollowResponseSchema } from "./deleteTagFollowResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1UserTagByIdPathParamsSchema = z.object({
  id: z.string().describe("ID of the tag follow to be deleted"),
});

/**
 * @description OK
 */
export const deleteApiV1UserTagById200Schema = z.lazy(
  () => deleteTagFollowResponseSchema,
);

/**
 * @description Error
 */
export const deleteApiV1UserTagByIdErrorSchema = z.lazy(() => errorModelSchema);

export const deleteApiV1UserTagByIdMutationResponseSchema = z.lazy(
  () => deleteApiV1UserTagById200Schema,
);
