/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { sportResponseSchema } from "./sportResponseSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1SportByIdPathParamsSchema = z.object({
    "id": z.string().describe("ID of the sport")
    })

/**
 * @description OK
 */
export const deleteApiV1SportById200Schema = z.lazy(() => sportResponseSchema)

/**
 * @description Error
 */
export const deleteApiV1SportByIdErrorSchema = z.lazy(() => errorModelSchema)

export const deleteApiV1SportByIdMutationResponseSchema = z.lazy(() => deleteApiV1SportById200Schema)