/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deleteUserResponseSchema } from "./deleteUserResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1UserByIdPathParamsSchema = z.object({
    "id": z.string().max(36).describe("ID to identify the user")
    })

/**
 * @description OK
 */
export const deleteApiV1UserById200Schema = z.lazy(() => deleteUserResponseSchema)

/**
 * @description Error
 */
export const deleteApiV1UserByIdErrorSchema = z.lazy(() => errorModelSchema)

export const deleteApiV1UserByIdMutationResponseSchema = z.lazy(() => deleteApiV1UserById200Schema)