/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { surveyResponseSchema } from "./surveyResponseSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1SurveyByIdPathParamsSchema = z.object({
  id: z.string().describe("ID of the survey to delete"),
});

/**
 * @description OK
 */
export const deleteApiV1SurveyById200Schema = z.lazy(
  () => surveyResponseSchema,
);

/**
 * @description Error
 */
export const deleteApiV1SurveyByIdErrorSchema = z.lazy(() => errorModelSchema);

export const deleteApiV1SurveyByIdMutationResponseSchema = z.lazy(
  () => deleteApiV1SurveyById200Schema,
);
