/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { deleteContentResponseSchema } from "./deleteContentResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1ContentQueryParamsSchema = z.object({
  key: z.string().describe("S3 object key to delete"),
});

/**
 * @description OK
 */
export const deleteApiV1Content200Schema = z.lazy(
  () => deleteContentResponseSchema,
);

/**
 * @description Error
 */
export const deleteApiV1ContentErrorSchema = z.lazy(() => errorModelSchema);

export const deleteApiV1ContentMutationResponseSchema = z.lazy(
  () => deleteApiV1Content200Schema,
);
