/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { assignRoleRequestSchema } from "./assignRoleRequestSchema.ts";
import { assignRoleResponseSchema } from "./assignRoleResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1UserByIdRolesPathParamsSchema = z.object({
  id: z.string().max(36).describe("ID of the user"),
});

/**
 * @description OK
 */
export const deleteApiV1UserByIdRoles200Schema = z.lazy(
  () => assignRoleResponseSchema,
);

/**
 * @description Error
 */
export const deleteApiV1UserByIdRolesErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const deleteApiV1UserByIdRolesMutationRequestSchema = z
  .lazy(() => assignRoleRequestSchema)
  .unwrap()
  .omit({ $schema: true });

export const deleteApiV1UserByIdRolesMutationResponseSchema = z.lazy(
  () => deleteApiV1UserByIdRoles200Schema,
);
