/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deleteTagPostResponseSchema } from "./deleteTagPostResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1PostTagByIdPathParamsSchema = z.object({
    "id": z.string().describe("ID of the TagsPosts item")
    })

/**
 * @description OK
 */
export const deleteApiV1PostTagById200Schema = z.lazy(() => deleteTagPostResponseSchema)

/**
 * @description Error
 */
export const deleteApiV1PostTagByIdErrorSchema = z.lazy(() => errorModelSchema)

export const deleteApiV1PostTagByIdMutationResponseSchema = z.lazy(() => deleteApiV1PostTagById200Schema)