/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { stripeProductResponseSchema } from "./stripeProductResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const deleteApiV1StripeProductById200Schema = z.lazy(() => stripeProductResponseSchema)

/**
 * @description Error
 */
export const deleteApiV1StripeProductByIdErrorSchema = z.lazy(() => errorModelSchema)

export const deleteApiV1StripeProductByIdMutationResponseSchema = z.lazy(() => deleteApiV1StripeProductById200Schema)