/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { deletePremiumPostRequestSchema } from "./deletePremiumPostRequestSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1PostsPremiumByIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description OK
 */
export const deleteApiV1PostsPremiumById200Schema = z.lazy(
  () => deletePremiumPostRequestSchema,
);

/**
 * @description Error
 */
export const deleteApiV1PostsPremiumByIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const deleteApiV1PostsPremiumByIdMutationResponseSchema = z.lazy(
  () => deleteApiV1PostsPremiumById200Schema,
);
