/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { deleteTagFollowResponseSchema } from "./deleteTagFollowResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const deleteApiV1UserTagTagByTagIdPathParamsSchema = z.object({
  tag_id: z
    .string()
    .describe("ID of the tag follow's tag to be deleted for current user"),
});

/**
 * @description OK
 */
export const deleteApiV1UserTagTagByTagId200Schema = z.lazy(
  () => deleteTagFollowResponseSchema,
);

/**
 * @description Error
 */
export const deleteApiV1UserTagTagByTagIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const deleteApiV1UserTagTagByTagIdMutationResponseSchema = z.lazy(
  () => deleteApiV1UserTagTagByTagId200Schema,
);
