/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const errorDetailSchema = z.object({
    "location": z.optional(z.string().describe("Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'")),
"message": z.optional(z.string().describe("Error message text")),
"value": z.optional(z.any().describe("The value at the given location"))
    })