/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getUserLikedPostsResponseSchema } from "./getUserLikedPostsResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1UserByUserIdLikedPostsPathParamsSchema = z.object({
  user_id: z.string().describe("ID of the user whose liked posts to fetch"),
});

/**
 * @description OK
 */
export const getApiV1UserByUserIdLikedPosts200Schema = z.lazy(
  () => getUserLikedPostsResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1UserByUserIdLikedPostsErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1UserByUserIdLikedPostsQueryResponseSchema = z.lazy(
  () => getApiV1UserByUserIdLikedPosts200Schema,
);
