/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { accessCheckResponseSchema } from "./accessCheckResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const getApiV1UtilityAccessCheck200Schema = z.lazy(
  () => accessCheckResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1UtilityAccessCheckErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1UtilityAccessCheckQueryResponseSchema = z.lazy(
  () => getApiV1UtilityAccessCheck200Schema,
);
