/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getPostsBySportIDResponseSchema } from "./getPostsBySportIDResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostsBySportBySportIdPathParamsSchema = z.object({
    "sport_id": z.string().describe("Sport ID to filter posts")
    })

export const getApiV1PostsBySportBySportIdQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(50).describe("Number of posts to return"),
"offset": z.coerce.number().int().default(0).describe("Number of posts to skip")
    })

/**
 * @description OK
 */
export const getApiV1PostsBySportBySportId200Schema = z.lazy(() => getPostsBySportIDResponseSchema)

/**
 * @description Error
 */
export const getApiV1PostsBySportBySportIdErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1PostsBySportBySportIdQueryResponseSchema = z.lazy(() => getApiV1PostsBySportBySportId200Schema)