/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { listTagsResponseSchema } from "./listTagsResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1TagQueryParamsSchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .default(100)
    .describe("Number of tags to return"),
  offset: z.coerce.number().int().default(0).describe("Number of tags to skip"),
});

/**
 * @description OK
 */
export const getApiV1Tag200Schema = z.lazy(() => listTagsResponseSchema);

/**
 * @description Error
 */
export const getApiV1TagErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1TagQueryResponseSchema = z.lazy(
  () => getApiV1Tag200Schema,
);
