/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getTagResponseSchema } from "./getTagResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1TagByIdPathParamsSchema = z.object({
  id: z.string().describe("ID to identify tag"),
});

/**
 * @description OK
 */
export const getApiV1TagById200Schema = z.lazy(() => getTagResponseSchema);

/**
 * @description Error
 */
export const getApiV1TagByIdErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1TagByIdQueryResponseSchema = z.lazy(
  () => getApiV1TagById200Schema,
);
