/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { postResponseSchema } from "./postResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostByIdPathParamsSchema = z.object({
  id: z.string().describe("ID of the post"),
});

/**
 * @description OK
 */
export const getApiV1PostById200Schema = z.lazy(() => postResponseSchema);

/**
 * @description Error
 */
export const getApiV1PostByIdErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1PostByIdQueryResponseSchema = z.lazy(
  () => getApiV1PostById200Schema,
);
