/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { listCollegesResponseSchema } from "./listCollegesResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1CollegesQueryParamsSchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .default(200)
    .describe("Maximum number of colleges to return"),
  offset: z.coerce
    .number()
    .int()
    .default(0)
    .describe("Number of colleges to skip"),
});

/**
 * @description OK
 */
export const getApiV1Colleges200Schema = z.lazy(
  () => listCollegesResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1CollegesErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1CollegesQueryResponseSchema = z.lazy(
  () => getApiV1Colleges200Schema,
);
