/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getTagPostByIDResponseSchema } from "./getTagPostByIDResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostTagByIdPathParamsSchema = z.object({
    "id": z.string().describe("ID of the TagsPosts item")
    })

/**
 * @description OK
 */
export const getApiV1PostTagById200Schema = z.lazy(() => getTagPostByIDResponseSchema)

/**
 * @description Error
 */
export const getApiV1PostTagByIdErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1PostTagByIdQueryResponseSchema = z.lazy(() => getApiV1PostTagById200Schema)