/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getStripeCustomerByEmailResponseSchema } from "./getStripeCustomerByEmailResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1StripeCustomersEmailByEmailPathParamsSchema = z.object({
    "email": z.string().max(36).describe("email to identify the stripe user")
    })

/**
 * @description OK
 */
export const getApiV1StripeCustomersEmailByEmail200Schema = z.lazy(() => getStripeCustomerByEmailResponseSchema)

/**
 * @description Error
 */
export const getApiV1StripeCustomersEmailByEmailErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1StripeCustomersEmailByEmailQueryResponseSchema = z.lazy(() => getApiV1StripeCustomersEmailByEmail200Schema)