/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getAllRolesResponseSchema } from "./getAllRolesResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1RolesQueryParamsSchema = z
  .object({
    limit: z.optional(
      z.coerce.number().int().describe("Limit number of roles"),
    ),
    offset: z.optional(
      z.coerce.number().int().describe("Offset for pagination"),
    ),
  })
  .optional();

/**
 * @description OK
 */
export const getApiV1Roles200Schema = z.lazy(() => getAllRolesResponseSchema);

/**
 * @description Error
 */
export const getApiV1RolesErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1RolesQueryResponseSchema = z.lazy(
  () => getApiV1Roles200Schema,
);
