/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getAllSportsResponseSchema } from "./getAllSportsResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1SportsQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(50).describe("Number of sports to return"),
"offset": z.coerce.number().int().default(0).describe("Number of sports to skip")
    })

/**
 * @description OK
 */
export const getApiV1Sports200Schema = z.lazy(() => getAllSportsResponseSchema)

/**
 * @description Error
 */
export const getApiV1SportsErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1SportsQueryResponseSchema = z.lazy(() => getApiV1Sports200Schema)