/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { roleResponseSchema } from "./roleResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1RoleByIdPathParamsSchema = z.object({
  id: z.string().max(36).describe("ID of the role"),
});

/**
 * @description OK
 */
export const getApiV1RoleById200Schema = z.lazy(() => roleResponseSchema);

/**
 * @description Error
 */
export const getApiV1RoleByIdErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1RoleByIdQueryResponseSchema = z.lazy(
  () => getApiV1RoleById200Schema,
);
