/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getAllPostsResponseSchema } from "./getAllPostsResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostsQueryParamsSchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .default(50)
    .describe("Number of posts to return"),
  offset: z.coerce
    .number()
    .int()
    .default(0)
    .describe("Number of posts to skip"),
});

/**
 * @description OK
 */
export const getApiV1Posts200Schema = z.lazy(() => getAllPostsResponseSchema);

/**
 * @description Error
 */
export const getApiV1PostsErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1PostsQueryResponseSchema = z.lazy(
  () => getApiV1Posts200Schema,
);
