/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { stripeCheckoutSessionResponseSchema } from "./stripeCheckoutSessionResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1CheckoutSessionsByIdPathParamsSchema = z.object({
  id: z.string().describe("ID of the product"),
});

/**
 * @description OK
 */
export const getApiV1CheckoutSessionsById200Schema = z.lazy(
  () => stripeCheckoutSessionResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1CheckoutSessionsByIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1CheckoutSessionsByIdQueryResponseSchema = z.lazy(
  () => getApiV1CheckoutSessionsById200Schema,
);
