/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getCommentLikeInfoResponseSchema } from "./getCommentLikeInfoResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1CommentLikeByCommentIdLikesPathParamsSchema = z.object({
    "comment_id": z.string().describe("Comment to get like info for")
    })

/**
 * @description OK
 */
export const getApiV1CommentLikeByCommentIdLikes200Schema = z.lazy(() => getCommentLikeInfoResponseSchema)

/**
 * @description Error
 */
export const getApiV1CommentLikeByCommentIdLikesErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1CommentLikeByCommentIdLikesQueryResponseSchema = z.lazy(() => getApiV1CommentLikeByCommentIdLikes200Schema)