/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getCollegeResponseSchema } from "./getCollegeResponseSchema.ts";
import { z } from "zod/v4";

export const getAllCollegesResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get colleges() {
    return z.array(getCollegeResponseSchema).nullable();
  },
});
