/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getUserResponseSchema } from "./getUserResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1UserUsernameByUsernamePathParamsSchema = z.object({
  username: z.string().describe("Username of the user"),
});

/**
 * @description OK
 */
export const getApiV1UserUsernameByUsername200Schema = z.lazy(
  () => getUserResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1UserUsernameByUsernameErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1UserUsernameByUsernameQueryResponseSchema = z.lazy(
  () => getApiV1UserUsernameByUsername200Schema,
);
