/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { stripePriceResponseSchema } from "./stripePriceResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1StripePriceByIdPathParamsSchema = z.object({
    "id": z.string().describe("ID of the product")
    })

/**
 * @description OK
 */
export const getApiV1StripePriceById200Schema = z.lazy(() => stripePriceResponseSchema)

/**
 * @description Error
 */
export const getApiV1StripePriceByIdErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1StripePriceByIdQueryResponseSchema = z.lazy(() => getApiV1StripePriceById200Schema)