/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { permissionResponseSchema } from "./permissionResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PermissionByIdPathParamsSchema = z.object({
    "id": z.string().max(36).describe("ID of the permission")
    })

/**
 * @description OK
 */
export const getApiV1PermissionById200Schema = z.lazy(() => permissionResponseSchema)

/**
 * @description Error
 */
export const getApiV1PermissionByIdErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1PermissionByIdQueryResponseSchema = z.lazy(() => getApiV1PermissionById200Schema)