/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getDownloadURLResponseSchema } from "./getDownloadURLResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1ContentDownloadUrlQueryParamsSchema = z.object({
  key: z.string().describe("S3 object key"),
});

/**
 * @description OK
 */
export const getApiV1ContentDownloadUrl200Schema = z.lazy(
  () => getDownloadURLResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1ContentDownloadUrlErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1ContentDownloadUrlQueryResponseSchema = z.lazy(
  () => getApiV1ContentDownloadUrl200Schema,
);
