/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getPostLikeInfoResponseSchema } from "./getPostLikeInfoResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostLikeByPostIdLikesPathParamsSchema = z.object({
    "post_id": z.string().describe("Post to get like info for")
    })

/**
 * @description OK
 */
export const getApiV1PostLikeByPostIdLikes200Schema = z.lazy(() => getPostLikeInfoResponseSchema)

/**
 * @description Error
 */
export const getApiV1PostLikeByPostIdLikesErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1PostLikeByPostIdLikesQueryResponseSchema = z.lazy(() => getApiV1PostLikeByPostIdLikes200Schema)