/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getPostLikeResponseSchema } from "./getPostLikeResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostLikeByIdPathParamsSchema = z.object({
    "id": z.string().max(36).describe("ID of the like")
    })

/**
 * @description OK
 */
export const getApiV1PostLikeById200Schema = z.lazy(() => getPostLikeResponseSchema)

/**
 * @description Error
 */
export const getApiV1PostLikeByIdErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1PostLikeByIdQueryResponseSchema = z.lazy(() => getApiV1PostLikeById200Schema)