/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { postResponseSchema } from "./postResponseSchema.ts";
import { z } from "zod/v4";

export const getAllPostsResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get posts() {
    return z.array(postResponseSchema).describe("List of posts").nullable();
  },
  total: z.int().describe("Total number of posts"),
});
