/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { permissionResponseSchema } from "./permissionResponseSchema.ts";
import { z } from "zod/v4";

export const getAllPermissionsResponseSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
get "permissions"(){
               return z.array(permissionResponseSchema).describe("List of permissions").nullable()
              },
"total": z.int().describe("Total number of permissions")
    })