/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { getUserResponseSchema } from "./getUserResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1UserByIdPathParamsSchema = z.object({
    "id": z.string().max(36).describe("ID to identify the user")
    })

/**
 * @description OK
 */
export const getApiV1UserById200Schema = z.lazy(() => getUserResponseSchema)

/**
 * @description Error
 */
export const getApiV1UserByIdErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1UserByIdQueryResponseSchema = z.lazy(() => getApiV1UserById200Schema)