/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getPremiumPostsBySportIDResponseSchema } from "./getPremiumPostsBySportIDResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostsPremiumBySportBySportIdPathParamsSchema = z.object({
  sport_id: z.string().describe("Sport ID to filter posts"),
});

export const getApiV1PostsPremiumBySportBySportIdQueryParamsSchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .default(50)
    .describe("Number of posts to return"),
  offset: z.coerce
    .number()
    .int()
    .default(0)
    .describe("Number of posts to skip"),
});

/**
 * @description OK
 */
export const getApiV1PostsPremiumBySportBySportId200Schema = z.lazy(
  () => getPremiumPostsBySportIDResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1PostsPremiumBySportBySportIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1PostsPremiumBySportBySportIdQueryResponseSchema = z.lazy(
  () => getApiV1PostsPremiumBySportBySportId200Schema,
);
