/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getFilterPremiumPostsResponseSchema } from "./getFilterPremiumPostsResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostsPremiumFilterQueryParamsSchema = z.object({
  college_ids: z.optional(
    z.string().describe("Comma seperated list of college_ids to filter by"),
  ),
  sport_ids: z.optional(
    z.string().describe("Comma seperated list of sport_ids to filter by"),
  ),
  tag_ids: z.optional(
    z.string().describe("Comma seperated list of tag_ids to filter by"),
  ),
  limit: z.coerce
    .number()
    .int()
    .default(20)
    .describe("Number of posts to return when filtering"),
  offset: z.coerce
    .number()
    .int()
    .default(0)
    .describe("Number of entries in the database to offset by"),
});

/**
 * @description OK
 */
export const getApiV1PostsPremiumFilter200Schema = z.lazy(
  () => getFilterPremiumPostsResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1PostsPremiumFilterErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1PostsPremiumFilterQueryResponseSchema = z.lazy(
  () => getApiV1PostsPremiumFilter200Schema,
);
