/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { searchResultsGetTagResponseSchema } from "./searchResultsGetTagResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1TagsSearchQueryParamsSchema = z.object({
  search_str: z.optional(z.string()),
  limit: z.coerce.number().int().default(20),
});

/**
 * @description OK
 */
export const getApiV1TagsSearch200Schema = z.lazy(
  () => searchResultsGetTagResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1TagsSearchErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1TagsSearchQueryResponseSchema = z.lazy(
  () => getApiV1TagsSearch200Schema,
);
