/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { healthResponseSchema } from "./healthResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const getApiV1HealthHealthcheck200Schema = z.lazy(() => healthResponseSchema)

/**
 * @description Error
 */
export const getApiV1HealthHealthcheckErrorSchema = z.lazy(() => errorModelSchema)

export const getApiV1HealthHealthcheckQueryResponseSchema = z.lazy(() => getApiV1HealthHealthcheck200Schema)