/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getSurveysByUserResponseSchema } from "./getSurveysByUserResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1SurveyUserByUserIdPathParamsSchema = z.object({
  user_id: z.string().describe("ID of the user"),
});

export const getApiV1SurveyUserByUserIdQueryParamsSchema = z.object({
  limit: z.coerce
    .number()
    .int()
    .default(50)
    .describe("Number of surveys to return"),
  offset: z.coerce
    .number()
    .int()
    .default(0)
    .describe("Number of surveys to skip"),
});

/**
 * @description OK
 */
export const getApiV1SurveyUserByUserId200Schema = z.lazy(
  () => getSurveysByUserResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1SurveyUserByUserIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const getApiV1SurveyUserByUserIdQueryResponseSchema = z.lazy(
  () => getApiV1SurveyUserByUserId200Schema,
);
