/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getAllPostsResponseSchema } from "./getAllPostsResponseSchema.ts";
import { z } from "zod/v4";

export const getApiV1PostsFilterQueryParamsSchema = z.object({
  college_ids: z.optional(
    z.string().describe("Comma seperated list of college_ids to filter by"),
  ),
  sport_ids: z.optional(
    z.string().describe("Comma seperated list of sport_ids to filter by"),
  ),
  tag_ids: z.optional(
    z.string().describe("Comma seperated list of tag_ids to filter by"),
  ),
  limit: z.coerce
    .number()
    .int()
    .default(20)
    .describe("Number of posts to return when filtering"),
  offset: z.coerce
    .number()
    .int()
    .default(0)
    .describe("Number of entries in the database to offset by"),
});

/**
 * @description OK
 */
export const getApiV1PostsFilter200Schema = z.lazy(
  () => getAllPostsResponseSchema,
);

/**
 * @description Error
 */
export const getApiV1PostsFilterErrorSchema = z.lazy(() => errorModelSchema);

export const getApiV1PostsFilterQueryResponseSchema = z.lazy(
  () => getApiV1PostsFilter200Schema,
);
