/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const getCollegeFollowsByUserResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  college_ids: z.nullable(
    z.array(z.string()).describe("The colleges the given user follows"),
  ),
  user_id: z.string().describe("ID of the user"),
});
