/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const getCurrentUserIDResponseSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
"account_type": z.boolean().describe("If the user has access to premium features"),
"bio": z.optional(z.string().describe("The bio of a user")),
"college": z.optional(z.string().describe("The college of a user")),
"division": z.optional(z.int().min(0).describe("The division of their college")),
"email": z.string().describe("The email of a user"),
"expected_grad_year": z.optional(z.int().min(0).describe("The user's grad year")),
"first_name": z.string().describe("The first name of a user"),
"id": z.string().describe("ID of the currently authenticated user"),
"last_name": z.string().describe("The last name of a user"),
"sport": z.optional(z.string().describe("The sport(s) the user is interested in")),
"username": z.string().describe("The username of a user"),
"verified_athlete_status": z.string().describe("Verification status for the athlete")
    })