/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { postResponseSchema } from "./postResponseSchema.ts";
import { z } from "zod/v4";

export const getPostsByTagResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get post_ids() {
    return z
      .array(postResponseSchema)
      .describe("The post ids associated with a tag")
      .nullable();
  },
});
