/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { premiumPostResponseSchema } from "./premiumPostResponseSchema.ts";
import { z } from "zod/v4";

export const getPremiumPostsByCollegeIDResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get posts() {
    return z
      .array(premiumPostResponseSchema)
      .describe("List of premium posts for the college")
      .nullable();
  },
  total: z.int().describe("Total number of premium posts for this college"),
});
