/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { premiumPostResponseSchema } from "./premiumPostResponseSchema.ts";
import { z } from "zod/v4";

export const getSearchPremiumPostResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  count: z.int().describe("Count of search results found for given search"),
  get posts() {
    return z
      .array(premiumPostResponseSchema)
      .describe("List of premium post responses found for given search")
      .nullable();
  },
});
