/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const getUploadURLRequestSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  fileName: z
    .string()
    .describe(
      "Optional; used as documentId in response (defaults to last segment of key)",
    ),
  fileType: z.string().describe("MIME type, e.g. image/jpeg, application/pdf"),
  key: z
    .string()
    .describe("Full S3 object key, e.g. premium/image/content-123/photo.jpg"),
});
