/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { collegeSchema } from "./collegeSchema.ts";
import { mediaSchema } from "./mediaSchema.ts";
import { roleResponseSchema } from "./roleResponseSchema.ts";
import { sportSchema } from "./sportSchema.ts";
import { z } from "zod/v4";

export const getUserResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  account_type: z
    .boolean()
    .describe("If the user has access to premium features"),
  bio: z.optional(z.string().describe("The bio of a user")),
  get college() {
    return collegeSchema.describe("The college of a user").optional();
  },
  division: z.optional(
    z.int().min(0).describe("The division of their college"),
  ),
  email: z.string().describe("The email of a user"),
  expected_grad_year: z.optional(
    z.int().min(0).describe("The user's grad year"),
  ),
  first_name: z.string().describe("The first name of a user"),
  id: z.string().describe("ID of the user"),
  last_name: z.string().describe("The last name of a user"),
  get profile_picture() {
    return mediaSchema.describe("The media of the profile picture").optional();
  },
  profile_picture_url: z.optional(
    z.string().describe("The url of the profile picture"),
  ),
  get roles() {
    return z
      .array(roleResponseSchema)
      .describe("Roles assigned to the user")
      .optional();
  },
  get sport() {
    return sportSchema
      .describe("The sport(s) the user is interested in")
      .optional();
  },
  username: z.string().describe("The username of a user"),
  verified_athlete_status: z
    .string()
    .describe("Verification status for the athlete"),
});
