/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const healthResponseSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
"message": z.string().describe("Message to display")
    })