/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { commentResponseSchema } from "./commentResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

export const listApiV1CommentByIdRepliesPathParamsSchema = z.object({
    "id": z.string().describe("ID of parent comment to get replies for")
    })

/**
 * @description OK
 */
export const listApiV1CommentByIdReplies200Schema = z.array(z.lazy(() => commentResponseSchema)).nullable()

/**
 * @description Error
 */
export const listApiV1CommentByIdRepliesErrorSchema = z.lazy(() => errorModelSchema)

export const listApiV1CommentByIdRepliesQueryResponseSchema = z.lazy(() => listApiV1CommentByIdReplies200Schema)