/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { stripeProductResponseSchema } from "./stripeProductResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const listApiV1StripeProducts200Schema = z.array(z.lazy(() => stripeProductResponseSchema)).nullable()

/**
 * @description Error
 */
export const listApiV1StripeProductsErrorSchema = z.lazy(() => errorModelSchema)

export const listApiV1StripeProductsQueryResponseSchema = z.lazy(() => listApiV1StripeProducts200Schema)