/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const mediaSchema = z.object({
  created_at: z.iso.datetime(),
  id: z.string(),
  media_type: z.string().describe("The media type of the object"),
  s3key: z.string().describe("The S3 key of the media object"),
  title: z.string().describe("The title of the media"),
});
