/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { roleResponseSchema } from "./roleResponseSchema.ts";
import { updateRoleRequestSchema } from "./updateRoleRequestSchema.ts";
import { z } from "zod/v4";

export const patchApiV1RoleByIdPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description OK
 */
export const patchApiV1RoleById200Schema = z.lazy(() => roleResponseSchema)

/**
 * @description Error
 */
export const patchApiV1RoleByIdErrorSchema = z.lazy(() => errorModelSchema)

export const patchApiV1RoleByIdMutationRequestSchema = z.lazy(() => updateRoleRequestSchema).unwrap().omit({ '$schema': true })

export const patchApiV1RoleByIdMutationResponseSchema = z.lazy(() => patchApiV1RoleById200Schema)