/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { premiumPostResponseSchema } from "./premiumPostResponseSchema.ts";
import { updatePremiumPostRequestSchema } from "./updatePremiumPostRequestSchema.ts";
import { z } from "zod/v4";

export const patchApiV1PostsPremiumByIdPathParamsSchema = z.object({
  id: z.string(),
});

/**
 * @description OK
 */
export const patchApiV1PostsPremiumById200Schema = z.lazy(
  () => premiumPostResponseSchema,
);

/**
 * @description Error
 */
export const patchApiV1PostsPremiumByIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const patchApiV1PostsPremiumByIdMutationRequestSchema = z
  .lazy(() => updatePremiumPostRequestSchema)
  .unwrap()
  .omit({ $schema: true });

export const patchApiV1PostsPremiumByIdMutationResponseSchema = z.lazy(
  () => patchApiV1PostsPremiumById200Schema,
);
