/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorModelSchema } from "./errorModelSchema.ts";
import { getStripeCustomerResponseSchema } from "./getStripeCustomerResponseSchema.ts";
import { updateStripeCustomerBodySchema } from "./updateStripeCustomerBodySchema.ts";
import { z } from "zod/v4";

export const patchApiV1StripeCustomersByIdPathParamsSchema = z.object({
  id: z.string().max(36).describe("ID to identify the stripe user"),
});

/**
 * @description OK
 */
export const patchApiV1StripeCustomersById200Schema = z.lazy(
  () => getStripeCustomerResponseSchema,
);

/**
 * @description Error
 */
export const patchApiV1StripeCustomersByIdErrorSchema = z.lazy(
  () => errorModelSchema,
);

export const patchApiV1StripeCustomersByIdMutationRequestSchema = z
  .lazy(() => updateStripeCustomerBodySchema)
  .unwrap()
  .omit({ $schema: true });

export const patchApiV1StripeCustomersByIdMutationResponseSchema = z.lazy(
  () => patchApiV1StripeCustomersById200Schema,
);
