/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { postResponseSchema } from "./postResponseSchema.ts";
import { updatePostRequestSchema } from "./updatePostRequestSchema.ts";
import { z } from "zod/v4";

export const patchApiV1PostByIdPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description OK
 */
export const patchApiV1PostById200Schema = z.lazy(() => postResponseSchema)

/**
 * @description Error
 */
export const patchApiV1PostByIdErrorSchema = z.lazy(() => errorModelSchema)

export const patchApiV1PostByIdMutationRequestSchema = z.lazy(() => updatePostRequestSchema).unwrap().omit({ '$schema': true })

export const patchApiV1PostByIdMutationResponseSchema = z.lazy(() => patchApiV1PostById200Schema)