/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { sportResponseSchema } from "./sportResponseSchema.ts";
import { updateSportRequestSchema } from "./updateSportRequestSchema.ts";
import { z } from "zod/v4";

export const patchApiV1SportByIdPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description OK
 */
export const patchApiV1SportById200Schema = z.lazy(() => sportResponseSchema)

/**
 * @description Error
 */
export const patchApiV1SportByIdErrorSchema = z.lazy(() => errorModelSchema)

export const patchApiV1SportByIdMutationRequestSchema = z.lazy(() => updateSportRequestSchema).unwrap().omit({ '$schema': true })

export const patchApiV1SportByIdMutationResponseSchema = z.lazy(() => patchApiV1SportById200Schema)