/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorModelSchema } from "./errorModelSchema.ts";
import { updateUserBodySchema } from "./updateUserBodySchema.ts";
import { updateUserResponseSchema } from "./updateUserResponseSchema.ts";
import { z } from "zod/v4";

export const patchApiV1UserByIdPathParamsSchema = z.object({
    "id": z.string().max(36).describe("ID to identify the user")
    })

/**
 * @description OK
 */
export const patchApiV1UserById200Schema = z.lazy(() => updateUserResponseSchema)

/**
 * @description Error
 */
export const patchApiV1UserByIdErrorSchema = z.lazy(() => errorModelSchema)

export const patchApiV1UserByIdMutationRequestSchema = z.lazy(() => updateUserBodySchema).unwrap().omit({ '$schema': true })

export const patchApiV1UserByIdMutationResponseSchema = z.lazy(() => patchApiV1UserById200Schema)