/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { commentResponseSchema } from "./commentResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { updateCommentBodySchema } from "./updateCommentBodySchema.ts";
import { z } from "zod/v4";

export const patchApiV1CommentByIdPathParamsSchema = z.object({
  id: z.string().describe("ID of comment to update"),
});

/**
 * @description OK
 */
export const patchApiV1CommentById200Schema = z.lazy(
  () => commentResponseSchema,
);

/**
 * @description Error
 */
export const patchApiV1CommentByIdErrorSchema = z.lazy(() => errorModelSchema);

export const patchApiV1CommentByIdMutationRequestSchema = z
  .lazy(() => updateCommentBodySchema)
  .unwrap()
  .omit({ $schema: true });

export const patchApiV1CommentByIdMutationResponseSchema = z.lazy(
  () => patchApiV1CommentById200Schema,
);
