/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createStripePriceRequestSchema } from "./createStripePriceRequestSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { stripePriceResponseSchema } from "./stripePriceResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1StripePrice200Schema = z.lazy(() => stripePriceResponseSchema)

/**
 * @description Error
 */
export const postApiV1StripePriceErrorSchema = z.lazy(() => errorModelSchema)

export const postApiV1StripePriceMutationRequestSchema = z.lazy(() => createStripePriceRequestSchema).unwrap().omit({ '$schema': true })

export const postApiV1StripePriceMutationResponseSchema = z.lazy(() => postApiV1StripePrice200Schema)