/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createPostRequestSchema } from "./createPostRequestSchema.ts";
import { createPostResponseSchema } from "./createPostResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1Post200Schema = z.lazy(() => createPostResponseSchema)

/**
 * @description Error
 */
export const postApiV1PostErrorSchema = z.lazy(() => errorModelSchema)

export const postApiV1PostMutationRequestSchema = z.lazy(() => createPostRequestSchema).unwrap().omit({ '$schema': true })

export const postApiV1PostMutationResponseSchema = z.lazy(() => postApiV1Post200Schema)