/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createTagFollowBodySchema } from "./createTagFollowBodySchema.ts";
import { createTagFollowResponseSchema } from "./createTagFollowResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1UserTag200Schema = z.lazy(
  () => createTagFollowResponseSchema,
);

/**
 * @description Error
 */
export const postApiV1UserTagErrorSchema = z.lazy(() => errorModelSchema);

export const postApiV1UserTagMutationRequestSchema = z
  .lazy(() => createTagFollowBodySchema)
  .unwrap()
  .omit({ $schema: true });

export const postApiV1UserTagMutationResponseSchema = z.lazy(
  () => postApiV1UserTag200Schema,
);
