/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createPremiumPostParamsSchema } from "./createPremiumPostParamsSchema.ts";
import { createPremiumPostResponseSchema } from "./createPremiumPostResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1PostPremium200Schema = z.lazy(
  () => createPremiumPostResponseSchema,
);

/**
 * @description Error
 */
export const postApiV1PostPremiumErrorSchema = z.lazy(() => errorModelSchema);

export const postApiV1PostPremiumMutationRequestSchema = z
  .lazy(() => createPremiumPostParamsSchema)
  .unwrap()
  .omit({ $schema: true });

export const postApiV1PostPremiumMutationResponseSchema = z.lazy(
  () => postApiV1PostPremium200Schema,
);
