/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createSportFollowBodySchema } from "./createSportFollowBodySchema.ts";
import { createSportFollowResponseSchema } from "./createSportFollowResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1UserSport200Schema = z.lazy(
  () => createSportFollowResponseSchema,
);

/**
 * @description Error
 */
export const postApiV1UserSportErrorSchema = z.lazy(() => errorModelSchema);

export const postApiV1UserSportMutationRequestSchema = z
  .lazy(() => createSportFollowBodySchema)
  .unwrap()
  .omit({ $schema: true });

export const postApiV1UserSportMutationResponseSchema = z.lazy(
  () => postApiV1UserSport200Schema,
);
