/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createCollegeRequestSchema } from "./createCollegeRequestSchema.ts";
import { createCollegeResponseSchema } from "./createCollegeResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1College200Schema = z.lazy(() => createCollegeResponseSchema)

/**
 * @description Error
 */
export const postApiV1CollegeErrorSchema = z.lazy(() => errorModelSchema)

export const postApiV1CollegeMutationRequestSchema = z.lazy(() => createCollegeRequestSchema).unwrap().omit({ '$schema': true })

export const postApiV1CollegeMutationResponseSchema = z.lazy(() => postApiV1College200Schema)