/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createPermissionRequestSchema } from "./createPermissionRequestSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { permissionResponseSchema } from "./permissionResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1Permission200Schema = z.lazy(() => permissionResponseSchema)

/**
 * @description Error
 */
export const postApiV1PermissionErrorSchema = z.lazy(() => errorModelSchema)

export const postApiV1PermissionMutationRequestSchema = z.lazy(() => createPermissionRequestSchema).unwrap().omit({ '$schema': true })

export const postApiV1PermissionMutationResponseSchema = z.lazy(() => postApiV1Permission200Schema)