/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createCommentLikeBodySchema } from "./createCommentLikeBodySchema.ts";
import { createCommentLikeResponseSchema } from "./createCommentLikeResponseSchema.ts";
import { errorModelSchema } from "./errorModelSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postApiV1CommentLike200Schema = z.lazy(() => createCommentLikeResponseSchema)

/**
 * @description Error
 */
export const postApiV1CommentLikeErrorSchema = z.lazy(() => errorModelSchema)

export const postApiV1CommentLikeMutationRequestSchema = z.lazy(() => createCommentLikeBodySchema).unwrap().omit({ '$schema': true })

export const postApiV1CommentLikeMutationResponseSchema = z.lazy(() => postApiV1CommentLike200Schema)