/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { sportResponseSchema } from "./sportResponseSchema.ts";
import { z } from "zod/v4";

export const searchResultsSportResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get results() {
    return z.array(sportResponseSchema).nullable();
  },
});
