/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { getTagResponseSchema } from "./getTagResponseSchema.ts";
import { z } from "zod/v4";

export const searchResultsGetTagResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  get results() {
    return z.array(getTagResponseSchema).nullable();
  },
});
