/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const sportResponseSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
"id": z.string().describe("ID of the sport"),
"name": z.string().describe("Name of the sport"),
"popularity": z.optional(z.int().describe("Number of players"))
    })