/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const tagSchema = z.object({
    "created_at": z.iso.datetime(),
"deleted_at": z.nullable(z.iso.datetime()),
"id": z.string(),
"name": z.string().describe("The name of the tag"),
"updated_at": z.iso.datetime()
    })