/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateStripeCustomerBodySchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  balance: z.optional(
    z.int().describe("Current balance in cents (can be negative)"),
  ),
  coupon: z.optional(z.string().describe("Coupon ID to apply discount")),
  default_source: z.optional(
    z.string().describe("ID of default payment source"),
  ),
  description: z.optional(z.string().describe("Description of customer")),
  email: z.optional(z.string().describe("Customer email")),
  metadata: z.optional(
    z
      .object({})
      .catchall(z.string())
      .describe("Set of key-value pairs for metadata"),
  ),
  name: z.optional(z.string().describe("Customer name")),
  phone: z.optional(z.string().describe("Customer phone number")),
  preferred_locales: z
    .array(z.string())
    .describe("Customer's preferred languages")
    .nullish(),
  promotion_code: z.optional(z.string().describe("Promotion code to apply")),
  tax_exempt: z.optional(
    z.string().describe("Tax exemption status: none, exempt, or reverse"),
  ),
});
