/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateTagResponseSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  id: z.string().describe("ID of the tag updated"),
  name: z.string().describe("The updated name of the tag"),
  type: z.string().describe("The type of the tag"),
});
