/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updateStripePriceRequestSchema = z.object({
    "$schema": z.optional(z.url().describe("A URL to the JSON Schema for this object.")),
"interval": z.nullable(z.string().describe("Interval between payments")),
"interval_count": z.nullable(z.int().describe("Number of intervals a billing cycle lasts")),
"total": z.nullable(z.int().describe("Price per billing cycle."))
    })