/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updatePremiumPostRequestSchema = z.object({
  $schema: z.optional(
    z.url().describe("A URL to the JSON Schema for this object."),
  ),
  content: z.optional(z.string().min(1).max(5000)),
  media_id: z.optional(z.string()),
  title: z.optional(z.string().min(1).max(100)),
});
