/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const userRoleResponseSchema = z.object({
    "id": z.string().describe("ID of the role"),
"name": z.string().describe("Name of the role")
    })